from __future__ import division

import ROOT
import lheanalyzer
import math

import sys
#######
#
# usage: python analyse_example.py input.lhe output.root
#
#######

#Create lhe analysis from lhe file
analysis = lheanalyzer.LHEAnalysis(sys.argv[1])
ROOT.TH1.SetDefaultSumw2()

# DeltaR
h_dr_t_H = ROOT.TH1F("h_dr_t_H","",30,0.,5.)
h_dr_t_j = ROOT.TH1F("h_dr_t_j","",30,0.,5.)
h_dr_t_Hb = ROOT.TH1F("h_dr_t_Hb","",30,0.,5.)
h_dr_t_tb = ROOT.TH1F("h_dr_t_tb","",30,0.,5.)
h_dr_t_W = ROOT.TH1F("h_dr_t_W","",30,0.,5.)
h_dr_t_tWl = ROOT.TH1F("h_dr_t_tWl","",30,0.,5.)
h_dr_t_tWnu = ROOT.TH1F("h_dr_t_tWnu","",30,0.,5.)
h_dr_H_j = ROOT.TH1F("h_dr_H_j","",30,0.,5.)
h_dr_H_Hb = ROOT.TH1F("h_dr_H_Hb","",30,0.,5.)
h_dr_H_tb = ROOT.TH1F("h_dr_H_tb","",30,0.,5.)
h_dr_H_W = ROOT.TH1F("h_dr_H_W","",30,0.,5.)
h_dr_H_tWl = ROOT.TH1F("h_dr_H_tWl","",30,0.,5.)
h_dr_H_tWnu = ROOT.TH1F("h_dr_H_tWnu","",30,0.,5.)
h_dr_W_tWl = ROOT.TH1F("h_dr_W_tWl","",30,0.,5.)
h_dr_W_tWnu = ROOT.TH1F("h_dr_W_tWnu","",30,0.,5.)
h_dr_j_Hb = ROOT.TH1F("h_dr_j_Hb","",30,0.,5.)
h_dr_j_tb = ROOT.TH1F("h_dr_j_tb","",30,0.,5.)
h_dr_j_W = ROOT.TH1F("h_dr_j_W","",30,0.,5.)
h_dr_j_tWl = ROOT.TH1F("h_dr_j_tWl","",30,0.,5.)
h_dr_j_tWnu = ROOT.TH1F("h_dr_j_tWnu","",30,0.,5.)
h_dr_Hb_tb = ROOT.TH1F("h_dr_Hb_tb","",30,0.,5.)
h_dr_Hb_W = ROOT.TH1F("h_dr_Hb_W","",30,0.,5.)
h_dr_Hb_tWl = ROOT.TH1F("h_dr_Hb_tWl","",30,0.,5.)
h_dr_Hb_tWnu = ROOT.TH1F("h_dr_Hb_tWnu","",30,0.,5.)
h_dr_tb_W = ROOT.TH1F("h_dr_tb_W","",30,0.,5.)
h_dr_tb_tWl = ROOT.TH1F("h_dr_tb_tWl","",30,0.,5.)
h_dr_tb_tWnu = ROOT.TH1F("h_dr_tb_tWnu","",30,0.,5.)
h_dr_tWl_tWnu = ROOT.TH1F("h_dr_tWl_tWnu","",30,0.,5.)
h_dr_Hb1_Hb2 = ROOT.TH1F("h_dr_Hb1_Hb2","",30,0.,5.)

# CosTheta 
h_costheta_t_H = ROOT.TH1F("h_costheta_t_H","",30,-1.,1.)
h_costheta_t_j = ROOT.TH1F("h_costheta_t_j","",30,-1.,1.)
h_costheta_t_Hb = ROOT.TH1F("h_costheta_t_Hb","",30,-1.,1.)
h_costheta_t_tb = ROOT.TH1F("h_costheta_t_tb","",30,-1.,1.)
h_costheta_t_W = ROOT.TH1F("h_costheta_t_W","",30,-1.,1.)
h_costheta_t_tWl = ROOT.TH1F("h_costheta_t_tWl","",30,-1.,1.)
h_costheta_t_tWnu = ROOT.TH1F("h_costheta_t_tWnu","",30,-1.,1.)
h_costheta_H_j = ROOT.TH1F("h_costheta_H_j","",30,-1.,1.)
h_costheta_H_Hb = ROOT.TH1F("h_costheta_H_Hb","",30,-1.,1.)
h_costheta_H_tb = ROOT.TH1F("h_costheta_H_tb","",30,-1.,1.)
h_costheta_H_W = ROOT.TH1F("h_costheta_H_W","",30,-1.,1.)
h_costheta_H_tWl = ROOT.TH1F("h_costheta_H_tWl","",30,-1.,1.)
h_costheta_H_tWnu = ROOT.TH1F("h_costheta_H_tWnu","",30,-1.,1.)
h_costheta_W_tWl = ROOT.TH1F("h_costheta_W_tWl","",30,-1.,1.)
h_costheta_W_tWnu = ROOT.TH1F("h_costheta_W_tWnu","",30,-1.,1.)
h_costheta_j_Hb = ROOT.TH1F("h_costheta_j_Hb","",30,-1.,1.)
h_costheta_j_tb = ROOT.TH1F("h_costheta_j_tb","",30,-1.,1.)
h_costheta_j_W = ROOT.TH1F("h_costheta_j_W","",30,-1.,1.)
h_costheta_j_tWl = ROOT.TH1F("h_costheta_j_tWl","",30,-1.,1.)
h_costheta_j_tWnu = ROOT.TH1F("h_costheta_j_tWnu","",30,-1.,1.)
h_costheta_Hb_tb = ROOT.TH1F("h_costheta_Hb_tb","",30,-1.,1.)
h_costheta_Hb_W = ROOT.TH1F("h_costheta_Hb_W","",30,-1.,1.)
h_costheta_Hb_tWl = ROOT.TH1F("h_costheta_Hb_tWl","",30,-1.,1.)
h_costheta_Hb_tWnu = ROOT.TH1F("h_costheta_Hb_tWnu","",30,-1.,1.)
h_costheta_tb_W = ROOT.TH1F("h_costheta_tb_W","",30,-1.,1.)
h_costheta_tb_tWl = ROOT.TH1F("h_costheta_tb_tWl","",30,-1.,1.)
h_costheta_tb_tWnu = ROOT.TH1F("h_costheta_tb_tWnu","",30,-1.,1.)
h_costheta_tWl_tWnu = ROOT.TH1F("h_costheta_tWl_tWnu","",30,-1.,1.)
h_costheta_Hb1_Hb2 = ROOT.TH1F("h_costheta_Hb1_Hb2","",30,-1.,1.)

# pT
h_pt_t = ROOT.TH1F("h_pt_t","",30,0.,300.)
h_pt_H = ROOT.TH1F("h_pt_H","",30,0.,300.)
h_pt_j = ROOT.TH1F("h_pt_j","",30,0.,300.)
h_pt_Hb = ROOT.TH1F("h_pt_Hb","",30,0.,300.)
h_pt_tb = ROOT.TH1F("h_pt_tb","",30,0.,300.)
h_pt_W = ROOT.TH1F("h_pt_W","",30,0.,300.)
h_pt_tWl = ROOT.TH1F("h_pt_tWl","",30,0.,300.)
h_pt_tWnu = ROOT.TH1F("h_pt_tWnu","",30,0.,300.)

# eta
h_eta_t = ROOT.TH1F("h_eta_t","",30,-5.,5.)
h_eta_H = ROOT.TH1F("h_eta_H","",30,-5.,5.)
h_eta_j = ROOT.TH1F("h_eta_j","",30,-5.,5.)
h_eta_Hb = ROOT.TH1F("h_eta_Hb","",30,-5.,5.)
h_eta_tb = ROOT.TH1F("h_eta_tb","",30,-5.,5.)
h_eta_W = ROOT.TH1F("h_eta_W","",30,-5.,5.)
h_eta_tWl = ROOT.TH1F("h_eta_tWl","",30,-5.,5.)
h_eta_tWnu = ROOT.TH1F("h_eta_tWnu","",30,-5.,5.)

# phi
h_phi_t = ROOT.TH1F("h_phi_t","",30,-3.2,3.2)
h_phi_H = ROOT.TH1F("h_phi_H","",30,-3.2,3.2)
h_phi_j = ROOT.TH1F("h_phi_j","",30,-3.2,3.2)
h_phi_Hb = ROOT.TH1F("h_phi_Hb","",30,-3.2,3.2)
h_phi_tb = ROOT.TH1F("h_phi_tb","",30,-3.2,3.2)
h_phi_W = ROOT.TH1F("h_phi_W","",30,-3.2,3.2)
h_phi_tWl = ROOT.TH1F("h_phi_tWl","",30,-3.2,3.2)
h_phi_tWnu = ROOT.TH1F("h_phi_tWnu","",30,-3.2,3.2)

#h_ratio = ROOT.TH1F("h_ratio","",1,0.,30.)
nevents = 1

#evpos30t60=0
#evneg30t60=0

for event in analysis:
    if nevents == 40000: break

    tb = filter(lambda particle: (particle.pdgId in [5, -5, 3, -3]) and (particle.mother[0] not in [4, 6]) and (particle.mother[0] > 0), event.particles)
    Hb = filter(lambda particle: (particle.pdgId in [5, -5]) and (particle.mother[0] in [4, 6]), event.particles)
    t = filter(lambda particle: particle.pdgId in [6, -6], event.particles)
    j = filter(lambda particle: (particle.pdgId in [2, -2, 4, -4] and (particle.mother[0] > 0)), event.particles)
    H = filter(lambda particle: particle.pdgId in [25], event.particles)
    W = filter(lambda particle: particle.pdgId in [24, -24], event.particles)
    l = filter(lambda particle: particle.pdgId in [11, 13, -11, -13, 15, -15], event.particles)
    nu = filter(lambda particle: particle.pdgId in [12, 14, -12, -14, 16, -16], event.particles)
    lminus = filter(lambda particle: particle.pdgId in [11, 13], event.particles)
    lplus = filter(lambda particle: particle.pdgId in [-11, -13], event.particles)
    nevents = nevents+1
    
    # Calculate variables
    
    dr_t1_H = t[0].tLorentzVector.DeltaR(H[0].tLorentzVector)
    dr_t2_H = t[1].tLorentzVector.DeltaR(H[0].tLorentzVector)
    dr_t1_j = t[0].tLorentzVector.DeltaR(j[0].tLorentzVector)
    dr_t2_j = t[1].tLorentzVector.DeltaR(j[0].tLorentzVector)
    dr_t1_Hb1 = t[0].tLorentzVector.DeltaR(Hb[0].tLorentzVector)
    dr_t2_Hb1 = t[1].tLorentzVector.DeltaR(Hb[0].tLorentzVector)
    dr_t1_Hb2 = t[0].tLorentzVector.DeltaR(Hb[1].tLorentzVector)
    dr_t2_Hb2 = t[1].tLorentzVector.DeltaR(Hb[1].tLorentzVector)
    dr_t1_tb = t[0].tLorentzVector.DeltaR(tb[0].tLorentzVector)
    dr_t2_tb = t[1].tLorentzVector.DeltaR(tb[0].tLorentzVector)
    dr_t1_W = t[0].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_t2_W = t[1].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_t1_tWl = t[0].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_t2_tWl = t[1].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_t1_tWnu = t[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_t2_tWnu = t[1].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_H_j = H[0].tLorentzVector.DeltaR(j[0].tLorentzVector)
    dr_H_Hb1 = H[0].tLorentzVector.DeltaR(Hb[0].tLorentzVector)
    dr_H_Hb2 = H[0].tLorentzVector.DeltaR(Hb[1].tLorentzVector)
    dr_H_tb = H[0].tLorentzVector.DeltaR(tb[0].tLorentzVector)
    dr_H_W = H[0].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_H_tWl = H[0].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_H_tWnu = H[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_W_tWl = W[0].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_W_tWnu = W[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_j_Hb1 = j[0].tLorentzVector.DeltaR(Hb[0].tLorentzVector)
    dr_j_Hb2 = j[0].tLorentzVector.DeltaR(Hb[1].tLorentzVector)
    dr_j_tb = j[0].tLorentzVector.DeltaR(tb[0].tLorentzVector)
    dr_j_W = j[0].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_j_tWl = j[0].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_j_tWnu = j[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_Hb1_tb = Hb[0].tLorentzVector.DeltaR(tb[0].tLorentzVector)
    dr_Hb2_tb = Hb[1].tLorentzVector.DeltaR(tb[0].tLorentzVector)
    dr_Hb1_W = Hb[0].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_Hb2_W = Hb[1].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_Hb1_tWl = Hb[0].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_Hb2_tWl = Hb[1].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_Hb1_tWnu = Hb[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_Hb2_tWnu = Hb[1].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_tb_W = tb[0].tLorentzVector.DeltaR(W[0].tLorentzVector)
    dr_tb_tWl = tb[0].tLorentzVector.DeltaR(l[0].tLorentzVector)
    dr_tb_tWnu = tb[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_tWl_tWnu = l[0].tLorentzVector.DeltaR(nu[0].tLorentzVector)
    dr_Hb1_Hb2 = Hb[0].tLorentzVector.DeltaR(Hb[1].tLorentzVector)

    costheta_t1_H = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(H[0].tLorentzVector.Vect()))
    costheta_t2_H = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(H[0].tLorentzVector.Vect()))
    costheta_t1_j = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(j[0].tLorentzVector.Vect()))
    costheta_t2_j = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(j[0].tLorentzVector.Vect()))
    costheta_t1_Hb1 = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(Hb[0].tLorentzVector.Vect()))
    costheta_t2_Hb1 = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(Hb[0].tLorentzVector.Vect()))
    costheta_t1_Hb2 = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(Hb[1].tLorentzVector.Vect()))
    costheta_t2_Hb2 = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(Hb[1].tLorentzVector.Vect()))
    costheta_t1_tb = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(tb[0].tLorentzVector.Vect()))
    costheta_t2_tb = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(tb[0].tLorentzVector.Vect()))
    costheta_t1_W = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_t2_W = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_t1_tWl = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_t2_tWl = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_t1_tWnu = ROOT.TMath.Cos(t[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_t2_tWnu = ROOT.TMath.Cos(t[1].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_H_j = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(j[0].tLorentzVector.Vect()))
    costheta_H_Hb1 = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(Hb[0].tLorentzVector.Vect()))
    costheta_H_Hb2 = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(Hb[1].tLorentzVector.Vect()))
    costheta_H_tb = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(tb[0].tLorentzVector.Vect()))
    costheta_H_W = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_H_tWl = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_H_tWnu = ROOT.TMath.Cos(H[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_W_tWl = ROOT.TMath.Cos(W[0].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_W_tWnu = ROOT.TMath.Cos(W[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_j_Hb1 = ROOT.TMath.Cos(j[0].tLorentzVector.Angle(Hb[0].tLorentzVector.Vect()))
    costheta_j_Hb2 = ROOT.TMath.Cos(j[0].tLorentzVector.Angle(Hb[1].tLorentzVector.Vect()))
    costheta_j_tb = ROOT.TMath.Cos(j[0].tLorentzVector.Angle(tb[0].tLorentzVector.Vect()))
    costheta_j_W = ROOT.TMath.Cos(j[0].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_j_tWl = ROOT.TMath.Cos(j[0].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_j_tWnu = ROOT.TMath.Cos(j[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_Hb1_tb = ROOT.TMath.Cos(Hb[0].tLorentzVector.Angle(tb[0].tLorentzVector.Vect()))
    costheta_Hb2_tb = ROOT.TMath.Cos(Hb[1].tLorentzVector.Angle(tb[0].tLorentzVector.Vect()))
    costheta_Hb1_W = ROOT.TMath.Cos(Hb[0].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_Hb2_W = ROOT.TMath.Cos(Hb[1].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_Hb1_tWl = ROOT.TMath.Cos(Hb[0].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_Hb2_tWl = ROOT.TMath.Cos(Hb[1].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_Hb1_tWnu = ROOT.TMath.Cos(Hb[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_Hb2_tWnu = ROOT.TMath.Cos(Hb[1].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_tb_W = ROOT.TMath.Cos(tb[0].tLorentzVector.Angle(W[0].tLorentzVector.Vect()))
    costheta_tb_tWl = ROOT.TMath.Cos(tb[0].tLorentzVector.Angle(l[0].tLorentzVector.Vect()))
    costheta_tb_tWnu = ROOT.TMath.Cos(tb[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_tWl_tWnu = ROOT.TMath.Cos(l[0].tLorentzVector.Angle(nu[0].tLorentzVector.Vect()))
    costheta_Hb1_Hb2 = ROOT.TMath.Cos(Hb[0].tLorentzVector.Angle(Hb[1].tLorentzVector.Vect()))

    pt_t1 = t[0].tLorentzVector.Pt()
    pt_t2 = t[1].tLorentzVector.Pt()
    pt_H = H[0].tLorentzVector.Pt()
    pt_j = j[0].tLorentzVector.Pt()
    pt_Hb1 = Hb[0].tLorentzVector.Pt()
    pt_Hb2 = Hb[1].tLorentzVector.Pt()
    pt_tb = tb[0].tLorentzVector.Pt()
    pt_W = W[0].tLorentzVector.Pt()
    pt_tWl = l[0].tLorentzVector.Pt()
    pt_tWnu = nu[0].tLorentzVector.Pt()

    eta_t1 = t[0].tLorentzVector.PseudoRapidity()
    eta_t2 = t[1].tLorentzVector.PseudoRapidity()
    eta_H = H[0].tLorentzVector.PseudoRapidity()
    eta_j = j[0].tLorentzVector.PseudoRapidity()
    eta_Hb1 = Hb[0].tLorentzVector.PseudoRapidity()
    eta_Hb2 = Hb[1].tLorentzVector.PseudoRapidity()
    eta_tb = tb[0].tLorentzVector.PseudoRapidity()
    eta_W = W[0].tLorentzVector.PseudoRapidity()
    eta_tWl = l[0].tLorentzVector.PseudoRapidity()
    eta_tWnu = nu[0].tLorentzVector.PseudoRapidity()
    
    phi_t1 = t[0].tLorentzVector.Phi()
    phi_t2 = t[1].tLorentzVector.Phi()
    phi_H = H[0].tLorentzVector.Phi()
    phi_j = j[0].tLorentzVector.Phi()
    phi_Hb1 = Hb[0].tLorentzVector.Phi()
    phi_Hb2 = Hb[1].tLorentzVector.Phi()
    phi_tb = tb[0].tLorentzVector.Phi()
    phi_W = W[0].tLorentzVector.Phi()
    phi_tWl = l[0].tLorentzVector.Phi()
    phi_tWnu = nu[0].tLorentzVector.Phi()
    
    # Fill histograms

    h_dr_t_H.Fill(dr_t1_H,1.)
    h_dr_t_H.Fill(dr_t2_H,1.)
    h_dr_t_j.Fill(dr_t1_j,1.)
    h_dr_t_j.Fill(dr_t2_j,1.)
    h_dr_t_Hb.Fill(dr_t1_Hb1,1.)
    h_dr_t_Hb.Fill(dr_t2_Hb1,1.)
    h_dr_t_Hb.Fill(dr_t1_Hb2,1.)
    h_dr_t_Hb.Fill(dr_t2_Hb2,1.)
    h_dr_t_tb.Fill(dr_t1_tb,1.)
    h_dr_t_tb.Fill(dr_t2_tb,1.)
    h_dr_t_W.Fill(dr_t1_W,1.)
    h_dr_t_W.Fill(dr_t2_W,1.)
    h_dr_t_tWl.Fill(dr_t1_tWl,1.)
    h_dr_t_tWl.Fill(dr_t2_tWl,1.)
    h_dr_t_tWnu.Fill(dr_t1_tWnu,1.)
    h_dr_t_tWnu.Fill(dr_t2_tWnu,1.)
    h_dr_H_j.Fill(dr_H_j,1.)
    h_dr_H_Hb.Fill(dr_H_Hb1,1.)
    h_dr_H_Hb.Fill(dr_H_Hb2,1.)
    h_dr_H_tb.Fill(dr_H_tb,1.)
    h_dr_H_W.Fill(dr_H_W,1.)
    h_dr_H_tWl.Fill(dr_H_tWl,1.)
    h_dr_H_tWnu.Fill(dr_H_tWnu,1.)
    h_dr_W_tWl.Fill(dr_W_tWl,1.)
    h_dr_W_tWnu.Fill(dr_W_tWnu,1.)
    h_dr_j_Hb.Fill(dr_j_Hb1,1.)
    h_dr_j_Hb.Fill(dr_j_Hb2,1.)
    h_dr_j_tb.Fill(dr_j_tb,1.)
    h_dr_j_W.Fill(dr_j_W,1.)
    h_dr_j_tWl.Fill(dr_j_tWl,1.)
    h_dr_j_tWnu.Fill(dr_j_tWnu,1.)
    h_dr_Hb_tb.Fill(dr_Hb1_tb,1.)
    h_dr_Hb_tb.Fill(dr_Hb2_tb,1.)
    h_dr_Hb_W.Fill(dr_Hb1_W,1.)
    h_dr_Hb_W.Fill(dr_Hb2_W,1.)
    h_dr_Hb_tWl.Fill(dr_Hb1_tWl,1.)
    h_dr_Hb_tWl.Fill(dr_Hb2_tWl,1.)
    h_dr_Hb_tWnu.Fill(dr_Hb1_tWnu,1.)
    h_dr_Hb_tWnu.Fill(dr_Hb2_tWnu,1.)
    h_dr_tb_W.Fill(dr_tb_W,1.)
    h_dr_tb_tWl.Fill(dr_tb_tWl,1.)
    h_dr_tb_tWnu.Fill(dr_tb_tWnu,1.)
    h_dr_tWl_tWnu.Fill(dr_tWl_tWnu,1.)
    h_dr_Hb1_Hb2.Fill(dr_Hb1_Hb2,1.)

    h_costheta_t_H.Fill(costheta_t1_H,1.)
    h_costheta_t_H.Fill(costheta_t2_H,1.)
    h_costheta_t_j.Fill(costheta_t1_j,1.)
    h_costheta_t_j.Fill(costheta_t2_j,1.)
    h_costheta_t_Hb.Fill(costheta_t1_Hb1,1.)
    h_costheta_t_Hb.Fill(costheta_t2_Hb1,1.)
    h_costheta_t_Hb.Fill(costheta_t1_Hb2,1.)
    h_costheta_t_Hb.Fill(costheta_t2_Hb2,1.)
    h_costheta_t_tb.Fill(costheta_t1_tb,1.)
    h_costheta_t_tb.Fill(costheta_t2_tb,1.)
    h_costheta_t_W.Fill(costheta_t1_W,1.)
    h_costheta_t_W.Fill(costheta_t2_W,1.)
    h_costheta_t_tWl.Fill(costheta_t1_tWl,1.)
    h_costheta_t_tWl.Fill(costheta_t2_tWl,1.)
    h_costheta_t_tWnu.Fill(costheta_t1_tWnu,1.)
    h_costheta_t_tWnu.Fill(costheta_t2_tWnu,1.)
    h_costheta_H_j.Fill(costheta_H_j,1.)
    h_costheta_H_Hb.Fill(costheta_H_Hb1,1.)
    h_costheta_H_Hb.Fill(costheta_H_Hb2,1.)
    h_costheta_H_tb.Fill(costheta_H_tb,1.)
    h_costheta_H_W.Fill(costheta_H_W,1.)
    h_costheta_H_tWl.Fill(costheta_H_tWl,1.)
    h_costheta_H_tWnu.Fill(costheta_H_tWnu,1.)
    h_costheta_W_tWl.Fill(costheta_W_tWl,1.)
    h_costheta_W_tWnu.Fill(costheta_W_tWnu,1.)
    h_costheta_j_Hb.Fill(costheta_j_Hb1,1.)
    h_costheta_j_Hb.Fill(costheta_j_Hb2,1.)
    h_costheta_j_tb.Fill(costheta_j_tb,1.)
    h_costheta_j_W.Fill(costheta_j_W,1.)
    h_costheta_j_tWl.Fill(costheta_j_tWl,1.)
    h_costheta_j_tWnu.Fill(costheta_j_tWnu,1.)
    h_costheta_Hb_tb.Fill(costheta_Hb1_tb,1.)
    h_costheta_Hb_tb.Fill(costheta_Hb2_tb,1.)
    h_costheta_Hb_W.Fill(costheta_Hb1_W,1.)
    h_costheta_Hb_W.Fill(costheta_Hb2_W,1.)
    h_costheta_Hb_tWl.Fill(costheta_Hb1_tWl,1.)
    h_costheta_Hb_tWl.Fill(costheta_Hb2_tWl,1.)
    h_costheta_Hb_tWnu.Fill(costheta_Hb1_tWnu,1.)
    h_costheta_Hb_tWnu.Fill(costheta_Hb2_tWnu,1.)
    h_costheta_tb_W.Fill(costheta_tb_W,1.)
    h_costheta_tb_tWl.Fill(costheta_tb_tWl,1.)
    h_costheta_tb_tWnu.Fill(costheta_tb_tWnu,1.)
    h_costheta_tWl_tWnu.Fill(costheta_tWl_tWnu,1.)
    h_costheta_Hb1_Hb2.Fill(costheta_Hb1_Hb2,1.)
    
    h_pt_t.Fill(pt_t1,1.)
    h_pt_t.Fill(pt_t2,1.)
    h_pt_H.Fill(pt_H,1.)
    h_pt_j.Fill(pt_j,1.)
    h_pt_Hb.Fill(pt_Hb1,1.)
    h_pt_Hb.Fill(pt_Hb2,1.)
    h_pt_tb.Fill(pt_tb,1.)
    h_pt_W.Fill(pt_W,1.)
    h_pt_tWl.Fill(pt_tWl,1.)
    h_pt_tWnu.Fill(pt_tWnu,1.)

    h_eta_t.Fill(eta_t1,1.)
    h_eta_t.Fill(eta_t2,1.)
    h_eta_H.Fill(eta_H,1.)
    h_eta_j.Fill(eta_j,1.)
    h_eta_Hb.Fill(eta_Hb1,1.)
    h_eta_Hb.Fill(eta_Hb2,1.)
    h_eta_tb.Fill(eta_tb,1.)
    h_eta_W.Fill(eta_W,1.)
    h_eta_tWl.Fill(eta_tWl,1.)
    h_eta_tWnu.Fill(eta_tWnu,1.)

    h_phi_t.Fill(phi_t1,1.)
    h_phi_t.Fill(phi_t2,1.)
    h_phi_H.Fill(phi_H,1.)
    h_phi_j.Fill(phi_j,1.)
    h_phi_Hb.Fill(phi_Hb1,1.)
    h_phi_Hb.Fill(phi_Hb2,1.)
    h_phi_tb.Fill(phi_tb,1.)
    h_phi_W.Fill(phi_W,1.)
    h_phi_tWl.Fill(phi_tWl,1.)
    h_phi_tWnu.Fill(phi_tWnu,1.)
    
#    if len(lplus) == 1 and lplus[0].tLorentzVector.Pt() > 30 and lplus[0].tLorentzVector.Pt() < 60:
#        evpos30t60=evpos30t60+1
#    if len(lminus) == 1 and lminus[0].tLorentzVector.Pt() > 30 and lminus[0].tLorentzVector.Pt() < 60:
#        evneg30t60=evneg30t60+1
    
#h_ratio.SetBinContent(1,evpos30t60/evneg30t60)

outfile = ROOT.TFile(sys.argv[2],"RECREATE")

# Save histograms

outfile.WriteTObject(h_dr_t_H)
outfile.WriteTObject(h_dr_t_j)
outfile.WriteTObject(h_dr_t_Hb)
outfile.WriteTObject(h_dr_t_tb)
outfile.WriteTObject(h_dr_t_W)
outfile.WriteTObject(h_dr_t_tWl)
outfile.WriteTObject(h_dr_t_tWnu)
outfile.WriteTObject(h_dr_H_j)
outfile.WriteTObject(h_dr_H_Hb)
outfile.WriteTObject(h_dr_H_tb)
outfile.WriteTObject(h_dr_H_W)
outfile.WriteTObject(h_dr_H_tWl)
outfile.WriteTObject(h_dr_H_tWnu)
outfile.WriteTObject(h_dr_W_tWl)
outfile.WriteTObject(h_dr_W_tWnu)
outfile.WriteTObject(h_dr_j_Hb)
outfile.WriteTObject(h_dr_j_tb)
outfile.WriteTObject(h_dr_j_W)
outfile.WriteTObject(h_dr_j_tWl)
outfile.WriteTObject(h_dr_j_tWnu)
outfile.WriteTObject(h_dr_Hb_tb)
outfile.WriteTObject(h_dr_Hb_W)
outfile.WriteTObject(h_dr_Hb_tWl)
outfile.WriteTObject(h_dr_Hb_tWnu)
outfile.WriteTObject(h_dr_tb_W)
outfile.WriteTObject(h_dr_tb_tWl)
outfile.WriteTObject(h_dr_tb_tWnu)
outfile.WriteTObject(h_dr_tWl_tWnu)
outfile.WriteTObject(h_dr_Hb1_Hb2)

outfile.WriteTObject(h_costheta_t_H)
outfile.WriteTObject(h_costheta_t_j)
outfile.WriteTObject(h_costheta_t_Hb)
outfile.WriteTObject(h_costheta_t_tb)
outfile.WriteTObject(h_costheta_t_W)
outfile.WriteTObject(h_costheta_t_tWl)
outfile.WriteTObject(h_costheta_t_tWnu)
outfile.WriteTObject(h_costheta_H_j)
outfile.WriteTObject(h_costheta_H_Hb)
outfile.WriteTObject(h_costheta_H_tb)
outfile.WriteTObject(h_costheta_H_W)
outfile.WriteTObject(h_costheta_H_tWl)
outfile.WriteTObject(h_costheta_H_tWnu)
outfile.WriteTObject(h_costheta_W_tWl)
outfile.WriteTObject(h_costheta_W_tWnu)
outfile.WriteTObject(h_costheta_j_Hb)
outfile.WriteTObject(h_costheta_j_tb)
outfile.WriteTObject(h_costheta_j_W)
outfile.WriteTObject(h_costheta_j_tWl)
outfile.WriteTObject(h_costheta_j_tWnu)
outfile.WriteTObject(h_costheta_Hb_tb)
outfile.WriteTObject(h_costheta_Hb_W)
outfile.WriteTObject(h_costheta_Hb_tWl)
outfile.WriteTObject(h_costheta_Hb_tWnu)
outfile.WriteTObject(h_costheta_tb_W)
outfile.WriteTObject(h_costheta_tb_tWl)
outfile.WriteTObject(h_costheta_tb_tWnu)
outfile.WriteTObject(h_costheta_tWl_tWnu)
outfile.WriteTObject(h_costheta_Hb1_Hb2)

outfile.WriteTObject(h_pt_t)
outfile.WriteTObject(h_pt_H)
outfile.WriteTObject(h_pt_j)
outfile.WriteTObject(h_pt_Hb)
outfile.WriteTObject(h_pt_tb)
outfile.WriteTObject(h_pt_W)
outfile.WriteTObject(h_pt_tWl)
outfile.WriteTObject(h_pt_tWnu)

outfile.WriteTObject(h_eta_t)
outfile.WriteTObject(h_eta_H)
outfile.WriteTObject(h_eta_j)
outfile.WriteTObject(h_eta_Hb)
outfile.WriteTObject(h_eta_tb)
outfile.WriteTObject(h_eta_W)
outfile.WriteTObject(h_eta_tWl)
outfile.WriteTObject(h_eta_tWnu)

outfile.WriteTObject(h_phi_t)
outfile.WriteTObject(h_phi_H)
outfile.WriteTObject(h_phi_j)
outfile.WriteTObject(h_phi_Hb)
outfile.WriteTObject(h_phi_tb)
outfile.WriteTObject(h_phi_W)
outfile.WriteTObject(h_phi_tWl)
outfile.WriteTObject(h_phi_tWnu)

#outfile.WriteTObject(h_ratio)

