const int nh = 82;
std::string hname[nh] =
{
   "h_pt_t",
   "h_pt_tb",
   "h_pt_tWl",
   "h_pt_tWnu",
   "h_pt_W",
   "h_pt_H",
   "h_pt_Hb",
   "h_pt_j",

   "h_eta_t",
   "h_eta_tb",
   "h_eta_tWl",
   "h_eta_tWnu",
   "h_eta_W",
   "h_eta_H",
   "h_eta_Hb",
   "h_eta_j",

   "h_phi_t",
   "h_phi_tb",
   "h_phi_tWl",
   "h_phi_tWnu",
   "h_phi_W",
   "h_phi_H",
   "h_phi_Hb",
   "h_phi_j",
   
   "h_dr_t_H",
   "h_dr_t_j",
   "h_dr_t_Hb",
   "h_dr_t_tb",
   "h_dr_t_W",
   "h_dr_t_tWl",
   "h_dr_t_tWnu",
   "h_dr_H_j",
   "h_dr_H_Hb",
   "h_dr_H_tb",
   "h_dr_H_W",
   "h_dr_H_tWl",
   "h_dr_H_tWnu",
   "h_dr_W_tWl",
   "h_dr_W_tWnu",
   "h_dr_j_Hb",
   "h_dr_j_tb",
   "h_dr_j_W",
   "h_dr_j_tWl",
   "h_dr_j_tWnu",
   "h_dr_Hb_tb",
   "h_dr_Hb_W",
   "h_dr_Hb_tWl",
   "h_dr_Hb_tWnu",
   "h_dr_tb_W",
   "h_dr_tb_tWl",
   "h_dr_tb_tWnu",
   "h_dr_tWl_tWnu",
   "h_dr_Hb1_Hb2",
   
   "h_costheta_t_H",
   "h_costheta_t_j",
   "h_costheta_t_Hb",
   "h_costheta_t_tb",
   "h_costheta_t_W",
   "h_costheta_t_tWl",
   "h_costheta_t_tWnu",
   "h_costheta_H_j",
   "h_costheta_H_Hb",
   "h_costheta_H_tb",
   "h_costheta_H_W",
   "h_costheta_H_tWl",
   "h_costheta_H_tWnu",
   "h_costheta_W_tWl",
   "h_costheta_W_tWnu",
   "h_costheta_j_Hb",
   "h_costheta_j_tb",
   "h_costheta_j_W",
   "h_costheta_j_tWl",
   "h_costheta_j_tWnu",
   "h_costheta_Hb_tb",
   "h_costheta_Hb_W",
   "h_costheta_Hb_tWl",
   "h_costheta_Hb_tWnu",
   "h_costheta_tb_W",
   "h_costheta_tb_tWl",
   "h_costheta_tb_tWnu",
   "h_costheta_tWl_tWnu",
   "h_costheta_Hb1_Hb2"   
};

std::string xtit[nh] =
{
   "P_{T} (t) [GeV]",
   "P_{T} (b_{t}) [GeV]",
   "P_{T} (l) [GeV]",
   "P_{T} (#nu) [GeV]",
   "P_{T} (W) [GeV]",
   "P_{T} (H) [GeV]",
   "P_{T} (b_{H}) [GeV]",
   "P_{T} (q) [GeV]",

   "#eta (t)",
   "#eta (b_{t})",
   "#eta (l)",
   "#eta (#nu)",
   "#eta (W)",
   "#eta (H)",
   "#eta (b_{H})",
   "#eta (q)",

   "#varphi (t)",
   "#varphi (b_{t})",
   "#varphi (l)",
   "#varphi (#nu)",
   "#varphi (W)",
   "#varphi (H)",
   "#varphi (b_{H})",
   "#varphi (q)",
   
   "#Delta R (t,H)",
   "#Delta R (t,q)",
   "#Delta R (t,b_{H})",
   "#Delta R (t,b_{t})",
   "#Delta R (t,W)",
   "#Delta R (t,l)",
   "#Delta R (t,#nu)",
   "#Delta R (H,q)",
   "#Delta R (H,b_{H})",
   "#Delta R (H,b_{t})",
   "#Delta R (H,W)",
   "#Delta R (H,l)",
   "#Delta R (H,#nu)",
   "#Delta R (W,l)",
   "#Delta R (W,#nu)",
   "#Delta R (q,b_{H})",
   "#Delta R (q,b_{t})",
   "#Delta R (q,W)",
   "#Delta R (q,l)",
   "#Delta R (q,#nu)",
   "#Delta R (b_{H},b_{t})",
   "#Delta R (b_{H},W)",
   "#Delta R (b_{H},l)",
   "#Delta R (b_{H},#nu)",
   "#Delta R (b_{t},W)",
   "#Delta R (b_{t},l)",
   "#Delta R (b_{t},#nu)",
   "#Delta R (l,#nu)",
   "#Delta R (b1_{H},b2_{H})",
   
   "cos#theta (t,H)",
   "cos#theta (t,q)",
   "cos#theta (t,b_{H})",
   "cos#theta (t,b_{t})",
   "cos#theta (t,W)",
   "cos#theta (t,l)",
   "cos#theta (t,#nu)",
   "cos#theta (H,q)",
   "cos#theta (H,b_{H})",
   "cos#theta (H,b_{t})",
   "cos#theta (H,W)",
   "cos#theta (H,l)",
   "cos#theta (H,#nu)",
   "cos#theta (W,l)",
   "cos#theta (W,#nu)",
   "cos#theta (q,b_{H})",
   "cos#theta (q,b_{t})",
   "cos#theta (q,W)",
   "cos#theta (q,l)",
   "cos#theta (q,#nu)",
   "cos#theta (b_{H},b_{t})",
   "cos#theta (b_{H},W)",
   "cos#theta (b_{H},l)",
   "cos#theta (b_{H},#nu)",
   "cos#theta (b_{t},W)",
   "cos#theta (b_{t},l)",
   "cos#theta (b_{t},#nu)",
   "cos#theta (l,#nu)",
   "cos#theta (b1_{H},b2_{H})",
};

// samples
const int nf = 2;
std::string fname[nf] =
{
   "TTtoHToBB-1L-Kappa-hut_CMS",
   "TTtoHToBB-1L-Kappa-hct_CMS"
};

std::string glab[nf] =
{
   "Hut (ttbar)",
   "Hct (ttbar)"
};
