// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Sat Oct  8 09:53:02 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_12/src/tHFCNC/NtupleAnalyzer/test/MVA
Training events: 1067411
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB                                             'D'    [15.8769626617,500]
TopHadMass_TOPTOPLEPHAD       TopHadMass_TOPTOPLEPHAD       TopHadMass_TOPTOPLEPHAD       TopHadMass_TOPTOPLEPHAD                                         'D'    [35.673374176,1000]
MVA_TOPHLEPBB                 MVA_TOPHLEPBB                 MVA_TOPHLEPBB                 MVA_TOPHLEPBB                                                   'D'    [-0.71241736412,0.754667162895]
MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD                                                'D'    [-0.874452292919,0.699228048325]
LepCharge                     LepCharge                     LepCharge                     LepCharge                                                       'I'    [-1,1]
HiggsEta_TOPHLEPBB            HiggsEta_TOPHLEPBB            HiggsEta_TOPHLEPBB            HiggsEta_TOPHLEPBB                                              'D'    [-8.47341442108,8.01798439026]
TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB                                            'D'    [82.0882034302,500]
TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD                                         'D'    [42.7401733398,500]
TopLepPt_TOPHLEPBB            TopLepPt_TOPHLEPBB            TopLepPt_TOPHLEPBB            TopLepPt_TOPHLEPBB                                              'D'    [0.152514234185,1000]
TopLepEta_TOPHLEPBB           TopLepEta_TOPHLEPBB           TopLepEta_TOPHLEPBB           TopLepEta_TOPHLEPBB                                             'D'    [-7.8106880188,7.56094884872]
HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB                                      'D'    [0.34280321002,5.61574935913]
TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB                                         'D'    [0.00465523079038,10.5010242462]
TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD                                     'D'    [0.0133803077042,11.7588825226]
HiggsBJet1CSVv2_TOPHLEPBB     HiggsBJet1CSVv2_TOPHLEPBB     HiggsBJet1CSVv2_TOPHLEPBB     HiggsBJet1CSVv2_TOPHLEPBB                                       'D'    [0.800000071526,1]
HiggsBJet2CSVv2_TOPHLEPBB     HiggsBJet2CSVv2_TOPHLEPBB     HiggsBJet2CSVv2_TOPHLEPBB     HiggsBJet2CSVv2_TOPHLEPBB                                       'D'    [-10,0.999436318874]
TopLepBJetCSVv2_TOPHLEPBB     TopLepBJetCSVv2_TOPHLEPBB     TopLepBJetCSVv2_TOPHLEPBB     TopLepBJetCSVv2_TOPHLEPBB                                       'D'    [-10,1]
TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD                                    'D'    [0.800001978874,1]
TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD                                    'D'    [0.800000071526,1]
TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD                                       'D'    [-10,0.799998044968]
TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD                                       'D'    [-10,0.796201467514]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsMass_TOPHLEPBB", "TopHadMass_TOPTOPLEPHAD", "MVA_TOPHLEPBB", "MVA_TOPTOPLEPHAD", "LepCharge", "HiggsEta_TOPHLEPBB", "TopLepMass_TOPHLEPBB", "TopLepMass_TOPTOPLEPHAD", "TopLepPt_TOPHLEPBB", "TopLepEta_TOPHLEPBB", "HiggsBJet1HiggsBJet2Dr_TOPHLEPBB", "TopLepHiggsDr_TOPHLEPBB", "TopLepTopHadDr_TOPTOPLEPHAD", "HiggsBJet1CSVv2_TOPHLEPBB", "HiggsBJet2CSVv2_TOPHLEPBB", "TopLepBJetCSVv2_TOPHLEPBB", "TopLepBJetCSVv2_TOPTOPLEPHAD", "TopHadBJetCSVv2_TOPTOPLEPHAD", "TopHadWNonBJet1CSVv2_TOPTOPLEPHAD", "TopHadWNonBJet2CSVv2_TOPTOPLEPHAD" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'I';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';
      fType[16] = 'D';
      fType[17] = 'D';
      fType[18] = 'D';
      fType[19] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.508604986653567);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 369.516, 0, 1, 0.802596,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361704,-99) , 
3, 0.197986, 1, 0, 0.446338,-99) , 
1, 221.166, 0, 0, 0.633088,-99) , 
NN(
0, 
0, 
-1, 219.355, 0, -1, 0.213489,-99) , 
4, 0, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.341892);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470469,-99) , 
4, 0, 0, 0, 0.605609,-99) , 
8, 238.344, 0, 0, 0.687242,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44062,-99) , 
8, 238.211, 0, 0, 0.480694,-99) , 
NN(
0, 
0, 
-1, 0.167592, 1, -1, 0.222999,-99) , 
4, 0, 0, 0, 0.391271,-99) , 
1, 265.275, 0, 0, 0.502152,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.272121);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 510.184, 0, 1, 0.698597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451912,-99) , 
14, 0.475653, 0, 0, 0.533021,-99) , 
NN(
0, 
0, 
-1, 0.150051, 1, -1, 0.317124,-99) , 
4, 0, 0, 0, 0.463292,-99) , 
1, 357.116, 0, 0, 0.5208,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.211794);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.736825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476675,-99) , 
13, 0.961906, 0, 0, 0.555909,-99) , 
8, 285.948, 0, 0, 0.600129,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452672,-99) , 
18, 0.285712, 0, 0, 0.512665,-99) , 
NN(
0, 
0, 
-1, 0.191321, 1, -1, 0.316601,-99) , 
4, 0, 0, 0, 0.448392,-99) , 
1, 219.355, 0, 0, 0.518839,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.151957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.689809,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457564,-99) , 
1, 188.739, 0, 0, 0.506503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325863,-99) , 
19, -9.4859, 0, 0, 0.490248,-99) , 
1, 494.877, 0, 0, 0.515326,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.130634);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673152,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485071,-99) , 
8, 158.856, 0, 0, 0.523857,-99) , 
NN(
0, 
0, 
-1, 0.170982, 1, -1, 0.422434,-99) , 
4, 0, 0, 0, 0.492696,-99) , 
8, 333.435, 0, 0, 0.512713,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.109331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648465,-99) , 
NN(
NN(
0, 
0, 
-1, 221.177, 0, 1, 0.530721,-99) , 
NN(
0, 
0, 
-1, 0, 0, -1, 0.433755,-99) , 
17, 0.92381, 0, 0, 0.501683,-99) , 
1, 494.877, 0, 0, 0.519621,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.13049);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4888,-99) , 
5, -1.28228, 1, 0, 0.512637,-99) , 
8, 285.823, 0, 0, 0.534846,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421918,-99) , 
14, 0.475636, 0, 0, 0.502297,-99) , 
NN(
0, 
0, 
-1, 0.475654, 0, -1, 0.340929,-99) , 
3, 0.170982, 1, 0, 0.440263,-99) , 
4, 0, 0, 0, 0.506711,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.11167);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498622,-99) , 
11, 2.50729, 1, 0, 0.522732,-99) , 
5, 1.71462, 0, 0, 0.54294,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426512,-99) , 
18, 0.28571, 0, 0, 0.489084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346302,-99) , 
3, 0.245263, 1, 0, 0.448919,-99) , 
4, 0, 0, 0, 0.515112,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.113284);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 404.421, 0, 1, 0.551217,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441967,-99) , 
13, 0.990476, 0, 0, 0.478879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345678,-99) , 
3, 0.319545, 1, 0, 0.453801,-99) , 
4, 0, 0, 0, 0.522468,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.082558);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 220.521, 0, 1, 0.569204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383654,-99) , 
3, 0.399479, 1, 0, 0.490977,-99) , 
19, 0.172178, 0, 0, 0.517955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372119,-99) , 
19, -9.4859, 0, 0, 0.505539,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0948632);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586477,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489275,-99) , 
7, 199.022, 0, 0, 0.515458,-99) , 
NN(
0, 
0, 
-1, 195.16, 0, -1, 0.448619,-99) , 
16, 0.980953, 0, 0, 0.477951,-99) , 
1, 494.877, 0, 0, 0.490852,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0831117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58727,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485573,-99) , 
10, 1.62143, 1, 0, 0.509845,-99) , 
NN(
0, 
0, 
-1, 2.96124, 1, -1, 0.440755,-99) , 
16, 0.914287, 0, 0, 0.492124,-99) , 
19, 0.282097, 0, 0, 0.503037,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0993761);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450985,-99) , 
0, 85.0374, 0, 0, 0.528259,-99) , 
NN(
0, 
0, 
-1, 0.150659, 0, -1, 0.426673,-99) , 
14, 0.189241, 0, 0, 0.517047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412945,-99) , 
19, -9.4859, 0, 0, 0.508308,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0812126);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572989,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481705,-99) , 
5, 0.965397, 0, 0, 0.505975,-99) , 
NN(
0, 
0, 
-1, 0.170982, 1, -1, 0.449181,-99) , 
4, 0, 0, 0, 0.489149,-99) , 
11, 2.00396, 1, 0, 0.498628,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0751843);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582664,-99) , 
NN(
NN(
0, 
0, 
-1, 199.729, 0, 1, 0.534297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465848,-99) , 
5, -1.28228, 1, 0, 0.479252,-99) , 
17, 0.990476, 0, 0, 0.496901,-99) , 
8, 333.435, 0, 0, 0.505858,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0735927);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 109.281, 0, 1, 0.556775,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488909,-99) , 
4, 0, 0, 0, 0.530467,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44866,-99) , 
11, 2.9716, 1, 0, 0.473671,-99) , 
16, 0.990476, 0, 0, 0.492461,-99) , 
7, 238.709, 0, 0, 0.504502,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0653867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448095,-99) , 
17, 0.847619, 0, 0, 0.507291,-99) , 
7, 260.483, 0, 0, 0.516084,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455974,-99) , 
0, 108.091, 0, 0, 0.492719,-99) , 
NN(
0, 
0, 
-1, 143.009, 0, -1, 0.442079,-99) , 
10, 1.82453, 1, 0, 0.466299,-99) , 
16, 0.933334, 0, 0, 0.499995,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0683542);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496229,-99) , 
10, 2.32721, 1, 0, 0.544013,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4774,-99) , 
10, 2.38263, 1, 0, 0.537958,-99) , 
NN(
0, 
0, 
-1, 0.400527, 1, -1, 0.47414,-99) , 
5, -1.66744, 1, 0, 0.485103,-99) , 
5, 1.73555, 0, 0, 0.49369,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0722057);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563168,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477772,-99) , 
0, 108.091, 0, 0, 0.531709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473565,-99) , 
16, 0.990476, 0, 0, 0.487638,-99) , 
10, 1.34717, 1, 0, 0.499338,-99) , 
8, 333.435, 0, 0, 0.505963,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0620076);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475654, 0, 1, 0.556548,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452852,-99) , 
15, 0.47619, 0, 0, 0.500922,-99) , 
2, 0.265639, 0, 0, 0.515628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451162,-99) , 
3, 0.399479, 1, 0, 0.509363,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.071264);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472277,-99) , 
3, 0.328654, 1, 0, 0.524056,-99) , 
NN(
0, 
0, 
-1, 2.44466, 1, -1, 0.471489,-99) , 
8, 95.3761, 0, 0, 0.510369,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40716,-99) , 
14, 0.475398, 1, 0, 0.459194,-99) , 
0, 154.198, 1, 0, 0.500859,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0586628);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.32369, 1, 1, 0.524211,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454555,-99) , 
3, 0.184315, 0, 0, 0.477833,-99) , 
0, 101.504, 0, 0, 0.50731,-99) , 
NN(
0, 
0, 
-1, 252.999, 0, -1, 0.457466,-99) , 
0, 154.198, 1, 0, 0.498053,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0745909);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472027,-99) , 
11, 3.45647, 1, 0, 0.504264,-99) , 
10, 1.33501, 1, 0, 0.519634,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478089,-99) , 
10, 1.88455, 1, 0, 0.508573,-99) , 
NN(
0, 
0, 
-1, 195.16, 0, -1, 0.457235,-99) , 
5, -0.844741, 1, 0, 0.481377,-99) , 
5, 0.950242, 0, 0, 0.49381,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0565897);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475654, 0, 1, 0.527524,-99) , 
NN(
0, 
0, 
-1, 0.372952, 0, -1, 0.473128,-99) , 
17, 0.904724, 0, 0, 0.514246,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480158,-99) , 
18, 0.653059, 0, 0, 0.492084,-99) , 
NN(
0, 
0, 
-1, 0, 0, -1, 0.462425,-99) , 
18, 0.285712, 0, 0, 0.479001,-99) , 
7, 173.386, 0, 0, 0.498469,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0572541);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.876088, 0, 1, 0.528684,-99) , 
NN(
0, 
0, 
-1, 0.160146, 0, -1, 0.476779,-99) , 
19, 0.13547, 0, 0, 0.504238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444131,-99) , 
19, -9.4859, 0, 0, 0.49922,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0535149);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540911,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478783,-99) , 
12, 2.72459, 1, 0, 0.487167,-99) , 
1, 145.006, 1, 0, 0.49423,-99) , 
1, 494.877, 0, 0, 0.499652,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0298518);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497333,-99) , 
5, 1.73555, 0, 0, 0.502954,-99) , 
7, 304.031, 0, 0, 0.508207,-99) , 
NN(
0, 
0, 
-1, 0.971113, 0, -1, 0.464238,-99) , 
16, 0.857144, 0, 0, 0.503353,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0290394);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56293,-99) , 
NN(
NN(
0, 
0, 
-1, 304.031, 0, 1, 0.508844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467663,-99) , 
16, 0.857144, 0, 0, 0.504308,-99) , 
5, -2.19098, 1, 0, 0.507817,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0428298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555772,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493269,-99) , 
14, 0.475654, 0, 0, 0.512914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480531,-99) , 
5, 1.58026, 0, 0, 0.487914,-99) , 
17, 0.980952, 0, 0, 0.498647,-99) , 
5, -2.19098, 1, 0, 0.502062,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0723459);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.289782, 1, 1, 0.542885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479871,-99) , 
8, 238.344, 0, 0, 0.49742,-99) , 
3, 0.174668, 0, 0, 0.513253,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461679,-99) , 
2, 0.135874, 0, 0, 0.509589,-99) , 
NN(
0, 
0, 
-1, 0.173936, 1, -1, 0.454181,-99) , 
14, 0.475654, 0, 0, 0.484094,-99) , 
4, 0, 0, 0, 0.50462,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0493708);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492177,-99) , 
8, 238.226, 1, 0, 0.531677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478194,-99) , 
2, -0.0147024, 0, 0, 0.501657,-99) , 
1, 269.961, 1, 0, 0.519465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47651,-99) , 
3, 0.0247936, 1, 0, 0.488295,-99) , 
5, -1.53833, 1, 0, 0.495498,-99) , 
6, 181.591, 0, 0, 0.506149,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0330217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465886,-99) , 
11, 4.00327, 1, 0, 0.503717,-99) , 
14, 0.954425, 0, 0, 0.508187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465745,-99) , 
19, -9.4859, 0, 0, 0.504652,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0345399);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495776,-99) , 
7, 177.524, 0, 0, 0.513767,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486641,-99) , 
9, -1.71447, 1, 0, 0.491992,-99) , 
6, 181.591, 0, 0, 0.501692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455241,-99) , 
12, 4.48786, 1, 0, 0.499259,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0282451);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499646,-99) , 
10, 1.37178, 1, 0, 0.51248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456963,-99) , 
1, 265.275, 1, 0, 0.491117,-99) , 
0, 108.091, 0, 0, 0.504455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459302,-99) , 
17, 0.828571, 0, 0, 0.502058,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0385824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494252,-99) , 
0, 126.753, 1, 0, 0.503755,-99) , 
10, 1.37178, 1, 0, 0.514196,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474659,-99) , 
4, 0, 0, 0, 0.494858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443812,-99) , 
15, 0.47619, 0, 0, 0.486555,-99) , 
0, 108.091, 0, 0, 0.503808,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0330371);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37178, 1, 1, 0.514776,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485381,-99) , 
11, 2.47711, 1, 0, 0.491022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453356,-99) , 
15, 0.47619, 0, 0, 0.484904,-99) , 
0, 108.091, 0, 0, 0.503549,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0285422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49522,-99) , 
17, 0.997279, 0, 0, 0.503219,-99) , 
7, 221.177, 0, 0, 0.511182,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479745,-99) , 
1, 173.434, 0, 0, 0.496814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463409,-99) , 
16, 0.866668, 0, 0, 0.492368,-99) , 
17, 0.980952, 0, 0, 0.500406,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0324549);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496845,-99) , 
5, 1.2868, 0, 0, 0.506258,-99) , 
5, -1.40567, 1, 0, 0.511678,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491083,-99) , 
8, 204.201, 0, 0, 0.497472,-99) , 
NN(
0, 
0, 
-1, 1.60127, 0, -1, 0.471933,-99) , 
8, 238.211, 1, 0, 0.49088,-99) , 
17, 0.980952, 0, 0, 0.499765,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0321285);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463162,-99) , 
0, 147.611, 1, 0, 0.503187,-99) , 
0, 246.412, 0, 0, 0.506068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46715,-99) , 
12, 4.48786, 1, 0, 0.504032,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0301959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491774,-99) , 
1, 145.006, 1, 0, 0.497266,-99) , 
1, 494.877, 0, 0, 0.500748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462441,-99) , 
17, 0.828571, 0, 0, 0.498713,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0374276);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545449,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474565,-99) , 
15, 0.47619, 0, 0, 0.502173,-99) , 
10, 1.37178, 1, 0, 0.509953,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487167,-99) , 
1, 177.807, 0, 0, 0.501036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465107,-99) , 
1, 265.275, 1, 0, 0.49235,-99) , 
0, 108.091, 0, 0, 0.503337,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0385651);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492194,-99) , 
3, 0.195639, 0, 0, 0.503389,-99) , 
7, 202.169, 0, 0, 0.514205,-99) , 
NN(
NN(
0, 
0, 
-1, 0.971431, 1, 1, 0.529509,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483781,-99) , 
5, -1.66744, 1, 0, 0.488843,-99) , 
5, 1.73555, 0, 0, 0.495515,-99) , 
9, -1.22284, 1, 0, 0.500676,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0149316);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499381,-99) , 
11, 1.98262, 1, 0, 0.50212,-99) , 
19, 0.282097, 0, 0, 0.505214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469815,-99) , 
17, 0.828571, 0, 0, 0.503334,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0393156);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534739,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477243,-99) , 
8, 238.23, 1, 0, 0.505931,-99) , 
1, 448.956, 0, 0, 0.509903,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485464,-99) , 
14, 0.385484, 1, 0, 0.504418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471006,-99) , 
1, 266.73, 1, 0, 0.492077,-99) , 
17, 0.904762, 0, 0, 0.50558,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0324568);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526035,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496879,-99) , 
0, 108.091, 0, 0, 0.517705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48621,-99) , 
3, 0.245533, 0, 0, 0.49278,-99) , 
10, 1.34717, 1, 0, 0.499301,-99) , 
8, 333.435, 0, 0, 0.502022,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0311621);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.12383, 1, 1, 0.532008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489812,-99) , 
8, 143.013, 0, 0, 0.504811,-99) , 
9, -1.65707, 1, 0, 0.509477,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482885,-99) , 
12, 4.13412, 1, 0, 0.501327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474195,-99) , 
0, 132.209, 1, 0, 0.492314,-99) , 
12, 3.36924, 1, 0, 0.50421,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0242782);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493603,-99) , 
0, 85.0374, 0, 0, 0.52693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495983,-99) , 
0, 188.779, 0, 0, 0.499871,-99) , 
10, 1.09608, 1, 0, 0.504594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478324,-99) , 
3, 0.399479, 1, 0, 0.502042,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0533999);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 201.804, 0, 1, 0.522572,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47907,-99) , 
8, 136.186, 0, 0, 0.494248,-99) , 
10, 2.07916, 1, 0, 0.509674,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462575,-99) , 
11, 2.88812, 1, 0, 0.509286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455872,-99) , 
11, 3.188, 1, 0, 0.492828,-99) , 
8, 238.211, 1, 0, 0.505528,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0134431);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532991,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533609,-99) , 
NN(
0, 
0, 
-1, 0.399479, 1, -1, 0.49718,-99) , 
5, 2.18431, 0, 0, 0.49983,-99) , 
5, -2.19098, 1, 0, 0.501803,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0269893);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472974,-99) , 
18, 0.160146, 0, 0, 0.502087,-99) , 
14, 0.954425, 0, 0, 0.506377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48145,-99) , 
19, -9.4859, 0, 0, 0.504304,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0183178);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496541,-99) , 
0, 200.305, 0, 0, 0.4995,-99) , 
7, 304.031, 0, 0, 0.502366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478412,-99) , 
16, 0.847621, 0, 0, 0.500203,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0448238);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594783,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48544,-99) , 
1, 184.055, 0, 0, 0.500938,-99) , 
1, 134.074, 1, 0, 0.508663,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480337,-99) , 
12, 2.89527, 0, 0, 0.502597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47336,-99) , 
12, 3.37438, 1, 0, 0.493335,-99) , 
1, 265.275, 1, 0, 0.503146,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0421025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476398,-99) , 
2, 0.33827, 1, 0, 0.502826,-99) , 
1, 134.074, 1, 0, 0.509482,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470795,-99) , 
0, 104.62, 0, 0, 0.506813,-99) , 
NN(
0, 
0, 
-1, 190.974, 0, -1, 0.481539,-99) , 
0, 132.001, 1, 0, 0.494265,-99) , 
1, 265.275, 1, 0, 0.504003,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0342732);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527116,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478425,-99) , 
4, 0, 0, 0, 0.513787,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487907,-99) , 
9, -1.48302, 1, 0, 0.494464,-99) , 
5, 1.21204, 0, 0, 0.499876,-99) , 
5, -2.19098, 1, 0, 0.501496,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0127095);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499836,-99) , 
0, 200.305, 0, 0, 0.502698,-99) , 
7, 304.031, 0, 0, 0.505032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482975,-99) , 
16, 0.847621, 0, 0, 0.503042,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0159388);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.28057, 0, 1, 0.507186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475039,-99) , 
13, 0.942594, 1, 0, 0.488131,-99) , 
16, 0.857144, 0, 0, 0.505084,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.014252);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497821,-99) , 
10, 1.09608, 1, 0, 0.500805,-99) , 
8, 333.435, 0, 0, 0.502944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476845,-99) , 
17, 0.828571, 0, 0, 0.50156,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0209912);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516463,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481758,-99) , 
8, 238.211, 1, 0, 0.499644,-99) , 
11, 1.98262, 1, 0, 0.501472,-99) , 
19, 0.282097, 0, 0, 0.503459,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0192256);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516966,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492539,-99) , 
0, 108.091, 0, 0, 0.508736,-99) , 
NN(
0, 
0, 
-1, 2.50379, 0, -1, 0.494681,-99) , 
10, 1.34717, 1, 0, 0.498347,-99) , 
8, 333.435, 0, 0, 0.500235,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0107873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.282097, 0, 1, 0.504591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480284,-99) , 
17, 0.828571, 0, 0, 0.503302,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0240898);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522079,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494353,-99) , 
8, 190.694, 0, 0, 0.502199,-99) , 
7, 221.177, 0, 0, 0.506822,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486789,-99) , 
13, 0.961905, 1, 0, 0.499688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480317,-99) , 
8, 285.823, 1, 0, 0.496471,-99) , 
17, 0.980952, 0, 0, 0.500892,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0195531);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.137185, 0, 1, 0.519917,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495391,-99) , 
5, -0.620367, 1, 0, 0.501147,-99) , 
12, 2.93449, 1, 0, 0.50647,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520015,-99) , 
NN(
0, 
0, 
-1, 0.866668, 0, -1, 0.492512,-99) , 
5, 1.96148, 0, 0, 0.495454,-99) , 
17, 0.971429, 0, 0, 0.500888,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0268399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492867,-99) , 
3, 0.181955, 0, 0, 0.503873,-99) , 
2, 0.333276, 0, 0, 0.508777,-99) , 
NN(
NN(
0, 
0, 
-1, 1.95993, 0, 1, 0.510429,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485789,-99) , 
9, -1.26115, 1, 0, 0.491842,-99) , 
5, 0.950242, 0, 0, 0.497904,-99) , 
16, 0.980953, 0, 0, 0.502663,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0242021);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.63596, 1, 1, 0.516327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487648,-99) , 
3, 0.185855, 0, 0, 0.498035,-99) , 
0, 108.689, 0, 0, 0.509297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488174,-99) , 
4, 0, 0, 0, 0.50191,-99) , 
NN(
0, 
0, 
-1, 0.10802, 1, -1, 0.486968,-99) , 
6, 161.69, 0, 0, 0.4974,-99) , 
16, 0.980953, 0, 0, 0.502606,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0232666);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.263563, 0, 1, 0.507897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471869,-99) , 
3, 0.213925, 0, 0, 0.496547,-99) , 
3, 0.0997308, 1, 0, 0.502714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485406,-99) , 
16, 0.847621, 0, 0, 0.501152,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0210055);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49395,-99) , 
5, 1.97539, 0, 0, 0.496834,-99) , 
5, -1.86621, 1, 0, 0.499732,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468623,-99) , 
8, 95.3761, 1, 0, 0.483898,-99) , 
11, 4.00327, 1, 0, 0.498007,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.022555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473594,-99) , 
0, 138.828, 1, 0, 0.500563,-99) , 
0, 200.305, 0, 0, 0.503102,-99) , 
NN(
0, 
0, 
-1, 2.60745, 1, -1, 0.484241,-99) , 
11, 4.00327, 1, 0, 0.501047,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0128145);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511364,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512117,-99) , 
NN(
0, 
0, 
-1, 92.7217, 0, -1, 0.494848,-99) , 
0, 246.412, 0, 0, 0.496383,-99) , 
19, 0.282097, 0, 0, 0.498088,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0265725);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487735,-99) , 
14, 0.475654, 0, 0, 0.523841,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488978,-99) , 
14, 0.475653, 1, 0, 0.497009,-99) , 
2, 0.3355, 0, 0, 0.501495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486654,-99) , 
3, 0.399479, 1, 0, 0.500058,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0205555);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513244,-99) , 
NN(
NN(
0, 
0, 
-1, 260.483, 0, 1, 0.504145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467886,-99) , 
10, 2.12072, 0, 0, 0.485073,-99) , 
8, 238.211, 1, 0, 0.499482,-99) , 
11, 2.00396, 1, 0, 0.501015,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0210701);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495018,-99) , 
1, 144.81, 1, 0, 0.498557,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460756,-99) , 
14, 0.475639, 0, 0, 0.48541,-99) , 
1, 358.607, 1, 0, 0.495696,-99) , 
10, 0.844989, 1, 0, 0.497358,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0193312);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512164,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494161,-99) , 
14, 0.475654, 0, 0, 0.502152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474686,-99) , 
2, 0.0453957, 1, 0, 0.486145,-99) , 
10, 2.60264, 1, 0, 0.498243,-99) , 
8, 333.435, 0, 0, 0.499649,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0264398);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537101,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49073,-99) , 
1, 214.252, 0, 0, 0.497555,-99) , 
1, 142.82, 1, 0, 0.501565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452174,-99) , 
4, 0, 0, 0, 0.490282,-99) , 
1, 357.116, 1, 0, 0.498994,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0251414);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561067,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490961,-99) , 
1, 177.808, 0, 0, 0.500027,-99) , 
1, 134.074, 1, 0, 0.505014,-99) , 
NN(
0, 
0, 
-1, 3.00921, 1, -1, 0.488723,-99) , 
1, 265.275, 1, 0, 0.499151,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0452484);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.285712, 1, 1, 0.524393,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435011,-99) , 
14, 0.475654, 0, 0, 0.475821,-99) , 
4, 0, 0, 0, 0.509384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52731,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481462,-99) , 
4, 0, 1, 0, 0.490565,-99) , 
2, 0.334155, 0, 0, 0.496517,-99) , 
3, 0.174668, 0, 0, 0.501075,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0257018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512282,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496944,-99) , 
10, 1.81221, 1, 0, 0.506735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484219,-99) , 
5, -0.965313, 1, 0, 0.491983,-99) , 
8, 142.988, 1, 0, 0.498128,-99) , 
11, 2.00396, 1, 0, 0.499704,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0110178);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513799,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498815,-99) , 
8, 333.435, 0, 0, 0.50119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482335,-99) , 
6, 300.994, 1, 0, 0.49957,-99) , 
9, 1.70509, 0, 0, 0.501028,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0133983);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497942,-99) , 
3, 0.188421, 0, 0, 0.502347,-99) , 
7, 325.806, 0, 0, 0.503791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484743,-99) , 
17, 0.828571, 0, 0, 0.502781,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.029509);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488458,-99) , 
14, 0.475654, 0, 0, 0.519145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496841,-99) , 
0, 183.838, 0, 0, 0.500768,-99) , 
7, 216.934, 0, 0, 0.505305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459706,-99) , 
14, 0.475639, 1, 0, 0.493531,-99) , 
0, 85.0374, 0, 0, 0.50353,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0425467);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498112,-99) , 
14, 0.475654, 0, 0, 0.514028,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457698,-99) , 
14, 0.475398, 1, 0, 0.493731,-99) , 
0, 144.318, 1, 0, 0.508596,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467043,-99) , 
14, 0.475639, 1, 0, 0.493447,-99) , 
0, 85.0374, 0, 0, 0.506313,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0378259);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47714,-99) , 
0, 93.5062, 0, 0, 0.512513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468276,-99) , 
14, 0.475398, 1, 0, 0.493072,-99) , 
0, 144.318, 1, 0, 0.507312,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477142,-99) , 
3, 0.184315, 0, 0, 0.493325,-99) , 
0, 85.0374, 0, 0, 0.505205,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0166323);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487372,-99) , 
12, 2.41145, 0, 0, 0.497015,-99) , 
8, 143.137, 0, 0, 0.508852,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497499,-99) , 
6, 241.293, 0, 0, 0.500738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486184,-99) , 
8, 285.823, 1, 0, 0.498399,-99) , 
12, 2.80993, 1, 0, 0.500635,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0202695);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 199.022, 1, 1, 0.514723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485022,-99) , 
17, 0.942859, 0, 0, 0.499973,-99) , 
16, 0.995465, 0, 0, 0.506963,-99) , 
NN(
NN(
0, 
0, 
-1, 1.95993, 0, 1, 0.507755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484013,-99) , 
10, 1.59203, 0, 0, 0.495225,-99) , 
5, 0.950242, 0, 0, 0.499312,-99) , 
16, 0.980953, 0, 0, 0.50266,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0179347);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.140973, 1, 1, 0.513957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490735,-99) , 
7, 201.306, 1, 0, 0.507041,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486578,-99) , 
14, 0.475654, 0, 0, 0.507243,-99) , 
NN(
0, 
0, 
-1, 0.47619, 0, -1, 0.494982,-99) , 
7, 216.934, 0, 0, 0.498087,-99) , 
13, 0.914286, 1, 0, 0.500016,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0297033);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496391,-99) , 
10, 1.83855, 0, 0, 0.510994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472889,-99) , 
14, 0.700135, 0, 0, 0.496147,-99) , 
14, 0.475654, 1, 0, 0.503314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489465,-99) , 
3, -0.274955, 0, 0, 0.50199,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0325122);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466723,-99) , 
8, 238.412, 1, 0, 0.496989,-99) , 
11, 2.78445, 1, 0, 0.50929,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48698,-99) , 
4, 0, 0, 0, 0.507172,-99) , 
NN(
0, 
0, 
-1, 0.675193, 0, -1, 0.490656,-99) , 
14, 0.475654, 1, 0, 0.498472,-99) , 
10, 1.34717, 1, 0, 0.501461,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0218199);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.913692, 0, 1, 0.509621,-99) , 
NN(
0, 
0, 
-1, 227.7, 0, -1, 0.485029,-99) , 
19, 0.098763, 0, 0, 0.503597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489348,-99) , 
19, -9.4859, 0, 0, 0.502414,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0306285);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491288,-99) , 
8, 143.289, 0, 0, 0.516928,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456418,-99) , 
8, 285.823, 1, 0, 0.496962,-99) , 
11, 2.66876, 1, 0, 0.502479,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481165,-99) , 
5, 1.73555, 1, 0, 0.501239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466927,-99) , 
11, 2.50661, 0, 0, 0.493583,-99) , 
10, 2.60264, 1, 0, 0.500316,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0285532);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509369,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478317,-99) , 
3, 0.170982, 1, 0, 0.50414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48431,-99) , 
3, 0.174668, 0, 0, 0.49212,-99) , 
4, 0, 1, 0, 0.495779,-99) , 
8, 333.435, 0, 0, 0.497147,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0289163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530048,-99) , 
NN(
0, 
0, 
-1, 1.90876, 0, -1, 0.480562,-99) , 
8, 143.289, 0, 0, 0.504459,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49351,-99) , 
5, -0.767767, 0, 0, 0.506345,-99) , 
NN(
0, 
0, 
-1, 0.324542, 1, -1, 0.487586,-99) , 
8, 142.988, 1, 0, 0.495225,-99) , 
11, 2.50379, 1, 0, 0.497229,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0113763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 200.305, 0, 1, 0.503177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48068,-99) , 
6, 300.994, 1, 0, 0.5013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47424,-99) , 
6, 184.681, 0, 0, 0.487772,-99) , 
11, 4.00327, 1, 0, 0.499824,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.014653);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498393,-99) , 
2, 0.334155, 0, 0, 0.502567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47843,-99) , 
3, 0.213925, 0, 0, 0.493912,-99) , 
3, 0.0997308, 1, 0, 0.498619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481901,-99) , 
17, 0.828571, 0, 0, 0.497733,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0281652);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524787,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494994,-99) , 
2, 0.264384, 0, 0, 0.500657,-99) , 
9, -1.89698, 1, 0, 0.503718,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47006,-99) , 
8, 143.005, 0, 0, 0.507573,-99) , 
NN(
0, 
0, 
-1, 1.61014, 0, -1, 0.487644,-99) , 
1, 155.996, 1, 0, 0.492679,-99) , 
3, 0.0997308, 1, 0, 0.498701,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0293721);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493171,-99) , 
11, 2.51842, 0, 0, 0.512378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47058,-99) , 
2, -0.0736901, 0, 0, 0.494343,-99) , 
4, 0, 0, 0, 0.507126,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480001,-99) , 
0, 93.0184, 0, 0, 0.502721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457559,-99) , 
0, 140.018, 1, 0, 0.498262,-99) , 
2, 0.125917, 1, 0, 0.502288,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0266575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479807,-99) , 
14, 0.475653, 1, 0, 0.490352,-99) , 
10, 1.79328, 1, 0, 0.508074,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490008,-99) , 
1, 357.116, 1, 0, 0.50535,-99) , 
NN(
0, 
0, 
-1, 0.400706, 1, -1, 0.489441,-99) , 
2, 0.130071, 1, 0, 0.496517,-99) , 
11, 2.50379, 1, 0, 0.499024,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0341063);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 330.876, 1, 1, 0.519762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48449,-99) , 
1, 405.225, 0, 0, 0.496386,-99) , 
13, 0.961906, 1, 0, 0.505392,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537437,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478924,-99) , 
18, 0.285712, 1, 0, 0.490566,-99) , 
1, 140.634, 1, 0, 0.496564,-99) , 
1, 219.355, 0, 0, 0.500609,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0233462);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49618,-99) , 
7, 221.177, 0, 0, 0.500188,-99) , 
8, 285.907, 0, 0, 0.503904,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485996,-99) , 
1, 368.049, 1, 0, 0.502965,-99) , 
NN(
0, 
0, 
-1, 0.194458, 0, -1, 0.486638,-99) , 
1, 219.355, 0, 0, 0.494293,-99) , 
17, 0.961905, 0, 0, 0.499516,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.021491);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.26117, 0, 1, 0.515773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484854,-99) , 
17, 0.994731, 1, 0, 0.501351,-99) , 
17, 0.996372, 0, 0, 0.505856,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490075,-99) , 
1, 219.355, 0, 0, 0.500378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481775,-99) , 
8, 285.823, 1, 0, 0.497307,-99) , 
17, 0.961905, 0, 0, 0.501953,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0146416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497926,-99) , 
9, 0.973104, 0, 0, 0.50172,-99) , 
11, 2.34982, 1, 0, 0.504939,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497249,-99) , 
1, 145.007, 1, 0, 0.500565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477459,-99) , 
3, -0.119336, 0, 0, 0.490057,-99) , 
1, 265.275, 1, 0, 0.496748,-99) , 
16, 0.980953, 0, 0, 0.500333,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
