// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Sat Oct  8 09:42:45 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_12/src/tHFCNC/NtupleAnalyzer/test/MVA
Training events: 697256
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB                                             'D'    [16.5751800537,500]
MVA_TOPHLEPBB                 MVA_TOPHLEPBB                 MVA_TOPHLEPBB                 MVA_TOPHLEPBB                                                   'D'    [-0.725488066673,0.747469961643]
TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB                                            'D'    [81.3465805054,500]
HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB                                      'D'    [0.384824663401,5.43350744247]
TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB                                         'D'    [0.0239859651774,11.4499855042]
HiggsBJet1CSVv2_TOPHLEPBB     HiggsBJet1CSVv2_TOPHLEPBB     HiggsBJet1CSVv2_TOPHLEPBB     HiggsBJet1CSVv2_TOPHLEPBB                                       'D'    [0.80000025034,1]
HiggsBJet2CSVv2_TOPHLEPBB     HiggsBJet2CSVv2_TOPHLEPBB     HiggsBJet2CSVv2_TOPHLEPBB     HiggsBJet2CSVv2_TOPHLEPBB                                       'D'    [-10,0.999436497688]
TopLepBJetCSVv2_TOPHLEPBB     TopLepBJetCSVv2_TOPHLEPBB     TopLepBJetCSVv2_TOPHLEPBB     TopLepBJetCSVv2_TOPHLEPBB                                       'D'    [-10,0.999942243099]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsMass_TOPHLEPBB", "MVA_TOPHLEPBB", "TopLepMass_TOPHLEPBB", "HiggsBJet1HiggsBJet2Dr_TOPHLEPBB", "TopLepHiggsDr_TOPHLEPBB", "HiggsBJet1CSVv2_TOPHLEPBB", "HiggsBJet2CSVv2_TOPHLEPBB", "TopLepBJetCSVv2_TOPHLEPBB" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.207346565885751);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.475972, 0, 1, 0.620661,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426981,-99) , 
7, 0.980648, 0, 0, 0.465699,-99) , 
NN(
0, 
0, 
-1, 0.11936, 1, -1, 0.383285,-99) , 
2, 183.357, 0, 0, 0.415384,-99) , 
6, 0.475654, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.152101);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.625289, 0, 1, 0.631036,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456865,-99) , 
6, 0.913964, 0, 0, 0.510678,-99) , 
7, 0.475972, 0, 0, 0.570774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45554,-99) , 
0, 109.549, 1, 0, 0.49043,-99) , 
NN(
0, 
0, 
-1, 3.12467, 1, -1, 0.417166,-99) , 
5, 0.980952, 0, 0, 0.448039,-99) , 
6, 0.475654, 0, 0, 0.498434,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.115369);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.650228, 0, 1, 0.594973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470621,-99) , 
3, 1.78437, 1, 0, 0.509504,-99) , 
7, 0.475972, 0, 0, 0.551921,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42003,-99) , 
4, 3.12467, 1, 0, 0.458089,-99) , 
0, 155.307, 0, 0, 0.471048,-99) , 
6, 0.475654, 0, 0, 0.504171,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.116137);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475972, 0, 1, 0.573149,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456478,-99) , 
3, 1.78261, 1, 0, 0.494938,-99) , 
5, 0.980953, 0, 0, 0.54029,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446262,-99) , 
0, 164.693, 0, 0, 0.458886,-99) , 
3, 0.865652, 1, 0, 0.470269,-99) , 
6, 0.475654, 0, 0, 0.498909,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0604918);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568741,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493579,-99) , 
3, 1.34534, 1, 0, 0.507427,-99) , 
4, 2.74446, 1, 0, 0.516692,-99) , 
NN(
0, 
0, 
-1, 0.384747, 0, -1, 0.445943,-99) , 
5, 0.904762, 0, 0, 0.50272,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0637604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475652, 0, 1, 0.53307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465034,-99) , 
1, 0.268156, 1, 0, 0.485964,-99) , 
4, 3.83265, 1, 0, 0.525402,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486108,-99) , 
5, 0.89433, 0, 0, 0.503273,-99) , 
NN(
0, 
0, 
-1, 3.13909, 1, -1, 0.455773,-99) , 
2, 181.214, 0, 0, 0.475509,-99) , 
5, 0.952381, 0, 0, 0.508038,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0526652);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475619, 0, 1, 0.544745,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48148,-99) , 
1, 0.138491, 0, 0, 0.500631,-99) , 
0, 109.629, 0, 0, 0.525509,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533405,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465914,-99) , 
2, 181.026, 0, 0, 0.481658,-99) , 
4, 2.74446, 1, 0, 0.488967,-99) , 
5, 0.990476, 0, 0, 0.502618,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0719382);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476886,-99) , 
6, 0.625289, 0, 0, 0.550647,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433017,-99) , 
0, 108.656, 0, 0, 0.485822,-99) , 
7, 0.475972, 0, 0, 0.51778,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487489,-99) , 
0, 86.3685, 1, 0, 0.49721,-99) , 
NN(
0, 
0, 
-1, 110.81, 1, -1, 0.452185,-99) , 
7, 0.904732, 0, 0, 0.486866,-99) , 
6, 0.475654, 0, 0, 0.49949,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0355198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559118,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496882,-99) , 
4, 2.92582, 1, 0, 0.507348,-99) , 
NN(
0, 
0, 
-1, 0.990126, 0, -1, 0.468339,-99) , 
4, 3.83265, 1, 0, 0.501156,-99) , 
0, 177.717, 0, 0, 0.504903,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0366441);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475591, 0, 1, 0.5364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497538,-99) , 
7, 0.475972, 0, 0, 0.524802,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497504,-99) , 
3, 1.10933, 1, 0, 0.505448,-99) , 
NN(
0, 
0, 
-1, 0.27032, 1, -1, 0.465359,-99) , 
4, 3.83265, 1, 0, 0.498767,-99) , 
5, 0.990476, 0, 0, 0.508487,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0437993);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485521,-99) , 
0, 128.386, 1, 0, 0.511592,-99) , 
0, 154.697, 0, 0, 0.515979,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477583,-99) , 
5, 0.971114, 0, 0, 0.496416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457338,-99) , 
2, 163.728, 0, 0, 0.484501,-99) , 
4, 3.83265, 1, 0, 0.510787,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0471573);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547395,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488098,-99) , 
7, 0.475972, 0, 0, 0.51687,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481699,-99) , 
7, 0.990421, 0, 0, 0.492565,-99) , 
6, 0.475654, 0, 0, 0.502587,-99) , 
0, 177.717, 0, 0, 0.505477,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0399746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.99013, 0, 1, 0.546921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480987,-99) , 
1, -0.0240795, 0, 0, 0.524483,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47924,-99) , 
4, 3.83265, 1, 0, 0.505197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471575,-99) , 
5, 0.876191, 0, 0, 0.500713,-99) , 
2, 200.962, 0, 0, 0.50696,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0300606);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562699,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487517,-99) , 
0, 109.348, 0, 0, 0.507957,-99) , 
1, 0.186343, 0, 0, 0.521324,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52584,-99) , 
NN(
0, 
0, 
-1, 128.388, 1, -1, 0.492683,-99) , 
0, 154.697, 0, 0, 0.496012,-99) , 
2, 200.962, 0, 0, 0.50266,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.029901);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475654, 0, 1, 0.525379,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486273,-99) , 
3, 2.52549, 1, 0, 0.504456,-99) , 
5, 0.990476, 0, 0, 0.512261,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48174,-99) , 
1, 0.118185, 1, 0, 0.487356,-99) , 
4, 2.97098, 1, 0, 0.493813,-99) , 
2, 161.09, 0, 0, 0.506718,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0324764);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566314,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472439,-99) , 
3, 1.46266, 0, 0, 0.490001,-99) , 
6, 0.475632, 0, 0, 0.518501,-99) , 
NN(
NN(
0, 
0, 
-1, 0.475591, 0, 1, 0.506903,-99) , 
NN(
0, 
0, 
-1, 108.656, 0, -1, 0.471654,-99) , 
7, 0.476135, 0, 0, 0.499117,-99) , 
1, 0.326625, 0, 0, 0.502966,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0343878);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.949553, 0, 1, 0.521531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469966,-99) , 
1, 0.0406138, 0, 0, 0.509192,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493312,-99) , 
1, 0.0690122, 1, 0, 0.497898,-99) , 
NN(
0, 
0, 
-1, 110.81, 1, -1, 0.469777,-99) , 
7, 0.904732, 0, 0, 0.491444,-99) , 
6, 0.475654, 0, 0, 0.498673,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0275149);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479534,-99) , 
4, 3.57506, 1, 0, 0.49812,-99) , 
6, 0.475632, 0, 0, 0.51739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497016,-99) , 
4, 2.57799, 1, 0, 0.500838,-99) , 
NN(
0, 
0, 
-1, 108.656, 0, -1, 0.476395,-99) , 
7, 0.476135, 0, 0, 0.49544,-99) , 
1, 0.326625, 0, 0, 0.499794,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0339916);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.990477, 0, 1, 0.527237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478349,-99) , 
1, -0.0942203, 0, 0, 0.516188,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495601,-99) , 
2, 166.785, 0, 0, 0.503614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468653,-99) , 
0, 166.755, 0, 0, 0.486801,-99) , 
0, 131.676, 1, 0, 0.4993,-99) , 
2, 200.962, 0, 0, 0.503734,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0303366);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494442,-99) , 
4, 3.31098, 1, 0, 0.505999,-99) , 
2, 201.138, 0, 0, 0.510757,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492655,-99) , 
3, 1.58689, 1, 0, 0.502939,-99) , 
NN(
0, 
0, 
-1, 0.990541, 0, -1, 0.474247,-99) , 
7, 0.475972, 0, 0, 0.496334,-99) , 
1, 0.186343, 0, 0, 0.503307,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0183015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531551,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499855,-99) , 
3, 2.25169, 1, 0, 0.51975,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496443,-99) , 
0, 155.307, 0, 0, 0.499308,-99) , 
4, 2.74446, 1, 0, 0.502508,-99) , 
1, 0.466907, 0, 0, 0.504118,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.03175);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475619, 0, 1, 0.526854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485438,-99) , 
3, 1.65276, 0, 0, 0.499123,-99) , 
0, 109.629, 0, 0, 0.514762,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495656,-99) , 
0, 118.335, 1, 0, 0.508593,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48947,-99) , 
3, 1.11285, 1, 0, 0.495593,-99) , 
1, 0.186343, 0, 0, 0.501919,-99) , 
5, 0.990476, 0, 0, 0.506707,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0222825);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.25169, 1, 1, 0.520882,-99) , 
NN(
NN(
0, 
0, 
-1, 0.475654, 0, 1, 0.507279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480423,-99) , 
6, 0.393441, 0, 0, 0.491276,-99) , 
5, 0.914286, 0, 0, 0.50368,-99) , 
4, 2.74446, 1, 0, 0.506228,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0182961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48878,-99) , 
1, -0.0240795, 0, 0, 0.514511,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524922,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482662,-99) , 
0, 131.675, 1, 0, 0.497564,-99) , 
0, 177.717, 0, 0, 0.49936,-99) , 
2, 220.898, 0, 0, 0.502056,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0222966);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493861,-99) , 
0, 109.348, 0, 0, 0.513936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491819,-99) , 
1, 0.368703, 0, 0, 0.494827,-99) , 
0, 177.717, 0, 0, 0.496502,-99) , 
2, 220.898, 0, 0, 0.499603,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0127695);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.25169, 1, 1, 0.517236,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499541,-99) , 
4, 2.92213, 1, 0, 0.501975,-99) , 
NN(
0, 
0, 
-1, 109.629, 1, -1, 0.485884,-99) , 
4, 3.98811, 1, 0, 0.499538,-99) , 
4, 2.74446, 1, 0, 0.502159,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0148205);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0661087, 0, 1, 0.528179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488147,-99) , 
1, -0.0942203, 0, 0, 0.516241,-99) , 
NN(
NN(
0, 
0, 
-1, 0.341609, 0, 1, 0.502741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478502,-99) , 
4, 4.37675, 1, 0, 0.501154,-99) , 
2, 220.898, 0, 0, 0.503837,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0161343);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49976,-99) , 
0, 109.348, 0, 0, 0.514751,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492259,-99) , 
6, 0.475654, 0, 0, 0.49677,-99) , 
0, 177.717, 0, 0, 0.497934,-99) , 
2, 220.898, 0, 0, 0.500924,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0203078);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497022,-99) , 
1, -0.0240795, 0, 0, 0.515031,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497711,-99) , 
7, 0.825344, 1, 0, 0.500879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461285,-99) , 
1, 0.170611, 0, 0, 0.488271,-99) , 
7, 0.476135, 0, 0, 0.498398,-99) , 
2, 220.898, 0, 0, 0.501355,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0734468);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473824,-99) , 
6, 0.285712, 0, 0, 0.512001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48341,-99) , 
7, 0.818217, 1, 0, 0.496033,-99) , 
7, 0.925114, 0, 0, 0.506511,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466221,-99) , 
3, 2.25047, 1, 0, 0.51109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466981,-99) , 
0, 108.656, 0, 0, 0.493348,-99) , 
7, 0.476135, 0, 0, 0.503787,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0346947);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.58689, 0, 1, 0.519923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492208,-99) , 
7, 0.866648, 0, 0, 0.516214,-99) , 
NN(
NN(
0, 
0, 
-1, 0.966181, 0, 1, 0.510091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45996,-99) , 
6, 0.65025, 0, 0, 0.500297,-99) , 
6, 0.475654, 1, 0, 0.509738,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0309504);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 143.777, 1, 1, 0.509868,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475597,-99) , 
3, 1.31932, 1, 0, 0.485419,-99) , 
6, 0.949553, 0, 0, 0.49501,-99) , 
6, 0.475654, 1, 0, 0.503823,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0162386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494223,-99) , 
3, 2.48345, 1, 0, 0.51107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510144,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494517,-99) , 
3, 0.754713, 1, 0, 0.496314,-99) , 
0, 155.307, 0, 0, 0.497814,-99) , 
4, 2.74446, 1, 0, 0.499779,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0161283);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 260.77, 0, 1, 0.523134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495281,-99) , 
0, 108.656, 1, 0, 0.499428,-99) , 
2, 220.898, 0, 0, 0.503054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483186,-99) , 
1, -0.164361, 0, 0, 0.501868,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0208555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.977, 1, 1, 0.506005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486799,-99) , 
4, 4.15823, 1, 0, 0.504048,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482449,-99) , 
6, 0.913943, 0, 0, 0.506886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474057,-99) , 
0, 108.656, 0, 0, 0.493652,-99) , 
7, 0.476135, 0, 0, 0.501896,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0137764);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 260.77, 0, 1, 0.516897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492127,-99) , 
3, 1.82731, 0, 0, 0.496855,-99) , 
2, 220.898, 0, 0, 0.499919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484668,-99) , 
1, -0.164361, 0, 0, 0.499009,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0117785);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514825,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497365,-99) , 
0, 86.3685, 1, 0, 0.499838,-99) , 
NN(
0, 
0, 
-1, 108.656, 0, -1, 0.489654,-99) , 
7, 0.476135, 0, 0, 0.497674,-99) , 
1, 0.466907, 0, 0, 0.498621,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0110403);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512578,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49986,-99) , 
2, 141.366, 1, 0, 0.501773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469043,-99) , 
3, 1.45326, 1, 0, 0.485228,-99) , 
1, 0.0349469, 0, 0, 0.499015,-99) , 
0, 154.697, 0, 0, 0.50034,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0208568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495707,-99) , 
3, 1.58901, 0, 0, 0.502623,-99) , 
2, 221.062, 0, 0, 0.504385,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47936,-99) , 
0, 85.6359, 0, 0, 0.501406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473609,-99) , 
3, 2.54599, 1, 0, 0.49357,-99) , 
1, 0.0460614, 0, 0, 0.501764,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0163949);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.99681, 0, 1, 0.512341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488503,-99) , 
4, 3.97361, 1, 0, 0.507288,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499171,-99) , 
3, 0.865652, 1, 0, 0.501633,-99) , 
NN(
0, 
0, 
-1, 0.904469, 1, -1, 0.48295,-99) , 
7, 0.475972, 0, 0, 0.497416,-99) , 
1, 0.256484, 0, 0, 0.500666,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0157831);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513596,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497141,-99) , 
0, 115.577, 1, 0, 0.503267,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475528,-99) , 
3, 1.45326, 1, 0, 0.489163,-99) , 
1, 0.0349469, 0, 0, 0.500917,-99) , 
0, 154.697, 0, 0, 0.502155,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.00836279);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.35581, 1, 1, 0.511042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491354,-99) , 
1, 0.0126559, 0, 0, 0.498604,-99) , 
1, 0.466907, 0, 0, 0.499629,-99) , 
4, 2.74446, 1, 0, 0.50132,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0113641);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499087,-99) , 
4, 2.35581, 1, 0, 0.508953,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49602,-99) , 
0, 155.307, 0, 0, 0.497381,-99) , 
1, 0.466907, 0, 0, 0.498351,-99) , 
4, 2.74446, 1, 0, 0.499921,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0159111);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.475597, 0, 1, 0.516191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481016,-99) , 
0, 86.3685, 0, 0, 0.508093,-99) , 
NN(
NN(
0, 
0, 
-1, 0.167554, 0, 1, 0.512212,-99) , 
NN(
0, 
0, 
-1, 152.139, 0, -1, 0.496668,-99) , 
2, 144.002, 1, 0, 0.499243,-99) , 
2, 200.962, 0, 0, 0.501561,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.00830699);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 237.985, 0, 1, 0.503762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489024,-99) , 
2, 300.641, 1, 0, 0.502962,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0146322);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498006,-99) , 
3, 2.25169, 1, 0, 0.508811,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496227,-99) , 
6, 0.475632, 0, 0, 0.506154,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481931,-99) , 
7, 0.476135, 0, 0, 0.497876,-99) , 
1, 0.326625, 0, 0, 0.499772,-99) , 
4, 2.74446, 1, 0, 0.501111,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.01343);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.23925, 0, 1, 0.517858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496209,-99) , 
4, 3.61446, 1, 0, 0.5083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513582,-99) , 
NN(
0, 
0, 
-1, 0.476135, 0, -1, 0.495646,-99) , 
4, 2.57799, 1, 0, 0.497866,-99) , 
1, 0.326625, 0, 0, 0.499932,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0160853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.61446, 1, 1, 0.516155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495709,-99) , 
5, 0.961905, 0, 0, 0.507908,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494508,-99) , 
7, 0.900177, 0, 0, 0.503016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480306,-99) , 
6, 0.913965, 1, 0, 0.491128,-99) , 
7, 0.476135, 0, 0, 0.500392,-99) , 
1, 0.326625, 0, 0, 0.501881,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0122828);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523509,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490912,-99) , 
4, 3.61446, 1, 0, 0.501202,-99) , 
2, 182.504, 0, 0, 0.507132,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498678,-99) , 
0, 86.3685, 1, 0, 0.501209,-99) , 
NN(
0, 
0, 
-1, 108.656, 0, -1, 0.491241,-99) , 
7, 0.476135, 0, 0, 0.49901,-99) , 
1, 0.326625, 0, 0, 0.500618,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0181406);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492968,-99) , 
6, 0.885472, 0, 0, 0.515059,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478061,-99) , 
3, 1.12084, 0, 0, 0.50016,-99) , 
7, 0.476135, 1, 0, 0.503374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482284,-99) , 
2, 181.026, 1, 0, 0.495477,-99) , 
0, 85.6359, 0, 0, 0.501974,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0214677);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490108,-99) , 
3, 2.01504, 0, 0, 0.496162,-99) , 
5, 0.990477, 0, 0, 0.504792,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491912,-99) , 
0, 108.656, 1, 0, 0.501626,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48073,-99) , 
0, 109.629, 0, 0, 0.493203,-99) , 
5, 0.980952, 1, 0, 0.497558,-99) , 
2, 200.962, 0, 0, 0.499453,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0180235);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0622424, 0, 1, 0.511345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492334,-99) , 
2, 300.642, 1, 0, 0.505532,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490856,-99) , 
2, 181.025, 1, 0, 0.50092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487228,-99) , 
5, 0.997279, 0, 0, 0.494305,-99) , 
5, 0.980952, 1, 0, 0.497722,-99) , 
2, 220.898, 0, 0, 0.499109,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0136821);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496407,-99) , 
6, 0.475597, 0, 0, 0.508904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486219,-99) , 
0, 86.3685, 0, 0, 0.503685,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506674,-99) , 
NN(
0, 
0, 
-1, 0.876191, 0, -1, 0.495624,-99) , 
2, 189.569, 0, 0, 0.496816,-99) , 
2, 200.962, 0, 0, 0.498615,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.00672631);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498506,-99) , 
3, 2.25169, 1, 0, 0.506845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490878,-99) , 
5, 0.885714, 0, 0, 0.498973,-99) , 
4, 2.74446, 1, 0, 0.500205,-99) , 
1, 0.466907, 0, 0, 0.500875,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.00846236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.35581, 1, 1, 0.507099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497061,-99) , 
3, 3.02937, 0, 0, 0.497813,-99) , 
1, 0.466907, 0, 0, 0.498617,-99) , 
4, 2.74446, 1, 0, 0.499873,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0209857);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524537,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49443,-99) , 
4, 3.05393, 1, 0, 0.501132,-99) , 
3, 2.79016, 0, 0, 0.503709,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495821,-99) , 
0, 85.6359, 0, 0, 0.507556,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488321,-99) , 
0, 110.911, 1, 0, 0.493125,-99) , 
3, 1.58689, 1, 0, 0.498261,-99) , 
1, 0.186343, 0, 0, 0.500894,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0140139);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511778,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51642,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494986,-99) , 
1, 0.220796, 0, 0, 0.500214,-99) , 
3, 0.754713, 1, 0, 0.501408,-99) , 
0, 154.697, 0, 0, 0.502421,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0114793);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497424,-99) , 
3, 2.07844, 1, 0, 0.515716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48974,-99) , 
0, 87.4627, 0, 0, 0.499373,-99) , 
0, 109.348, 0, 0, 0.5072,-99) , 
NN(
NN(
0, 
0, 
-1, 0.167554, 0, 1, 0.508088,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485552,-99) , 
2, 152.139, 0, 0, 0.498779,-99) , 
2, 144.002, 1, 0, 0.50032,-99) , 
2, 200.962, 0, 0, 0.502122,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0163086);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.07844, 1, 1, 0.51549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49266,-99) , 
5, 0.97143, 1, 0, 0.499174,-99) , 
0, 109.348, 0, 0, 0.506988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491419,-99) , 
6, 0.457858, 1, 0, 0.501215,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488049,-99) , 
6, 0.475652, 0, 0, 0.494545,-99) , 
5, 0.980952, 1, 0, 0.497993,-99) , 
2, 200.962, 0, 0, 0.500348,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0127676);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493535,-99) , 
4, 3.1373, 1, 0, 0.499267,-99) , 
5, 0.990477, 0, 0, 0.50521,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497983,-99) , 
1, 0.167554, 0, 0, 0.504526,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493204,-99) , 
2, 176.55, 0, 0, 0.49602,-99) , 
2, 144.002, 1, 0, 0.497428,-99) , 
2, 200.962, 0, 0, 0.499465,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.00780458);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497783,-99) , 
0, 109.348, 0, 0, 0.506893,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513103,-99) , 
NN(
0, 
0, 
-1, 0.0531746, 0, -1, 0.497686,-99) , 
1, -0.0608449, 1, 0, 0.498868,-99) , 
2, 240.834, 0, 0, 0.49986,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.00952324);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491789,-99) , 
1, 0.0503166, 0, 0, 0.500159,-99) , 
2, 260.769, 0, 0, 0.501975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491128,-99) , 
1, -0.164361, 0, 0, 0.501328,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0108748);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517227,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493217,-99) , 
0, 99.4993, 0, 0, 0.500892,-99) , 
0, 132.328, 0, 0, 0.50427,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498181,-99) , 
0, 85.6359, 1, 0, 0.499898,-99) , 
NN(
0, 
0, 
-1, 189.569, 0, -1, 0.491446,-99) , 
2, 183.873, 1, 0, 0.498377,-99) , 
2, 200.962, 0, 0, 0.49992,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.00869037);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512962,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49775,-99) , 
1, 0.349042, 0, 0, 0.499508,-99) , 
3, 0.754713, 1, 0, 0.500499,-99) , 
0, 154.697, 0, 0, 0.501259,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00853597);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497991,-99) , 
4, 2.48535, 1, 0, 0.507787,-99) , 
NN(
NN(
0, 
0, 
-1, 0.476135, 1, 1, 0.502404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489662,-99) , 
3, 1.82929, 0, 0, 0.495719,-99) , 
5, 0.904762, 0, 0, 0.501072,-99) , 
4, 2.74446, 1, 0, 0.502066,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0104544);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.35581, 1, 1, 0.507558,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497723,-99) , 
4, 2.98135, 1, 0, 0.500353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48624,-99) , 
0, 109.629, 1, 0, 0.494112,-99) , 
4, 3.98811, 1, 0, 0.499407,-99) , 
4, 2.74446, 1, 0, 0.500614,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.00755556);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492087,-99) , 
1, 0.00738254, 0, 0, 0.500306,-99) , 
2, 260.769, 0, 0, 0.501981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492777,-99) , 
1, -0.164361, 0, 0, 0.501432,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0076559);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507018,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497564,-99) , 
5, 0.857143, 1, 0, 0.498518,-99) , 
3, 0.754713, 1, 0, 0.499377,-99) , 
0, 154.697, 0, 0, 0.500123,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00808616);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495502,-99) , 
2, 302.541, 1, 0, 0.506755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513763,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487383,-99) , 
1, 0.0531746, 0, 0, 0.499209,-99) , 
1, -0.0608449, 1, 0, 0.500325,-99) , 
2, 240.834, 0, 0, 0.501119,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00784225);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496198,-99) , 
3, 1.55152, 1, 0, 0.506469,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511743,-99) , 
NN(
0, 
0, 
-1, 0.876191, 0, -1, 0.497672,-99) , 
1, -0.0608449, 1, 0, 0.498751,-99) , 
2, 240.834, 0, 0, 0.499704,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.00737341);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524779,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493095,-99) , 
5, 0.876191, 0, 0, 0.500077,-99) , 
2, 260.769, 0, 0, 0.501711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492279,-99) , 
1, -0.164361, 0, 0, 0.501149,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.00621883);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497435,-99) , 
4, 3.32988, 0, 0, 0.505571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509825,-99) , 
NN(
0, 
0, 
-1, 0.0531746, 0, -1, 0.498281,-99) , 
1, -0.0608449, 1, 0, 0.499166,-99) , 
2, 240.834, 0, 0, 0.499957,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0100952);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.77903, 1, 1, 0.507943,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496756,-99) , 
3, 2.06758, 0, 0, 0.499531,-99) , 
4, 2.92582, 1, 0, 0.5017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493798,-99) , 
4, 4.37675, 1, 0, 0.501143,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0214766);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489885,-99) , 
1, 0.0865768, 1, 0, 0.496901,-99) , 
4, 3.03235, 1, 0, 0.503969,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493439,-99) , 
7, 0.476135, 0, 0, 0.503577,-99) , 
NN(
0, 
0, 
-1, -0.0828171, 1, -1, 0.485662,-99) , 
1, 0.0242959, 0, 0, 0.499687,-99) , 
3, 1.58689, 1, 0, 0.501333,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0157811);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494619,-99) , 
6, 0.824839, 0, 0, 0.516583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477832,-99) , 
0, 109.348, 1, 0, 0.497016,-99) , 
6, 0.475647, 0, 0, 0.504258,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512746,-99) , 
NN(
0, 
0, 
-1, 0.0242959, 0, -1, 0.497229,-99) , 
5, 0.857143, 1, 0, 0.498609,-99) , 
3, 1.58689, 1, 0, 0.50078,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0140769);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498136,-99) , 
3, 2.25047, 1, 0, 0.516673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494084,-99) , 
0, 108.656, 0, 0, 0.507574,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496132,-99) , 
0, 73.2371, 1, 0, 0.510838,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48867,-99) , 
3, 1.36043, 0, 0, 0.498676,-99) , 
0, 86.3685, 1, 0, 0.501032,-99) , 
7, 0.476135, 1, 0, 0.502384,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0151264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497184,-99) , 
1, 0.0505481, 1, 0, 0.500471,-99) , 
1, 0.179905, 0, 0, 0.508807,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499652,-99) , 
0, 73.2371, 1, 0, 0.510722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494458,-99) , 
0, 145.459, 0, 0, 0.496558,-99) , 
0, 86.3685, 1, 0, 0.499301,-99) , 
7, 0.476135, 1, 0, 0.501265,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00673018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514939,-99) , 
NN(
NN(
0, 
0, 
-1, 260.769, 0, 1, 0.502405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49332,-99) , 
1, -0.157685, 0, 0, 0.5018,-99) , 
1, 0.466907, 0, 0, 0.502524,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00631015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498663,-99) , 
1, -0.0694461, 1, 0, 0.499662,-99) , 
2, 260.769, 0, 0, 0.500341,-99) , 
1, 0.466907, 0, 0, 0.501054,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0195721);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495789,-99) , 
6, 0.949553, 0, 0, 0.50772,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497212,-99) , 
2, 143.948, 1, 0, 0.500311,-99) , 
6, 0.475654, 0, 0, 0.503306,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491417,-99) , 
0, 85.6359, 0, 0, 0.503708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482492,-99) , 
3, 2.54599, 1, 0, 0.497727,-99) , 
1, 0.0460614, 0, 0, 0.501955,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.017573);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.949553, 0, 1, 0.51051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496801,-99) , 
4, 3.12467, 0, 0, 0.504095,-99) , 
6, 0.475654, 0, 0, 0.506688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514618,-99) , 
NN(
0, 
0, 
-1, 0.475652, 1, -1, 0.491642,-99) , 
3, 1.34534, 1, 0, 0.498377,-99) , 
1, 0.0460614, 0, 0, 0.504676,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0130574);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499505,-99) , 
0, 131.676, 0, 0, 0.502555,-99) , 
1, 0.326625, 0, 0, 0.505215,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498642,-99) , 
3, 2.3396, 0, 0, 0.504666,-99) , 
NN(
0, 
0, 
-1, 0.980953, 0, -1, 0.489777,-99) , 
0, 132.328, 1, 0, 0.500701,-99) , 
4, 3.28856, 1, 0, 0.503502,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.012513);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524219,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495261,-99) , 
1, 0.00738254, 0, 0, 0.504161,-99) , 
2, 260.769, 0, 0, 0.505487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496514,-99) , 
1, -0.164361, 0, 0, 0.504952,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00937944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.35581, 1, 1, 0.507708,-99) , 
NN(
NN(
0, 
0, 
-1, 0.396766, 0, 1, 0.503256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487826,-99) , 
1, 0.201575, 1, 0, 0.494493,-99) , 
4, 3.98811, 1, 0, 0.501927,-99) , 
4, 2.74446, 1, 0, 0.502783,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00514786);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497959,-99) , 
4, 2.35581, 1, 0, 0.505363,-99) , 
NN(
NN(
0, 
0, 
-1, 178.287, 0, 1, 0.500959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492677,-99) , 
5, 0.866667, 0, 0, 0.500013,-99) , 
4, 2.74446, 1, 0, 0.500806,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00587198);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499246,-99) , 
4, 2.35581, 1, 0, 0.505539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495564,-99) , 
6, 0.475654, 1, 0, 0.498454,-99) , 
1, 0.466907, 0, 0, 0.49902,-99) , 
4, 2.74446, 1, 0, 0.499986,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00728278);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.97143, 1, 1, 0.505739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498234,-99) , 
1, 0.396766, 0, 0, 0.499561,-99) , 
NN(
0, 
0, 
-1, 0.268156, 1, -1, 0.493545,-99) , 
4, 3.98811, 1, 0, 0.498649,-99) , 
4, 2.74446, 1, 0, 0.499699,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0175568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478598,-99) , 
7, 0.980649, 1, 0, 0.499225,-99) , 
6, 0.475654, 0, 0, 0.504158,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496844,-99) , 
0, 108.656, 1, 0, 0.502529,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492797,-99) , 
5, 0.998186, 0, 0, 0.496186,-99) , 
5, 0.980952, 1, 0, 0.499466,-99) , 
2, 200.962, 0, 0, 0.500694,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00709232);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514759,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496263,-99) , 
0, 115.963, 1, 0, 0.499546,-99) , 
0, 147.021, 0, 0, 0.500495,-99) , 
0, 177.717, 0, 0, 0.501118,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0147519);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496247,-99) , 
1, 0.2407, 0, 0, 0.499916,-99) , 
3, 1.36186, 1, 0, 0.50263,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498491,-99) , 
5, 0.980625, 1, 0, 0.506803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477937,-99) , 
6, 0.475654, 1, 0, 0.49224,-99) , 
3, 1.67545, 0, 0, 0.497867,-99) , 
0, 108.656, 0, 0, 0.500497,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00847609);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511684,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496502,-99) , 
3, 2.04932, 0, 0, 0.498635,-99) , 
0, 147.021, 0, 0, 0.499633,-99) , 
0, 177.717, 0, 0, 0.500409,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0204719);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509566,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466386,-99) , 
6, 0.625308, 0, 0, 0.504256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494354,-99) , 
0, 78.4902, 1, 0, 0.497024,-99) , 
6, 0.475654, 0, 0, 0.499993,-99) , 
0, 177.717, 0, 0, 0.50061,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0185336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 143.777, 1, 1, 0.504615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483907,-99) , 
6, 0.874727, 0, 0, 0.498191,-99) , 
6, 0.475654, 1, 0, 0.501954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492081,-99) , 
3, 0.865652, 0, 0, 0.500963,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0121047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487982,-99) , 
7, 0.476135, 0, 0, 0.498775,-99) , 
1, 0.326625, 0, 0, 0.500835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511094,-99) , 
NN(
0, 
0, 
-1, 132.592, 1, -1, 0.494073,-99) , 
2, 240.834, 0, 0, 0.496506,-99) , 
4, 3.28856, 1, 0, 0.499193,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0073789);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508309,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497672,-99) , 
1, -0.079276, 1, 0, 0.498814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490574,-99) , 
2, 300.641, 1, 0, 0.498342,-99) , 
1, 0.466907, 0, 0, 0.498891,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.00601533);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515661,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494064,-99) , 
1, 0.0503166, 0, 0, 0.499764,-99) , 
2, 260.769, 0, 0, 0.500815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491194,-99) , 
1, -0.164361, 0, 0, 0.500241,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00430664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509017,-99) , 
NN(
0, 
0, 
-1, 0.00449945, 0, -1, 0.498886,-99) , 
1, -0.0726408, 1, 0, 0.49978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491862,-99) , 
2, 300.641, 1, 0, 0.499351,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00532304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499091,-99) , 
2, 132.61, 1, 0, 0.499744,-99) , 
2, 260.769, 0, 0, 0.500752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492311,-99) , 
1, -0.164361, 0, 0, 0.500248,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00688575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488964,-99) , 
1, 0.00449945, 0, 0, 0.501072,-99) , 
1, -0.0726408, 1, 0, 0.501766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492546,-99) , 
2, 300.641, 1, 0, 0.501267,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00638954);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514251,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4977,-99) , 
6, 0.475654, 0, 0, 0.499404,-99) , 
2, 260.769, 0, 0, 0.500385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493022,-99) , 
1, -0.164361, 0, 0, 0.499946,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
