// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Sat Oct  8 09:23:51 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_12/src/tHFCNC/NtupleAnalyzer/test/MVA
Training events: 1342572
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
HiggsMass_TOPTOPLEPHBB        HiggsMass_TOPTOPLEPHBB        HiggsMass_TOPTOPLEPHBB        HiggsMass_TOPTOPLEPHBB                                          'D'    [16.1990242004,500]
MVA_TOPTOPLEPHBB              MVA_TOPTOPLEPHBB              MVA_TOPTOPLEPHBB              MVA_TOPTOPLEPHBB                                                'D'    [-0.876381695271,0.695079147816]
MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD                                                'D'    [-0.879554510117,0.690950393677]
TopLepMass_TOPTOPLEPHBB       TopLepMass_TOPTOPLEPHBB       TopLepMass_TOPTOPLEPHBB       TopLepMass_TOPTOPLEPHBB                                         'D'    [35.7756080627,500]
TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD                                         'D'    [49.3037643433,500]
HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB                                         'D'    [0.385648816824,5.59136295319]
TopLepHiggsDr_TOPTOPLEPHBB    TopLepHiggsDr_TOPTOPLEPHBB    TopLepHiggsDr_TOPTOPLEPHBB    TopLepHiggsDr_TOPTOPLEPHBB                                      'D'    [0.00797547958791,11.9889259338]
TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD                                     'D'    [0.0151111688465,11.0869293213]
HiggsBJet1CSVv2_TOPTOPLEPHBB  HiggsBJet1CSVv2_TOPTOPLEPHBB  HiggsBJet1CSVv2_TOPTOPLEPHBB  HiggsBJet1CSVv2_TOPTOPLEPHBB                                    'D'    [-10,1]
HiggsBJet2CSVv2_TOPTOPLEPHBB  HiggsBJet2CSVv2_TOPTOPLEPHBB  HiggsBJet2CSVv2_TOPTOPLEPHBB  HiggsBJet2CSVv2_TOPTOPLEPHBB                                    'D'    [-10,0.799997150898]
TopLepBJetCSVv2_TOPTOPLEPHBB  TopLepBJetCSVv2_TOPTOPLEPHBB  TopLepBJetCSVv2_TOPTOPLEPHBB  TopLepBJetCSVv2_TOPTOPLEPHBB                                    'D'    [-10,1]
TopHadNonBJetCSVv2_TOPTOPLEPHBB TopHadNonBJetCSVv2_TOPTOPLEPHBB TopHadNonBJetCSVv2_TOPTOPLEPHBB TopHadNonBJetCSVv2_TOPTOPLEPHBB                                     'D'    [-10,0.794426560402]
TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD                                    'D'    [-10,1]
TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD                                    'D'    [-10,1]
TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD                                       'D'    [-10,0.79971408844]
TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD                                       'D'    [-10,0.790807247162]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsMass_TOPTOPLEPHBB", "MVA_TOPTOPLEPHBB", "MVA_TOPTOPLEPHAD", "TopLepMass_TOPTOPLEPHBB", "TopLepMass_TOPTOPLEPHAD", "HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB", "TopLepHiggsDr_TOPTOPLEPHBB", "TopLepTopHadDr_TOPTOPLEPHAD", "HiggsBJet1CSVv2_TOPTOPLEPHBB", "HiggsBJet2CSVv2_TOPTOPLEPHBB", "TopLepBJetCSVv2_TOPTOPLEPHBB", "TopHadNonBJetCSVv2_TOPTOPLEPHBB", "TopLepBJetCSVv2_TOPTOPLEPHAD", "TopHadBJetCSVv2_TOPTOPLEPHAD", "TopHadWNonBJet1CSVv2_TOPTOPLEPHAD", "TopHadWNonBJet2CSVv2_TOPTOPLEPHAD" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.20269990158918);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.285442, 0, 1, 0.661037,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493607,-99) , 
10, 0.47619, 0, 0, 0.544224,-99) , 
9, 0.555099, 0, 0, 0.587507,-99) , 
NN(
0, 
0, 
-1, -9.51023, 0, -1, 0.388139,-99) , 
9, 0.285712, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.169644);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.446574, 0, 1, 0.589093,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432064,-99) , 
8, 0.955472, 0, 0, 0.465178,-99) , 
14, 0.229083, 0, 0, 0.53272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325432,-99) , 
15, -9.48615, 0, 0, 0.508114,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.11155);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.177539, 0, 1, 0.582739,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422082,-99) , 
2, 0.242235, 1, 0, 0.478981,-99) , 
9, 0.443218, 0, 0, 0.5144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351903,-99) , 
11, -9.48598, 0, 0, 0.497272,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0806381);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61593,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423281,-99) , 
14, 0.15773, 0, 0, 0.485215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381473,-99) , 
15, -9.48737, 0, 0, 0.472196,-99) , 
11, 0.280406, 0, 0, 0.484864,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0964901);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596684,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448455,-99) , 
7, 3.17849, 1, 0, 0.482967,-99) , 
NN(
0, 
0, 
-1, 2.92934, 1, -1, 0.412287,-99) , 
13, 0.47619, 0, 0, 0.465146,-99) , 
11, 0.280406, 0, 0, 0.476668,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0872288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573264,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455757,-99) , 
11, 0.147387, 0, 0, 0.477777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400272,-99) , 
11, -9.51046, 0, 0, 0.468991,-99) , 
11, 0.280406, 0, 0, 0.478082,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0665728);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492076,-99) , 
9, 0.28571, 0, 0, 0.546452,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454867,-99) , 
12, 0.47619, 0, 0, 0.493831,-99) , 
5, 1.37721, 1, 0, 0.512831,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456176,-99) , 
2, 0.144965, 1, 0, 0.478186,-99) , 
NN(
0, 
0, 
-1, 0.933336, 0, -1, 0.423035,-99) , 
13, 0.47619, 0, 0, 0.465123,-99) , 
4, 199.536, 0, 0, 0.482793,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0701933);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574821,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481414,-99) , 
0, 108.352, 0, 0, 0.499405,-99) , 
7, 2.86898, 1, 0, 0.517307,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459539,-99) , 
8, 0.955472, 0, 0, 0.476417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408737,-99) , 
11, -9.48615, 0, 0, 0.46942,-99) , 
5, 1.37721, 1, 0, 0.482842,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0680578);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561729,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495946,-99) , 
2, -0.0530965, 1, 0, 0.523194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463582,-99) , 
7, 2.65126, 1, 0, 0.47197,-99) , 
5, 1.12932, 1, 0, 0.481747,-99) , 
15, 0.276959, 0, 0, 0.487557,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0525973);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.285692, 0, 1, 0.538422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471744,-99) , 
10, 0.47619, 0, 0, 0.493323,-99) , 
5, 1.37721, 1, 0, 0.506787,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477359,-99) , 
6, 3.83863, 1, 0, 0.487484,-99) , 
NN(
0, 
0, 
-1, 4.15496, 1, -1, 0.444948,-99) , 
4, 185.406, 0, 0, 0.466795,-99) , 
6, 3.4311, 1, 0, 0.495316,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0565101);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58543,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482319,-99) , 
10, 0.954852, 0, 0, 0.491953,-99) , 
14, 0.550063, 0, 0, 0.499437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44777,-99) , 
15, -9.48615, 0, 0, 0.493546,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0486002);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.285282, 0, 1, 0.536625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467072,-99) , 
0, 131.39, 1, 0, 0.493711,-99) , 
8, 0.975057, 0, 0, 0.508814,-99) , 
NN(
0, 
0, 
-1, 0.971429, 0, -1, 0.456025,-99) , 
8, 0.47619, 0, 0, 0.500831,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0423455);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.86889, 1, 1, 0.516147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469989,-99) , 
1, -0.27773, 0, 0, 0.511103,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475508,-99) , 
5, 1.62545, 1, 0, 0.485235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447612,-99) , 
2, 0.362323, 1, 0, 0.478866,-99) , 
4, 178.074, 0, 0, 0.496097,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0320774);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548232,-99) , 
NN(
0, 
0, 
-1, 0.284457, 0, -1, 0.492206,-99) , 
9, 0.657285, 0, 0, 0.498801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453428,-99) , 
11, -9.48598, 0, 0, 0.49416,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0410647);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498296,-99) , 
8, 0.914594, 0, 0, 0.515552,-99) , 
NN(
0, 
0, 
-1, 0.164949, 1, -1, 0.478694,-99) , 
15, 0.0992558, 0, 0, 0.505217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463633,-99) , 
15, -9.48615, 0, 0, 0.500484,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0370372);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.954852, 0, 1, 0.518915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473131,-99) , 
15, -9.48615, 0, 0, 0.513765,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466823,-99) , 
6, 3.45554, 1, 0, 0.494904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462312,-99) , 
2, 0.3175, 1, 0, 0.487744,-99) , 
3, 168.411, 0, 0, 0.504712,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0286596);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52983,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491866,-99) , 
6, 2.61606, 1, 0, 0.498183,-99) , 
5, 0.881431, 1, 0, 0.501902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459567,-99) , 
6, 4.57215, 1, 0, 0.49937,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0305393);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0144667, 1, 1, 0.516263,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478427,-99) , 
4, 185.527, 0, 0, 0.493673,-99) , 
6, 3.43483, 1, 0, 0.509349,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479626,-99) , 
10, 0.47619, 0, 0, 0.493597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456963,-99) , 
8, 0.47619, 0, 0, 0.488156,-99) , 
3, 168.411, 0, 0, 0.501975,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0223413);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529467,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486804,-99) , 
3, 190.517, 0, 0, 0.493405,-99) , 
11, 0.280406, 0, 0, 0.496062,-99) , 
2, -0.356053, 1, 0, 0.498375,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0203962);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.24609, 0, 1, 0.508744,-99) , 
NN(
0, 
0, 
-1, 146.305, 0, -1, 0.491671,-99) , 
2, 0.092909, 1, 0, 0.500394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463771,-99) , 
6, 4.57215, 1, 0, 0.498204,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0452838);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451639,-99) , 
8, 0.660459, 0, 0, 0.513526,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463237,-99) , 
10, 0.47619, 0, 0, 0.492322,-99) , 
9, 0.285712, 0, 0, 0.5043,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480715,-99) , 
9, 0.28571, 1, 0, 0.491018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462328,-99) , 
3, 346.808, 1, 0, 0.484107,-99) , 
1, -0.0532355, 0, 0, 0.498404,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0357704);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496802,-99) , 
14, 0.285282, 0, 0, 0.515882,-99) , 
NN(
0, 
0, 
-1, -0.117051, 0, -1, 0.489294,-99) , 
8, 0.975057, 0, 0, 0.49863,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437708,-99) , 
10, 0.971429, 0, 0, 0.476939,-99) , 
8, 0.47619, 0, 0, 0.495355,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0318315);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 85.3134, 0, 1, 0.526141,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49198,-99) , 
1, 0.171999, 0, 0, 0.500349,-99) , 
5, 1.12932, 1, 0, 0.505244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446531,-99) , 
10, 0.971429, 0, 0, 0.477022,-99) , 
8, 0.47619, 0, 0, 0.500986,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.030625);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.34951, 1, 1, 0.518177,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492748,-99) , 
6, 2.63263, 1, 0, 0.498161,-99) , 
8, 0.975057, 0, 0, 0.505187,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476819,-99) , 
3, 182.499, 0, 0, 0.494697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441912,-99) , 
10, 0.933335, 0, 0, 0.477096,-99) , 
8, 0.47619, 0, 0, 0.50095,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0259864);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.975057, 0, 1, 0.517197,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494646,-99) , 
8, 0.800454, 1, 0, 0.50059,-99) , 
5, 1.37721, 1, 0, 0.50522,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484464,-99) , 
3, 182.499, 0, 0, 0.494699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449478,-99) , 
10, 0.933335, 0, 0, 0.479632,-99) , 
8, 0.47619, 0, 0, 0.501363,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.021261);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.47619, 0, 1, 0.508369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482067,-99) , 
8, 0.62585, 0, 0, 0.505855,-99) , 
NN(
0, 
0, 
-1, 1.61001, 0, -1, 0.481787,-99) , 
8, 0.47619, 0, 0, 0.502228,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0180789);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.37721, 1, 1, 0.51417,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484699,-99) , 
2, 0.37044, 1, 0, 0.498486,-99) , 
2, -0.0569091, 1, 0, 0.50335,-99) , 
NN(
0, 
0, 
-1, 0.0956441, 0, -1, 0.481814,-99) , 
0, 85.3134, 0, 0, 0.499378,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0255481);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.99355, 0, 1, 0.525553,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470223,-99) , 
11, 0.0996005, 0, 0, 0.492743,-99) , 
10, 0.954852, 0, 0, 0.499656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477514,-99) , 
11, -9.48598, 0, 0, 0.497397,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0175394);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5249,-99) , 
NN(
0, 
0, 
-1, 147.767, 0, -1, 0.494076,-99) , 
5, 0.881431, 1, 0, 0.496326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470693,-99) , 
0, 62.2753, 0, 0, 0.494625,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0184949);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488142,-99) , 
6, 3.43483, 1, 0, 0.509238,-99) , 
NN(
0, 
0, 
-1, 0.47619, 0, -1, 0.495999,-99) , 
2, -0.0569091, 1, 0, 0.500071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475065,-99) , 
0, 62.2753, 0, 0, 0.498412,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0104187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521759,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499159,-99) , 
5, 2.89998, 0, 0, 0.501344,-99) , 
5, 0.881431, 1, 0, 0.502833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479679,-99) , 
0, 62.2753, 0, 0, 0.501297,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0152501);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.273757, 1, 1, 0.506055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48486,-99) , 
1, -0.27773, 0, 0, 0.50427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479709,-99) , 
6, 4.57215, 1, 0, 0.502803,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0127685);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.12932, 1, 1, 0.503656,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467104,-99) , 
5, 1.85392, 0, 0, 0.488744,-99) , 
8, 0.47619, 0, 0, 0.501458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480219,-99) , 
0, 62.2753, 0, 0, 0.50005,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0172263);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516132,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48727,-99) , 
9, 0.285691, 1, 0, 0.509143,-99) , 
NN(
0, 
0, 
-1, -0.185941, 0, -1, 0.49425,-99) , 
0, 154.428, 0, 0, 0.496271,-99) , 
2, -0.356053, 1, 0, 0.497641,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0146415);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51638,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497435,-99) , 
2, 0.0178769, 1, 0, 0.501571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474162,-99) , 
2, 0.0956441, 0, 0, 0.489709,-99) , 
0, 85.3134, 0, 0, 0.499376,-99) , 
11, 0.280406, 0, 0, 0.500846,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0103251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.231848, 0, 1, 0.503547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483896,-99) , 
6, 4.57215, 1, 0, 0.502421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485374,-99) , 
1, -0.27773, 0, 0, 0.500946,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0126894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.87112, 1, 1, 0.505522,-99) , 
NN(
0, 
0, 
-1, 3.94805, 1, -1, 0.494193,-99) , 
3, 178.937, 0, 0, 0.500095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482289,-99) , 
3, 411.576, 1, 0, 0.499081,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0212738);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497007,-99) , 
6, 3.28634, 1, 0, 0.513026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494114,-99) , 
2, 0.321374, 1, 0, 0.506831,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489228,-99) , 
5, 2.34164, 1, 0, 0.508841,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490957,-99) , 
0, 154.428, 0, 0, 0.494179,-99) , 
6, 2.29006, 1, 0, 0.496762,-99) , 
1, 0.24609, 0, 0, 0.499137,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0179047);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498034,-99) , 
10, 0.47619, 0, 0, 0.505232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479566,-99) , 
0, 108.894, 0, 0, 0.492722,-99) , 
8, 0.47619, 0, 0, 0.503365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477111,-99) , 
9, 0.28571, 1, 0, 0.488826,-99) , 
1, -0.202898, 0, 0, 0.50133,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0171754);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481279,-99) , 
8, 0.600907, 0, 0, 0.504991,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481418,-99) , 
10, 0.961906, 0, 0, 0.492872,-99) , 
8, 0.47619, 0, 0, 0.503182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476447,-99) , 
0, 154.622, 0, 0, 0.489306,-99) , 
1, -0.202898, 0, 0, 0.50124,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0108827);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51283,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497054,-99) , 
1, 0.370817, 0, 0, 0.498454,-99) , 
2, -0.281267, 1, 0, 0.499728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485437,-99) , 
1, -0.27773, 0, 0, 0.498492,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0218877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493027,-99) , 
1, 0.160207, 0, 0, 0.498831,-99) , 
5, 1.60825, 1, 0, 0.505739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492496,-99) , 
7, 3.03148, 1, 0, 0.499459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483637,-99) , 
7, 4.23604, 1, 0, 0.497544,-99) , 
6, 2.86058, 1, 0, 0.500333,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0240391);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488103,-99) , 
13, 0.47619, 0, 0, 0.508272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480771,-99) , 
7, 3.02785, 1, 0, 0.498445,-99) , 
7, 3.17849, 0, 0, 0.502784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490154,-99) , 
1, -0.27773, 0, 0, 0.501692,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0238784);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496012,-99) , 
2, 0.377566, 1, 0, 0.511555,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483996,-99) , 
6, 3.17434, 1, 0, 0.494741,-99) , 
2, 0.0926628, 0, 0, 0.503281,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49576,-99) , 
4, 242.459, 0, 0, 0.501939,-99) , 
NN(
0, 
0, 
-1, 3.09958, 1, -1, 0.486962,-99) , 
7, 3.02785, 1, 0, 0.497131,-99) , 
7, 3.17849, 0, 0, 0.49986,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0104696);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4862,-99) , 
4, 371.23, 1, 0, 0.501799,-99) , 
11, 0.280406, 0, 0, 0.503132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492237,-99) , 
7, 4.23295, 1, 0, 0.502117,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.00969515);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498503,-99) , 
2, 0.158019, 0, 0, 0.507142,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498276,-99) , 
5, 0.857822, 1, 0, 0.500196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483676,-99) , 
6, 4.32529, 1, 0, 0.499059,-99) , 
5, 2.86456, 0, 0, 0.500304,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0117374);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497517,-99) , 
5, 2.34164, 1, 0, 0.509082,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499027,-99) , 
2, 0.0354679, 1, 0, 0.509135,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497128,-99) , 
5, 2.86456, 0, 0, 0.499129,-99) , 
6, 2.75191, 1, 0, 0.500807,-99) , 
6, 2.29006, 1, 0, 0.501934,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0206371);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.285701, 0, 1, 0.512927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498947,-99) , 
0, 124.614, 1, 0, 0.508801,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494337,-99) , 
12, 0.92517, 0, 0, 0.503737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479481,-99) , 
0, 108.572, 0, 0, 0.493658,-99) , 
12, 0.47619, 0, 0, 0.501736,-99) , 
1, 0.24609, 0, 0, 0.503402,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0131692);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.85825, 0, 1, 0.514375,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495574,-99) , 
12, 0.47619, 0, 0, 0.503186,-99) , 
1, 0.320922, 0, 0, 0.504744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509653,-99) , 
NN(
0, 
0, 
-1, 0.285442, 1, -1, 0.493261,-99) , 
5, 2.61458, 0, 0, 0.498025,-99) , 
4, 156.612, 0, 0, 0.5031,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0367713);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49593,-99) , 
10, 0.909705, 0, 0, 0.507257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482826,-99) , 
11, -9.48778, 0, 0, 0.504018,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541222,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477529,-99) , 
13, 0.965994, 0, 0, 0.488369,-99) , 
14, 0.554823, 0, 0, 0.498113,-99) , 
14, 0.285442, 1, 0, 0.501802,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0373379);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47723,-99) , 
10, 0.187341, 0, 0, 0.511555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492012,-99) , 
11, -9.48778, 0, 0, 0.508964,-99) , 
NN(
NN(
0, 
0, 
-1, 0.93668, 0, 1, 0.522148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478275,-99) , 
10, 0.523628, 1, 0, 0.488686,-99) , 
9, 0.554971, 0, 0, 0.500362,-99) , 
14, 0.285442, 1, 0, 0.505738,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0147978);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498654,-99) , 
10, 0.954852, 0, 0, 0.502398,-99) , 
15, -9.48615, 1, 0, 0.504792,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47446,-99) , 
5, 1.61001, 0, 0, 0.491941,-99) , 
8, 0.47619, 0, 0, 0.502858,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0215303);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.994061, 0, 1, 0.511777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484315,-99) , 
2, 0.0251945, 0, 0, 0.498129,-99) , 
8, 0.875283, 0, 0, 0.506721,-99) , 
NN(
0, 
0, 
-1, 1.61001, 0, -1, 0.490937,-99) , 
8, 0.47619, 0, 0, 0.504345,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0131878);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512015,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485497,-99) , 
8, 0.62585, 0, 0, 0.502317,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485666,-99) , 
2, 0.192383, 0, 0, 0.494485,-99) , 
8, 0.47619, 0, 0, 0.501098,-99) , 
2, -0.356053, 1, 0, 0.50185,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0187457);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522018,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492654,-99) , 
12, 0.47619, 0, 0, 0.499513,-99) , 
3, 323.883, 0, 0, 0.501812,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484922,-99) , 
13, 0.706429, 0, 0, 0.503687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476752,-99) , 
9, 0.383454, 0, 0, 0.496015,-99) , 
14, 0.285442, 1, 0, 0.499638,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.00781333);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506823,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497326,-99) , 
0, 177.466, 0, 0, 0.498202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48609,-99) , 
4, 349.768, 1, 0, 0.497496,-99) , 
2, -0.356053, 1, 0, 0.498138,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0108959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493723,-99) , 
9, 0.285711, 0, 0, 0.50526,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496892,-99) , 
2, 0.0354679, 1, 0, 0.506107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494186,-99) , 
4, 178.074, 1, 0, 0.497086,-99) , 
6, 2.75191, 1, 0, 0.498599,-99) , 
6, 2.29006, 1, 0, 0.499506,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0169619);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491889,-99) , 
13, 0.475838, 0, 0, 0.507094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490604,-99) , 
2, -0.0663157, 0, 0, 0.496557,-99) , 
1, -0.0733886, 0, 0, 0.503002,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493245,-99) , 
2, 0.101325, 1, 0, 0.498793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484281,-99) , 
6, 3.94805, 1, 0, 0.497105,-99) , 
3, 190.517, 0, 0, 0.499763,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0108212);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0671717, 1, 1, 0.506316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496554,-99) , 
1, 0.24609, 0, 0, 0.498737,-99) , 
2, 0.242235, 0, 0, 0.500802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487718,-99) , 
2, 0.0827474, 1, 0, 0.494233,-99) , 
3, 146.305, 0, 0, 0.499834,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0109198);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.10263, 1, 1, 0.509989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490179,-99) , 
4, 184.217, 0, 0, 0.505229,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489853,-99) , 
2, 0.394458, 1, 0, 0.500303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481973,-99) , 
6, 4.21338, 1, 0, 0.498789,-99) , 
3, 234.729, 0, 0, 0.500335,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0136812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48147,-99) , 
7, 3.46893, 0, 0, 0.496534,-99) , 
7, 3.10263, 1, 0, 0.503812,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496141,-99) , 
1, 0.00210899, 1, 0, 0.49824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4847,-99) , 
6, 4.21338, 1, 0, 0.497122,-99) , 
3, 234.729, 0, 0, 0.498728,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0132187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497682,-99) , 
1, 0.303113, 0, 0, 0.499822,-99) , 
0, 79.9238, 1, 0, 0.501577,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494103,-99) , 
3, 324.924, 0, 0, 0.500298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485013,-99) , 
14, 0.284675, 1, 0, 0.495011,-99) , 
1, -0.0532355, 0, 0, 0.499663,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0138649);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.89255, 0, 1, 0.507773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495775,-99) , 
12, 0.47619, 1, 0, 0.49794,-99) , 
0, 111.357, 1, 0, 0.50287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495823,-99) , 
4, 224.655, 0, 0, 0.501811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488315,-99) , 
14, 0.284675, 1, 0, 0.497143,-99) , 
1, -0.0532355, 0, 0, 0.501201,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0102191);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498975,-99) , 
9, 0.285711, 0, 0, 0.507719,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497972,-99) , 
9, 0.28571, 0, 0, 0.508715,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495386,-99) , 
2, 0.0926628, 0, 0, 0.498467,-99) , 
6, 2.75191, 1, 0, 0.500185,-99) , 
6, 2.29006, 1, 0, 0.501212,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00696673);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499295,-99) , 
5, 2.34164, 1, 0, 0.50728,-99) , 
NN(
NN(
0, 
0, 
-1, 2.61996, 0, 1, 0.508374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492249,-99) , 
2, 0.317021, 1, 0, 0.498629,-99) , 
6, 2.75191, 1, 0, 0.500263,-99) , 
6, 2.29006, 1, 0, 0.501219,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.00752407);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499246,-99) , 
4, 161.8, 0, 0, 0.506935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499821,-99) , 
6, 2.61996, 0, 0, 0.506632,-99) , 
NN(
0, 
0, 
-1, 146.305, 0, -1, 0.497571,-99) , 
6, 2.75191, 1, 0, 0.49909,-99) , 
6, 2.29006, 1, 0, 0.500159,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.00469648);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 367.364, 0, 1, 0.502067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493676,-99) , 
0, 62.2753, 0, 0, 0.501514,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00851976);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.218609, 0, 1, 0.503768,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486063,-99) , 
5, 1.37735, 0, 0, 0.497234,-99) , 
3, 179.991, 0, 0, 0.501357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490448,-99) , 
2, 0.0827474, 1, 0, 0.495501,-99) , 
3, 146.305, 0, 0, 0.500494,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.015524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506449,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492651,-99) , 
13, 0.47619, 0, 0, 0.501996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490858,-99) , 
13, 0.47619, 1, 0, 0.495671,-99) , 
7, 3.17849, 0, 0, 0.49848,-99) , 
15, 0.276959, 0, 0, 0.499053,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00866284);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497652,-99) , 
10, 0.475838, 0, 0, 0.50456,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49731,-99) , 
9, 0.28571, 0, 0, 0.50518,-99) , 
NN(
0, 
0, 
-1, 0.285442, 1, -1, 0.496742,-99) , 
6, 2.75191, 1, 0, 0.498156,-99) , 
6, 2.29006, 1, 0, 0.499029,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.015025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516871,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499071,-99) , 
5, 1.13334, 1, 0, 0.50055,-99) , 
3, 323.883, 0, 0, 0.502217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511343,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482794,-99) , 
10, 0.965973, 0, 0, 0.490929,-99) , 
8, 0.965994, 0, 0, 0.497656,-99) , 
14, 0.285442, 1, 0, 0.500507,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0158814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498538,-99) , 
9, 0.285712, 0, 0, 0.502621,-99) , 
0, 154.622, 0, 0, 0.504039,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493285,-99) , 
10, 0.659543, 0, 0, 0.502535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480184,-99) , 
9, 0.358951, 0, 0, 0.497476,-99) , 
14, 0.285442, 1, 0, 0.501578,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0181281);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.092909, 0, 1, 0.511687,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494487,-99) , 
6, 3.43483, 1, 0, 0.503085,-99) , 
7, 3.70905, 0, 0, 0.504823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487099,-99) , 
10, 0.489602, 1, 0, 0.493601,-99) , 
9, 0.628479, 0, 0, 0.498305,-99) , 
14, 0.285442, 1, 0, 0.502379,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0113737);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514011,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493947,-99) , 
5, 1.49767, 0, 0, 0.500824,-99) , 
5, 0.857414, 1, 0, 0.502009,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495316,-99) , 
5, 2.36914, 1, 0, 0.502218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484105,-99) , 
14, 0.282161, 1, 0, 0.495981,-99) , 
1, -0.128067, 0, 0, 0.50073,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.00695842);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494822,-99) , 
10, 0.47619, 0, 0, 0.503984,-99) , 
NN(
0, 
0, 
-1, 3.2681, 1, -1, 0.498589,-99) , 
6, 3.4311, 0, 0, 0.500073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492158,-99) , 
4, 414.153, 1, 0, 0.499608,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0197909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497986,-99) , 
7, 3.00596, 1, 0, 0.507295,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484446,-99) , 
13, 0.725624, 0, 0, 0.500258,-99) , 
13, 0.47619, 1, 0, 0.501884,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496072,-99) , 
2, 0.092909, 0, 0, 0.505947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480143,-99) , 
14, 0.285023, 1, 0, 0.496432,-99) , 
7, 3.70572, 1, 0, 0.50079,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0207707);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.942859, 1, 1, 0.50996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49099,-99) , 
5, 1.36558, 0, 0, 0.50491,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479674,-99) , 
12, 0.285714, 0, 0, 0.506484,-99) , 
NN(
0, 
0, 
-1, 0.799266, 1, -1, 0.49157,-99) , 
13, 0.900227, 0, 0, 0.498414,-99) , 
13, 0.47619, 1, 0, 0.499926,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00546471);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507289,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490086,-99) , 
7, 2.12403, 0, 0, 0.500498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487987,-99) , 
4, 349.768, 1, 0, 0.49977,-99) , 
2, -0.356053, 1, 0, 0.500287,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0063138);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505923,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498895,-99) , 
4, 263.921, 0, 0, 0.500083,-99) , 
NN(
0, 
0, 
-1, 202.454, 1, -1, 0.494043,-99) , 
1, -0.10161, 0, 0, 0.498732,-99) , 
2, -0.356053, 1, 0, 0.499226,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0122528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490569,-99) , 
9, 0.285691, 1, 0, 0.504473,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492164,-99) , 
12, 0.865242, 0, 0, 0.508974,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485345,-99) , 
0, 90.4853, 0, 0, 0.498237,-99) , 
0, 75.4399, 1, 0, 0.4997,-99) , 
0, 154.428, 0, 0, 0.500374,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.015249);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493631,-99) , 
9, 0.285691, 1, 0, 0.50475,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493366,-99) , 
0, 61.3346, 0, 0, 0.50905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494869,-99) , 
4, 328.306, 0, 0, 0.496121,-99) , 
0, 75.4399, 1, 0, 0.497882,-99) , 
0, 154.428, 0, 0, 0.498852,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00913951);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 212.623, 0, 1, 0.504797,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497283,-99) , 
0, 164.301, 0, 0, 0.499565,-99) , 
0, 108.352, 1, 0, 0.501914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49104,-99) , 
4, 414.153, 1, 0, 0.501274,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00727385);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496678,-99) , 
7, 3.74862, 1, 0, 0.507105,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496814,-99) , 
1, -0.0732621, 0, 0, 0.500826,-99) , 
6, 4.00163, 0, 0, 0.501632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493324,-99) , 
4, 414.153, 1, 0, 0.501143,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0126048);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519041,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49491,-99) , 
1, -0.106688, 0, 0, 0.49979,-99) , 
2, 0.239741, 0, 0, 0.502736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510263,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49332,-99) , 
1, 0.21402, 0, 0, 0.497627,-99) , 
3, 234.729, 0, 0, 0.499091,-99) , 
1, 0.0215959, 1, 0, 0.500504,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00902989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498986,-99) , 
9, 0.285691, 1, 0, 0.506628,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494643,-99) , 
12, 0.865242, 0, 0, 0.508301,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491572,-99) , 
0, 98.0079, 0, 0, 0.497975,-99) , 
0, 75.4399, 1, 0, 0.499381,-99) , 
0, 154.428, 0, 0, 0.500405,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0148578);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48766,-99) , 
8, 0.47619, 0, 0, 0.500823,-99) , 
2, 0.239741, 0, 0, 0.502585,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485862,-99) , 
5, 1.5163, 0, 0, 0.502736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491872,-99) , 
5, 1.52281, 1, 0, 0.494639,-99) , 
0, 101.287, 1, 0, 0.496653,-99) , 
1, 0.0964274, 1, 0, 0.499652,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00952459);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498139,-99) , 
9, 0.285691, 1, 0, 0.504499,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493658,-99) , 
0, 61.3346, 0, 0, 0.505767,-99) , 
NN(
0, 
0, 
-1, 0.285712, 0, -1, 0.496812,-99) , 
0, 75.4399, 1, 0, 0.498031,-99) , 
0, 154.428, 0, 0, 0.498944,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00591715);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49753,-99) , 
10, 0.475838, 0, 0, 0.505088,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499597,-99) , 
2, 0.0354679, 1, 0, 0.505152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493441,-99) , 
4, 263.921, 1, 0, 0.499059,-99) , 
6, 2.75191, 1, 0, 0.500081,-99) , 
6, 2.29006, 1, 0, 0.500763,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00752118);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499009,-99) , 
10, 0.475838, 0, 0, 0.504902,-99) , 
NN(
NN(
0, 
0, 
-1, 2.61996, 0, 1, 0.505457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497113,-99) , 
5, 2.86456, 0, 0, 0.498154,-99) , 
6, 2.75191, 1, 0, 0.499379,-99) , 
6, 2.29006, 1, 0, 0.500132,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00662508);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498389,-99) , 
5, 2.34164, 1, 0, 0.504667,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490607,-99) , 
7, 2.4292, 0, 0, 0.500805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494307,-99) , 
7, 4.23604, 1, 0, 0.500146,-99) , 
6, 2.29006, 1, 0, 0.500762,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00763921);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499226,-99) , 
9, 0.285711, 0, 0, 0.504339,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498117,-99) , 
15, -9.48615, 1, 0, 0.499879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489009,-99) , 
10, 0.971429, 0, 0, 0.494833,-99) , 
8, 0.47619, 0, 0, 0.499107,-99) , 
6, 2.29006, 1, 0, 0.49982,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0100703);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494594,-99) , 
1, -0.201631, 0, 0, 0.503226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493877,-99) , 
7, 2.87721, 1, 0, 0.498215,-99) , 
7, 3.17849, 0, 0, 0.50044,-99) , 
15, 0.276959, 0, 0, 0.500864,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00859303);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 203.796, 1, 1, 0.504637,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488859,-99) , 
0, 121.581, 1, 0, 0.504191,-99) , 
NN(
0, 
0, 
-1, 4.21338, 1, -1, 0.497802,-99) , 
3, 234.729, 0, 0, 0.499351,-99) , 
0, 154.428, 0, 0, 0.500097,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00701228);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499471,-99) , 
13, 0.47619, 1, 0, 0.500768,-99) , 
0, 79.9238, 1, 0, 0.501933,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497884,-99) , 
6, 3.44153, 0, 0, 0.501381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490746,-99) , 
3, 171.732, 0, 0, 0.498739,-99) , 
1, -0.0532355, 0, 0, 0.501003,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00654428);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 161.8, 0, 1, 0.505638,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499993,-99) , 
8, 0.800454, 1, 0, 0.502409,-99) , 
NN(
0, 
0, 
-1, 1.85392, 0, -1, 0.494448,-99) , 
8, 0.47619, 0, 0, 0.501191,-99) , 
6, 2.29006, 1, 0, 0.501797,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0099655);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507418,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49175,-99) , 
2, 0.441669, 1, 0, 0.503718,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485962,-99) , 
4, 266.214, 1, 0, 0.498163,-99) , 
1, -0.0291833, 0, 0, 0.502022,-99) , 
2, -0.356053, 1, 0, 0.502394,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00730765);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496991,-99) , 
4, 417.22, 1, 0, 0.504194,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49933,-99) , 
6, 4.00511, 0, 0, 0.501196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492383,-99) , 
1, 0.120526, 0, 0, 0.497275,-99) , 
4, 159.678, 0, 0, 0.499979,-99) , 
4, 306.844, 0, 0, 0.500472,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00572037);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499647,-99) , 
5, 1.85825, 0, 0, 0.507592,-99) , 
NN(
0, 
0, 
-1, 4.23295, 0, 1, 0.501388,-99) , 
1, 0.320922, 0, 0, 0.502252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505077,-99) , 
NN(
0, 
0, 
-1, 0.229942, 1, -1, 0.495628,-99) , 
5, 2.61458, 0, 0, 0.498375,-99) , 
4, 156.612, 0, 0, 0.501303,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00740272);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49571,-99) , 
5, 1.85825, 0, 0, 0.506539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498383,-99) , 
5, 1.37824, 1, 0, 0.500075,-99) , 
1, 0.320922, 0, 0, 0.500931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494149,-99) , 
6, 4.57215, 1, 0, 0.500527,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00512309);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 306.844, 0, 1, 0.502228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494536,-99) , 
3, 345.259, 1, 0, 0.501651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495999,-99) , 
6, 4.57215, 1, 0, 0.501314,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
