// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Wed Sep 21 22:56:39 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_12/src/tHFCNC/NtupleAnalyzer/test/MVA
Training events: 85147
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB           HiggsMass_TOPHLEPBB                                             'D'    [17.2658157349,500]
TopHadMass_TOPTOPLEPHAD       TopHadMass_TOPTOPLEPHAD       TopHadMass_TOPTOPLEPHAD       TopHadMass_TOPTOPLEPHAD                                         'D'    [44.3978996277,1000]
MVA_TOPHLEPBB                 MVA_TOPHLEPBB                 MVA_TOPHLEPBB                 MVA_TOPHLEPBB                                                   'D'    [-0.664078474045,0.75155377388]
MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD                                                'D'    [-0.873886883259,0.676805019379]
LepCharge                     LepCharge                     LepCharge                     LepCharge                                                       'I'    [-1,1]
HiggsEta_TOPHLEPBB            HiggsEta_TOPHLEPBB            HiggsEta_TOPHLEPBB            HiggsEta_TOPHLEPBB                                              'D'    [-6.11002874374,6.76000976562]
TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB          TopLepMass_TOPHLEPBB                                            'D'    [85.5019836426,500]
TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD                                         'D'    [56.7179450989,500]
TopLepPt_TOPHLEPBB            TopLepPt_TOPHLEPBB            TopLepPt_TOPHLEPBB            TopLepPt_TOPHLEPBB                                              'D'    [0.412734508514,1000]
TopLepEta_TOPHLEPBB           TopLepEta_TOPHLEPBB           TopLepEta_TOPHLEPBB           TopLepEta_TOPHLEPBB                                             'D'    [-6.28940057755,6.57280778885]
HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB HiggsBJet1HiggsBJet2Dr_TOPHLEPBB                                      'D'    [0.399777770042,5.50272893906]
TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB       TopLepHiggsDr_TOPHLEPBB                                         'D'    [0.0144780697301,9.63595581055]
TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD                                     'D'    [0.0320357643068,9.97610759735]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsMass_TOPHLEPBB", "TopHadMass_TOPTOPLEPHAD", "MVA_TOPHLEPBB", "MVA_TOPTOPLEPHAD", "LepCharge", "HiggsEta_TOPHLEPBB", "TopLepMass_TOPHLEPBB", "TopLepMass_TOPTOPLEPHAD", "TopLepPt_TOPHLEPBB", "TopLepEta_TOPHLEPBB", "HiggsBJet1HiggsBJet2Dr_TOPHLEPBB", "TopLepHiggsDr_TOPHLEPBB", "TopLepTopHadDr_TOPTOPLEPHAD" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'I';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.464937020016919);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0784023, 0, 1, 0.805854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363291,-99) , 
3, 0.252746, 1, 0, 0.471484,-99) , 
1, 232.744, 0, 0, 0.62787,-99) , 
NN(
0, 
0, 
-1, 226.417, 0, -1, 0.236037,-99) , 
4, 0, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.361945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 191.297, 0, 1, 0.717935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388121,-99) , 
0, 158.915, 1, 0, 0.666517,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417646,-99) , 
8, 239.284, 0, 0, 0.45736,-99) , 
NN(
0, 
0, 
-1, 0.188855, 1, -1, 0.224628,-99) , 
4, 0, 0, 0, 0.373992,-99) , 
1, 226.417, 0, 0, 0.497483,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.259168);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 287.37, 0, 1, 0.758256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450096,-99) , 
2, 0.144854, 0, 0, 0.524145,-99) , 
1, 368.142, 0, 0, 0.57835,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370623,-99) , 
2, 0.281845, 0, 0, 0.433596,-99) , 
NN(
0, 
0, 
-1, 0.3528, 1, -1, 0.214947,-99) , 
3, 0.226964, 1, 0, 0.355804,-99) , 
4, 0, 0, 0, 0.508712,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.199721);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47985,-99) , 
2, 0.0563392, 0, 0, 0.590625,-99) , 
8, 287.1, 0, 0, 0.653882,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472773,-99) , 
11, 2.52623, 1, 0, 0.498533,-99) , 
NN(
0, 
0, 
-1, 0.341394, 1, -1, 0.347065,-99) , 
4, 0, 0, 0, 0.448981,-99) , 
1, 317.427, 0, 0, 0.500754,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.171977);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0342257, 1, 1, 0.72601,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478485,-99) , 
10, 1.79307, 1, 0, 0.53612,-99) , 
NN(
0, 
0, 
-1, 0.257929, 1, -1, 0.40552,-99) , 
4, 0, 0, 0, 0.494744,-99) , 
1, 499.447, 0, 0, 0.519215,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.169022);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777059,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414398,-99) , 
0, 87.9248, 0, 0, 0.56479,-99) , 
8, 381.208, 0, 0, 0.586307,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426405,-99) , 
4, 0, 0, 0, 0.494139,-99) , 
NN(
0, 
0, 
-1, 110.252, 0, -1, 0.363287,-99) , 
3, 0.395501, 1, 0, 0.465233,-99) , 
3, 0.0860652, 1, 0, 0.525732,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.122079);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.683738,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476691,-99) , 
10, 1.37177, 1, 0, 0.507314,-99) , 
NN(
0, 
0, 
-1, 73.0915, 0, -1, 0.399755,-99) , 
0, 86.2278, 0, 0, 0.492503,-99) , 
1, 544.951, 0, 0, 0.508162,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.11152);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722342,-99) , 
NN(
NN(
0, 
0, 
-1, 3.05892, 1, 1, 0.555489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462653,-99) , 
5, 1.35745, 0, 0, 0.482373,-99) , 
3, 0.0122228, 1, 0, 0.510263,-99) , 
8, 428.807, 0, 0, 0.521152,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.111652);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665281,-99) , 
NN(
NN(
0, 
0, 
-1, 2.34536, 1, 1, 0.572187,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459571,-99) , 
5, 1.0693, 0, 0, 0.487189,-99) , 
5, -1.20716, 1, 0, 0.507048,-99) , 
8, 381.208, 0, 0, 0.519056,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.12663);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712734,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48062,-99) , 
10, 2.1779, 1, 0, 0.507059,-99) , 
8, 191.937, 0, 0, 0.592631,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445454,-99) , 
0, 102.647, 0, 0, 0.511081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408769,-99) , 
0, 155.19, 1, 0, 0.498458,-99) , 
11, 2.30531, 1, 0, 0.516475,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.061138);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633576,-99) , 
NN(
NN(
0, 
0, 
-1, -1.73519, 1, 1, 0.513097,-99) , 
NN(
0, 
0, 
-1, 2.11023, 1, -1, 0.428356,-99) , 
11, 3.6798, 1, 0, 0.499785,-99) , 
8, 381.208, 0, 0, 0.509688,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0994259);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61927,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476076,-99) , 
0, 110.31, 0, 0, 0.506384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405443,-99) , 
10, 1.61477, 1, 0, 0.439461,-99) , 
0, 132.203, 1, 0, 0.489291,-99) , 
8, 381.208, 0, 0, 0.498851,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0776505);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620585,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457711,-99) , 
0, 132.203, 1, 0, 0.504128,-99) , 
NN(
0, 
0, 
-1, 0.463545, 1, -1, 0.413557,-99) , 
3, 0.396901, 1, 0, 0.493671,-99) , 
1, 590.456, 0, 0, 0.501422,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0670897);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 280.413, 0, 1, 0.573492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456055,-99) , 
7, 183.37, 0, 0, 0.476716,-99) , 
5, -1.82002, 1, 0, 0.484895,-99) , 
8, 333.608, 0, 0, 0.494736,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0947925);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654934,-99) , 
NN(
0, 
0, 
-1, 101.397, 0, -1, 0.480076,-99) , 
8, 191.937, 0, 0, 0.550345,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477037,-99) , 
5, -1.22722, 1, 0, 0.497066,-99) , 
NN(
0, 
0, 
-1, 0.300354, 1, -1, 0.440498,-99) , 
4, 0, 0, 0, 0.479323,-99) , 
11, 2.30531, 1, 0, 0.492741,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0425961);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601495,-99) , 
NN(
NN(
0, 
0, 
-1, 1.8399, 0, 1, 0.510502,-99) , 
NN(
0, 
0, 
-1, 0, 0, -1, 0.460496,-99) , 
10, 2.58676, 1, 0, 0.500776,-99) , 
1, 590.456, 0, 0, 0.506844,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0522732);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.72243, 1, 1, 0.569232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467073,-99) , 
10, 2.34386, 1, 0, 0.494031,-99) , 
8, 286.009, 0, 0, 0.505946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404079,-99) , 
3, 0.455278, 1, 0, 0.500089,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0740368);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617031,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473152,-99) , 
10, 2.1779, 0, 0, 0.495918,-99) , 
8, 191.937, 0, 0, 0.543859,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485023,-99) , 
5, 1.82453, 0, 0, 0.497242,-99) , 
NN(
0, 
0, 
-1, 0.300354, 1, -1, 0.451889,-99) , 
4, 0, 0, 0, 0.48303,-99) , 
11, 2.30531, 1, 0, 0.494468,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0613793);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587479,-99) , 
NN(
NN(
0, 
0, 
-1, 143.211, 0, 1, 0.552973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46606,-99) , 
1, 190.503, 0, 0, 0.493745,-99) , 
1, 148.402, 1, 0, 0.500603,-99) , 
1, 590.456, 0, 0, 0.505796,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0685393);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48957,-99) , 
3, 0.244811, 0, 0, 0.506231,-99) , 
8, 381.58, 0, 0, 0.513987,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455322,-99) , 
1, 226.417, 1, 0, 0.492955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407471,-99) , 
3, 0.300354, 1, 0, 0.474181,-99) , 
4, 0, 0, 0, 0.501693,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0515254);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 548.673, 0, 1, 0.519217,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437117,-99) , 
0, 93.8867, 0, 0, 0.495503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424379,-99) , 
0, 132.203, 1, 0, 0.477628,-99) , 
4, 0, 0, 0, 0.506386,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0375239);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536448,-99) , 
NN(
0, 
0, 
-1, 0.40527, 1, -1, 0.487133,-99) , 
5, -1.82002, 1, 0, 0.49226,-99) , 
1, 590.456, 0, 0, 0.497062,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.038477);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.72243, 1, 1, 0.551244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456818,-99) , 
11, 3.89609, 1, 0, 0.499625,-99) , 
8, 286.009, 0, 0, 0.507728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433148,-99) , 
3, 0.455278, 1, 0, 0.503497,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0464536);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4462,-99) , 
0, 145.34, 1, 0, 0.49556,-99) , 
10, 0.885773, 1, 0, 0.502927,-99) , 
NN(
0, 
0, 
-1, 73.0915, 0, -1, 0.456373,-99) , 
0, 86.2278, 0, 0, 0.496782,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0448033);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55295,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471513,-99) , 
5, -0.798587, 1, 0, 0.482256,-99) , 
5, 1.85714, 0, 0, 0.487597,-99) , 
1, 590.456, 0, 0, 0.491445,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0558447);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595498,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444747,-99) , 
3, 0.381435, 1, 0, 0.495885,-99) , 
11, 1.86559, 1, 0, 0.50553,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46775,-99) , 
1, 174.403, 0, 0, 0.487758,-99) , 
NN(
0, 
0, 
-1, 3.05892, 1, -1, 0.441898,-99) , 
1, 226.417, 1, 0, 0.473664,-99) , 
8, 143.211, 0, 0, 0.492402,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0566426);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492853,-99) , 
1, 194.772, 0, 0, 0.528902,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461255,-99) , 
4, 0, 0, 0, 0.502194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464598,-99) , 
5, -1.61583, 1, 0, 0.47368,-99) , 
5, 0.63142, 0, 0, 0.484463,-99) , 
11, 1.84714, 1, 0, 0.489143,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0615417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596077,-99) , 
NN(
0, 
0, 
-1, 190.311, 1, -1, 0.454057,-99) , 
0, 108.069, 0, 0, 0.517008,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485901,-99) , 
5, 1.83118, 0, 0, 0.490616,-99) , 
NN(
0, 
0, 
-1, 187.017, 0, -1, 0.455095,-99) , 
11, 3.6798, 1, 0, 0.484736,-99) , 
10, 1.12877, 1, 0, 0.491528,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0376288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 194.772, 0, 1, 0.538569,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47848,-99) , 
6, 289.462, 1, 0, 0.514535,-99) , 
NN(
0, 
0, 
-1, 3.70589, 1, -1, 0.487207,-99) , 
6, 184.192, 0, 0, 0.497687,-99) , 
11, 1.84714, 1, 0, 0.501994,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0344636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 113.777, 0, 1, 0.53052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572394,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470583,-99) , 
12, 2.9138, 0, 0, 0.492348,-99) , 
1, 142.479, 1, 0, 0.498635,-99) , 
7, 246.696, 0, 0, 0.504147,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0443579);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457296,-99) , 
2, 0.0174048, 0, 0, 0.49999,-99) , 
8, 287.003, 0, 0, 0.516054,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487049,-99) , 
8, 240.23, 1, 0, 0.507913,-99) , 
NN(
0, 
0, 
-1, 368.142, 1, -1, 0.481192,-99) , 
11, 3.09075, 1, 0, 0.490517,-99) , 
11, 2.76347, 1, 0, 0.499361,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0309474);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566753,-99) , 
NN(
0, 
0, 
-1, 87.3254, 0, -1, 0.491234,-99) , 
1, 142.479, 1, 0, 0.497121,-99) , 
7, 331.131, 0, 0, 0.500524,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0395276);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49732,-99) , 
5, -1.06559, 1, 0, 0.507656,-99) , 
5, 1.46761, 0, 0, 0.514268,-99) , 
NN(
NN(
0, 
0, 
-1, 144.344, 0, 1, 0.515996,-99) , 
NN(
0, 
0, 
-1, 127.32, 1, -1, 0.470566,-99) , 
2, 0.144854, 1, 0, 0.490825,-99) , 
10, 2.10076, 1, 0, 0.50598,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0463219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.90602, 1, 1, 0.522302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472968,-99) , 
2, -0.052589, 0, 0, 0.517184,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48895,-99) , 
3, 0.303007, 0, 0, 0.502807,-99) , 
NN(
0, 
0, 
-1, 121.23, 1, -1, 0.468435,-99) , 
4, 0, 0, 0, 0.491886,-99) , 
10, 2.10076, 1, 0, 0.508241,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0281751);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.72243, 1, 1, 0.535716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495784,-99) , 
3, 0.265524, 0, 0, 0.502286,-99) , 
8, 286.009, 0, 0, 0.50748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46707,-99) , 
3, 0.455278, 1, 0, 0.505209,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0375382);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499634,-99) , 
8, 240.165, 1, 0, 0.527542,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561278,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480813,-99) , 
1, 183.317, 0, 0, 0.498523,-99) , 
1, 142.479, 1, 0, 0.503438,-99) , 
7, 246.696, 0, 0, 0.507604,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0236826);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 113.777, 0, 1, 0.525605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462569,-99) , 
0, 87.3254, 0, 0, 0.496262,-99) , 
1, 142.479, 1, 0, 0.500621,-99) , 
7, 246.696, 0, 0, 0.504938,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0365233);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466199,-99) , 
0, 89.9084, 0, 0, 0.525828,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46023,-99) , 
10, 2.98008, 1, 0, 0.503393,-99) , 
NN(
0, 
0, 
-1, 0.0443656, 1, -1, 0.464233,-99) , 
0, 143.798, 1, 0, 0.496859,-99) , 
10, 0.885773, 1, 0, 0.500109,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0420408);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475298,-99) , 
0, 89.9084, 0, 0, 0.525059,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473916,-99) , 
4, 0, 0, 0, 0.504588,-99) , 
NN(
0, 
0, 
-1, 136.666, 1, -1, 0.484103,-99) , 
2, 0.144854, 1, 0, 0.491831,-99) , 
10, 0.885773, 1, 0, 0.495554,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0296146);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485792,-99) , 
0, 89.9084, 0, 0, 0.524169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457891,-99) , 
0, 80.1901, 0, 0, 0.501845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410604,-99) , 
2, 0.0443656, 1, 0, 0.471756,-99) , 
0, 143.798, 1, 0, 0.496837,-99) , 
10, 0.885773, 1, 0, 0.499896,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0242444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493192,-99) , 
0, 89.9084, 0, 0, 0.523541,-99) , 
NN(
NN(
0, 
0, 
-1, -0.0174394, 0, -1, 0.495469,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427644,-99) , 
0, 177.722, 0, 0, 0.469436,-99) , 
0, 143.798, 1, 0, 0.491139,-99) , 
10, 0.885773, 1, 0, 0.494763,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0240447);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 235.293, 0, 1, 0.529373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459378,-99) , 
0, 143.798, 1, 0, 0.498345,-99) , 
10, 0.885773, 1, 0, 0.501834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468958,-99) , 
2, -0.12479, 0, 0, 0.499129,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0343905);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489918,-99) , 
0, 113.777, 0, 0, 0.513886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543758,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479201,-99) , 
5, 0.757162, 0, 0, 0.486931,-99) , 
1, 142.479, 1, 0, 0.491373,-99) , 
7, 246.696, 0, 0, 0.495257,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0237534);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49755,-99) , 
0, 89.9084, 0, 0, 0.520033,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484463,-99) , 
1, 226.417, 1, 0, 0.497129,-99) , 
NN(
0, 
0, 
-1, 0.0443656, 1, -1, 0.47464,-99) , 
0, 143.798, 1, 0, 0.493393,-99) , 
10, 0.885773, 1, 0, 0.496368,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0219601);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 235.293, 0, 1, 0.519528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523732,-99) , 
NN(
0, 
0, 
-1, 146.963, 1, -1, 0.490921,-99) , 
0, 232.849, 0, 0, 0.49277,-99) , 
10, 0.885773, 1, 0, 0.495757,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0252913);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499174,-99) , 
8, 190.81, 0, 0, 0.508299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469854,-99) , 
6, 308.26, 1, 0, 0.504946,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508931,-99) , 
NN(
0, 
0, 
-1, 191.594, 1, -1, 0.482067,-99) , 
1, 271.922, 0, 0, 0.489368,-99) , 
6, 164.454, 0, 0, 0.499471,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0266217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 192.675, 1, 1, 0.525862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483895,-99) , 
5, 0.881976, 0, 0, 0.498977,-99) , 
9, -0.164539, 1, 0, 0.512102,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497334,-99) , 
11, 1.85278, 1, 0, 0.50107,-99) , 
NN(
0, 
0, 
-1, 144.575, 0, -1, 0.478132,-99) , 
12, 2.66181, 0, 0, 0.496801,-99) , 
7, 204.479, 0, 0, 0.501561,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0286813);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483155,-99) , 
6, 292.281, 1, 0, 0.512977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485254,-99) , 
3, 0.165377, 1, 0, 0.497571,-99) , 
6, 164.454, 0, 0, 0.507588,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472323,-99) , 
3, 0.0885792, 0, 0, 0.487515,-99) , 
12, 3.82025, 1, 0, 0.504808,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.032398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486419,-99) , 
11, 2.30531, 0, 0, 0.517599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478481,-99) , 
1, 362.932, 1, 0, 0.508588,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499162,-99) , 
1, 458.408, 0, 0, 0.503865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421375,-99) , 
0, 140.373, 1, 0, 0.496879,-99) , 
2, 0.144854, 1, 0, 0.501308,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0333567);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 287.003, 0, 1, 0.51816,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471239,-99) , 
8, 238.41, 1, 0, 0.500901,-99) , 
11, 2.78135, 1, 0, 0.506968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483686,-99) , 
2, -0.12479, 0, 0, 0.505056,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0181996);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495303,-99) , 
8, 240.165, 1, 0, 0.516507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535935,-99) , 
NN(
0, 
0, 
-1, 1.05101, 1, -1, 0.49507,-99) , 
1, 142.479, 1, 0, 0.498261,-99) , 
7, 267.805, 0, 0, 0.500678,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0244747);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 408.437, 0, 1, 0.510753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480694,-99) , 
7, 193.61, 0, 0, 0.492711,-99) , 
12, 2.73788, 0, 0, 0.506381,-99) , 
NN(
0, 
0, 
-1, 0.836815, 1, -1, 0.488645,-99) , 
12, 3.82025, 1, 0, 0.503924,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0151878);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499338,-99) , 
11, 1.74528, 1, 0, 0.501236,-99) , 
5, -1.83757, 1, 0, 0.503923,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514226,-99) , 
NN(
0, 
0, 
-1, 0.463229, 1, -1, 0.480472,-99) , 
5, 1.47075, 0, 0, 0.489915,-99) , 
9, 1.06043, 1, 0, 0.501138,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.023579);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.98699, 1, 1, 0.510413,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488346,-99) , 
3, 0.255827, 0, 0, 0.497303,-99) , 
7, 162.261, 0, 0, 0.506295,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510431,-99) , 
NN(
0, 
0, 
-1, 0.463229, 1, -1, 0.484264,-99) , 
5, 1.47075, 0, 0, 0.491585,-99) , 
9, 1.06043, 1, 0, 0.50337,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0152256);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497499,-99) , 
5, -2.07001, 1, 0, 0.500018,-99) , 
5, 2.09156, 0, 0, 0.50246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481427,-99) , 
10, 3.07275, 1, 0, 0.501142,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0298906);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 286.439, 0, 1, 0.512546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47747,-99) , 
0, 90.6976, 0, 0, 0.508288,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439874,-99) , 
8, 239.284, 1, 0, 0.489002,-99) , 
1, 141.908, 1, 0, 0.497837,-99) , 
1, 180.912, 0, 0, 0.504118,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0168033);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 235.293, 0, 1, 0.516033,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46874,-99) , 
10, 2.98008, 1, 0, 0.499269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435837,-99) , 
2, 0.0443656, 1, 0, 0.482567,-99) , 
0, 143.798, 1, 0, 0.496495,-99) , 
10, 0.885773, 1, 0, 0.498672,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0187139);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49821,-99) , 
1, 235.293, 0, 0, 0.511836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518477,-99) , 
NN(
0, 
0, 
-1, 146.963, 1, -1, 0.491753,-99) , 
0, 232.849, 0, 0, 0.493261,-99) , 
10, 0.885773, 1, 0, 0.49533,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0306031);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443112,-99) , 
1, 235.439, 0, 0, 0.478563,-99) , 
11, 2.71885, 1, 0, 0.509728,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487529,-99) , 
1, 226.417, 1, 0, 0.498793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467946,-99) , 
10, 3.07283, 1, 0, 0.496876,-99) , 
8, 286.009, 0, 0, 0.49901,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.03697);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495935,-99) , 
1, 297.925, 0, 0, 0.513287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466661,-99) , 
1, 336.929, 1, 0, 0.492347,-99) , 
11, 3.03815, 1, 0, 0.503443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525688,-99) , 
NN(
0, 
0, 
-1, 0.265622, 0, -1, 0.479911,-99) , 
1, 141.908, 1, 0, 0.488186,-99) , 
1, 180.912, 0, 0, 0.497354,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0359614);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.29008, 1, 1, 0.517933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446938,-99) , 
5, -1.3189, 0, 0, 0.477415,-99) , 
4, 0, 0, 0, 0.505711,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53096,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484066,-99) , 
4, 0, 1, 0, 0.492145,-99) , 
5, 2.20737, 0, 0, 0.495562,-99) , 
5, -0.594298, 1, 0, 0.499262,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0409182);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.144854, 1, 1, 0.52461,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447951,-99) , 
3, 0.134005, 1, 0, 0.492778,-99) , 
3, 0.238438, 0, 0, 0.502144,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481374,-99) , 
3, 0.0766601, 0, 0, 0.500542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452071,-99) , 
3, 0.300354, 1, 0, 0.490081,-99) , 
4, 0, 0, 0, 0.498395,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0290384);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464924,-99) , 
8, 144.404, 0, 0, 0.510794,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491631,-99) , 
0, 201.165, 0, 0, 0.493539,-99) , 
11, 1.97804, 1, 0, 0.495822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476611,-99) , 
11, 4.13797, 1, 0, 0.494517,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.017372);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 89.9084, 0, 1, 0.513106,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472112,-99) , 
0, 80.1901, 0, 0, 0.501995,-99) , 
NN(
0, 
0, 
-1, 0.0443656, 1, -1, 0.480451,-99) , 
0, 143.798, 1, 0, 0.498418,-99) , 
10, 0.885773, 1, 0, 0.500053,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0313975);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488621,-99) , 
0, 113.437, 0, 0, 0.50771,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472399,-99) , 
3, 0.262423, 0, 0, 0.491715,-99) , 
1, 187.612, 0, 0, 0.500736,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48917,-99) , 
3, 0.267155, 0, 0, 0.495486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478588,-99) , 
7, 204.479, 1, 0, 0.49135,-99) , 
6, 164.454, 0, 0, 0.497437,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0427843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544865,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442733,-99) , 
2, 0.173753, 1, 0, 0.47813,-99) , 
0, 108.069, 0, 0, 0.507337,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488319,-99) , 
10, 1.75942, 0, 0, 0.511774,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483847,-99) , 
10, 1.54535, 1, 0, 0.489413,-99) , 
0, 105.075, 1, 0, 0.495564,-99) , 
10, 1.12877, 1, 0, 0.498013,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.013881);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.21418, 0, 1, 0.510503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476778,-99) , 
11, 3.6953, 1, 0, 0.498329,-99) , 
6, 188.89, 0, 0, 0.501813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483928,-99) , 
6, 282.882, 1, 0, 0.500488,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.014342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518661,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48738,-99) , 
10, 1.61477, 0, 0, 0.495044,-99) , 
1, 142.479, 1, 0, 0.496876,-99) , 
7, 331.131, 0, 0, 0.49814,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.029156);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.353899, 0, 1, 0.511131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4775,-99) , 
2, 0.145309, 1, 0, 0.489132,-99) , 
11, 3.03815, 1, 0, 0.500785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517747,-99) , 
NN(
0, 
0, 
-1, 239.284, 1, -1, 0.485836,-99) , 
1, 141.908, 1, 0, 0.491603,-99) , 
1, 180.912, 0, 0, 0.49712,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00997732);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518343,-99) , 
NN(
0, 
0, 
-1, -0.208769, 0, -1, 0.49706,-99) , 
7, 331.131, 0, 0, 0.498476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483605,-99) , 
2, -0.12479, 0, 0, 0.49725,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0128065);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.21418, 0, 1, 0.506583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483468,-99) , 
0, 133.577, 1, 0, 0.496814,-99) , 
6, 179.491, 0, 0, 0.500623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48466,-99) , 
6, 282.882, 1, 0, 0.49944,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0189883);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0429815, 0, 1, 0.511924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494662,-99) , 
1, 368.142, 0, 0, 0.497895,-99) , 
6, 204.159, 0, 0, 0.501551,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481541,-99) , 
0, 135.013, 1, 0, 0.498069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466979,-99) , 
6, 223.668, 1, 0, 0.493354,-99) , 
9, -0.164539, 1, 0, 0.497621,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0299804);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480252,-99) , 
4, 0, 0, 0, 0.510614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481577,-99) , 
1, 187.612, 0, 0, 0.499085,-99) , 
3, 0.234018, 0, 0, 0.502681,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485889,-99) , 
10, 2.02539, 1, 0, 0.508598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479579,-99) , 
4, 0, 1, 0, 0.48663,-99) , 
5, 1.43462, 0, 0, 0.491993,-99) , 
9, -0.164539, 1, 0, 0.497557,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0264302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465474,-99) , 
8, 239.284, 1, 0, 0.496702,-99) , 
1, 232.744, 0, 0, 0.500492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512483,-99) , 
NN(
0, 
0, 
-1, 113.437, 0, -1, 0.484745,-99) , 
1, 226.417, 1, 0, 0.491133,-99) , 
3, 0.0122228, 0, 0, 0.4969,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0255924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48898,-99) , 
8, 240.165, 1, 0, 0.507076,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487633,-99) , 
11, 2.90276, 1, 0, 0.501417,-99) , 
NN(
0, 
0, 
-1, 324.292, 1, -1, 0.489431,-99) , 
8, 190.81, 0, 0, 0.493844,-99) , 
7, 267.805, 0, 0, 0.495592,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0206145);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513957,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463329,-99) , 
0, 72.1355, 0, 0, 0.502118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463823,-99) , 
0, 145.296, 1, 0, 0.498362,-99) , 
0, 224.152, 0, 0, 0.499191,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0249969);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489141,-99) , 
5, -1.20716, 0, 0, 0.507888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469776,-99) , 
1, 368.142, 1, 0, 0.500858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51359,-99) , 
NN(
0, 
0, 
-1, 0.151752, 1, -1, 0.489609,-99) , 
1, 408.437, 0, 0, 0.493134,-99) , 
11, 3.22164, 0, 0, 0.495612,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0126126);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497498,-99) , 
1, 271.922, 0, 0, 0.500675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479702,-99) , 
11, 4.15227, 1, 0, 0.499348,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474407,-99) , 
10, 1.54964, 1, 0, 0.488888,-99) , 
6, 243.406, 1, 0, 0.498072,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0235188);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484848,-99) , 
8, 238.41, 1, 0, 0.499745,-99) , 
1, 278.414, 0, 0, 0.50186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489296,-99) , 
2, 0.287623, 0, 0, 0.508427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469576,-99) , 
8, 192.047, 0, 0, 0.491098,-99) , 
1, 317.427, 1, 0, 0.499318,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0226949);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467829,-99) , 
8, 354.014, 1, 0, 0.48555,-99) , 
11, 2.71885, 1, 0, 0.507442,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494061,-99) , 
10, 1.37304, 1, 0, 0.497597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473541,-99) , 
11, 1.84714, 0, 0, 0.49525,-99) , 
8, 286.009, 0, 0, 0.497265,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0159843);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516131,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466724,-99) , 
0, 72.1355, 0, 0, 0.500865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474066,-99) , 
0, 145.296, 1, 0, 0.498239,-99) , 
0, 224.152, 0, 0, 0.499191,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0204312);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510437,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493502,-99) , 
0, 128.912, 0, 0, 0.497695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454421,-99) , 
0, 147.521, 1, 0, 0.495189,-99) , 
0, 178.177, 0, 0, 0.496415,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0282564);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.144854, 1, 1, 0.517198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477732,-99) , 
4, 0, 0, 0, 0.504635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48752,-99) , 
4, 0, 1, 0, 0.493715,-99) , 
2, 0.483149, 0, 0, 0.496382,-99) , 
3, 0.23375, 0, 0, 0.498883,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0335125);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481923,-99) , 
11, 2.51333, 0, 0, 0.515898,-99) , 
NN(
0, 
0, 
-1, 144.404, 1, -1, 0.480268,-99) , 
4, 0, 0, 0, 0.50503,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482521,-99) , 
2, 0.202643, 0, 0, 0.50081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442549,-99) , 
0, 140.373, 1, 0, 0.495925,-99) , 
2, 0.144854, 1, 0, 0.499377,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0298935);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488561,-99) , 
4, 0, 0, 0, 0.511925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484122,-99) , 
1, 362.932, 1, 0, 0.505506,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492211,-99) , 
11, 2.04055, 1, 0, 0.495609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450832,-99) , 
0, 140.373, 1, 0, 0.491861,-99) , 
2, 0.144854, 1, 0, 0.497032,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0283958);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489648,-99) , 
11, 2.30531, 0, 0, 0.506663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472191,-99) , 
1, 499.447, 1, 0, 0.503404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532211,-99) , 
NN(
0, 
0, 
-1, 0.381435, 1, -1, 0.487537,-99) , 
11, 2.76015, 1, 0, 0.495516,-99) , 
2, 0.279676, 1, 0, 0.500614,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0176257);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483936,-99) , 
8, 144.404, 0, 0, 0.511853,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49776,-99) , 
2, -0.053661, 1, 0, 0.499581,-99) , 
11, 2.32438, 1, 0, 0.501944,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479283,-99) , 
0, 111.773, 1, 0, 0.490293,-99) , 
6, 243.406, 1, 0, 0.500524,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0133061);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.74795, 1, 1, 0.505969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489499,-99) , 
11, 4.15227, 1, 0, 0.504925,-99) , 
NN(
0, 
0, 
-1, -0.201046, 1, -1, 0.490489,-99) , 
6, 243.406, 1, 0, 0.503166,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0190234);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487741,-99) , 
8, 144.404, 0, 0, 0.510873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494716,-99) , 
8, 143.211, 1, 0, 0.499966,-99) , 
11, 2.32438, 1, 0, 0.502029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489793,-99) , 
2, -0.12479, 0, 0, 0.50102,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0105905);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516955,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498611,-99) , 
5, 0.63142, 0, 0, 0.502335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490043,-99) , 
9, 1.67292, 1, 0, 0.501243,-99) , 
7, 373.348, 0, 0, 0.502096,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0329174);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513368,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472771,-99) , 
5, 1.04009, 1, 0, 0.508154,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488745,-99) , 
5, 1.02245, 0, 0, 0.498532,-99) , 
4, 0, 1, 0, 0.501575,-99) , 
5, -1.82002, 1, 0, 0.502803,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0146542);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.254177, 0, 1, 0.513075,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498944,-99) , 
5, -0.471975, 1, 0, 0.503211,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47961,-99) , 
3, 0.0801838, 0, 0, 0.491622,-99) , 
6, 223.668, 1, 0, 0.501371,-99) , 
10, 0.885773, 1, 0, 0.502668,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0117805);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492755,-99) , 
5, -1.20716, 0, 0, 0.50047,-99) , 
10, 0.885773, 1, 0, 0.502048,-99) , 
8, 381.208, 0, 0, 0.502972,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0116015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495588,-99) , 
9, -0.777026, 1, 0, 0.498933,-99) , 
10, 0.885773, 1, 0, 0.500375,-99) , 
8, 381.208, 0, 0, 0.501213,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0348394);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499361,-99) , 
1, 232.744, 0, 0, 0.512623,-99) , 
NN(
0, 
0, 
-1, 0.00679375, 0, -1, 0.482569,-99) , 
4, 0, 0, 0, 0.50383,-99) , 
NN(
NN(
0, 
0, 
-1, 0.192933, 1, 1, 0.516193,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476403,-99) , 
3, 0.27055, 0, 0, 0.488405,-99) , 
4, 0, 1, 0, 0.497798,-99) , 
8, 143.211, 0, 0, 0.501328,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0255163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.30165, 0, 1, 0.513306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465263,-99) , 
3, 0.00679375, 0, 0, 0.491272,-99) , 
4, 0, 0, 0, 0.506861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516117,-99) , 
NN(
0, 
0, 
-1, 1.57189, 0, -1, 0.491789,-99) , 
7, 204.479, 0, 0, 0.497835,-99) , 
8, 143.211, 0, 0, 0.503118,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0182046);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496347,-99) , 
10, 1.3358, 0, 0, 0.504349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48262,-99) , 
11, 4.15227, 1, 0, 0.502989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480812,-99) , 
10, 1.31998, 1, 0, 0.494332,-99) , 
6, 223.668, 1, 0, 0.501545,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0111899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528301,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497712,-99) , 
5, -2.07001, 1, 0, 0.499536,-99) , 
5, 2.09156, 0, 0, 0.50127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490216,-99) , 
10, 3.07275, 1, 0, 0.500576,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00812486);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513851,-99) , 
NN(
NN(
0, 
0, 
-1, 142.479, 1, 1, 0.503008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489366,-99) , 
3, -0.283147, 0, 0, 0.502127,-99) , 
7, 373.348, 0, 0, 0.502763,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00966219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496782,-99) , 
3, -0.230202, 1, 0, 0.507914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492678,-99) , 
10, 1.37177, 0, 0, 0.49854,-99) , 
1, 142.479, 1, 0, 0.499927,-99) , 
7, 267.805, 0, 0, 0.50098,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
