// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Tue Feb 14 13:49:39 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_25/src/tHFCNC/NtupleAnalyzer/test/MVA
Training events: 1666259
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
HiggsMass_TOPTOPLEPHBB        HiggsMass_TOPTOPLEPHBB        HiggsMass_TOPTOPLEPHBB        HiggsMass_TOPTOPLEPHBB                                          'D'    [16.745973587,500]
MVA_TOPTOPLEPHBB              MVA_TOPTOPLEPHBB              MVA_TOPTOPLEPHBB              MVA_TOPTOPLEPHBB                                                'D'    [-0.838059604168,0.618747830391]
MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD              MVA_TOPTOPLEPHAD                                                'D'    [-0.840806245804,0.767355918884]
TopLepMass_TOPTOPLEPHBB       TopLepMass_TOPTOPLEPHBB       TopLepMass_TOPTOPLEPHBB       TopLepMass_TOPTOPLEPHBB                                         'D'    [42.1121902466,500]
TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD       TopLepMass_TOPTOPLEPHAD                                         'D'    [41.0960121155,500]
HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB                                         'D'    [0.390216380358,5.61477994919]
TopLepHiggsDr_TOPTOPLEPHBB    TopLepHiggsDr_TOPTOPLEPHBB    TopLepHiggsDr_TOPTOPLEPHBB    TopLepHiggsDr_TOPTOPLEPHBB                                      'D'    [0.00492225214839,10.5506839752]
TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD   TopLepTopHadDr_TOPTOPLEPHAD                                     'D'    [0.023369025439,10.3938074112]
HiggsBJet1CSVv2_TOPTOPLEPHBB  HiggsBJet1CSVv2_TOPTOPLEPHBB  HiggsBJet1CSVv2_TOPTOPLEPHBB  HiggsBJet1CSVv2_TOPTOPLEPHBB                                    'D'    [0.803491234779,1]
HiggsBJet2CSVv2_TOPTOPLEPHBB  HiggsBJet2CSVv2_TOPTOPLEPHBB  HiggsBJet2CSVv2_TOPTOPLEPHBB  HiggsBJet2CSVv2_TOPTOPLEPHBB                                    'D'    [-10,0.999437987804]
TopLepBJetCSVv2_TOPTOPLEPHBB  TopLepBJetCSVv2_TOPTOPLEPHBB  TopLepBJetCSVv2_TOPTOPLEPHBB  TopLepBJetCSVv2_TOPTOPLEPHBB                                    'D'    [-10,1]
TopHadNonBJetCSVv2_TOPTOPLEPHBB TopHadNonBJetCSVv2_TOPTOPLEPHBB TopHadNonBJetCSVv2_TOPTOPLEPHBB TopHadNonBJetCSVv2_TOPTOPLEPHBB                                     'D'    [-10,0.846882283688]
TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD  TopLepBJetCSVv2_TOPTOPLEPHAD                                    'D'    [0.80000680685,1]
TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD  TopHadBJetCSVv2_TOPTOPLEPHAD                                    'D'    [0.80000603199,1]
TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD TopHadWNonBJet1CSVv2_TOPTOPLEPHAD                                       'D'    [-10,0.848398506641]
TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD TopHadWNonBJet2CSVv2_TOPTOPLEPHAD                                       'D'    [-10,0.846882283688]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsMass_TOPTOPLEPHBB", "MVA_TOPTOPLEPHBB", "MVA_TOPTOPLEPHAD", "TopLepMass_TOPTOPLEPHBB", "TopLepMass_TOPTOPLEPHAD", "HiggsBJet1HiggsBJet2Dr_TOPTOPLEPHBB", "TopLepHiggsDr_TOPTOPLEPHBB", "TopLepTopHadDr_TOPTOPLEPHAD", "HiggsBJet1CSVv2_TOPTOPLEPHBB", "HiggsBJet2CSVv2_TOPTOPLEPHBB", "TopLepBJetCSVv2_TOPTOPLEPHBB", "TopHadNonBJetCSVv2_TOPTOPLEPHBB", "TopLepBJetCSVv2_TOPTOPLEPHAD", "TopHadBJetCSVv2_TOPTOPLEPHAD", "TopHadWNonBJet1CSVv2_TOPTOPLEPHAD", "TopHadWNonBJet2CSVv2_TOPTOPLEPHAD" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';
      fType[15] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.236745111238684);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470879,-99) , 
9, 0.65025, 0, 0, 0.554223,-99) , 
11, 0.330364, 0, 0, 0.585751,-99) , 
NN(
0, 
0, 
-1, 0.238629, 1, -1, 0.347074,-99) , 
9, 0.475655, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.166432);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.330364, 0, 1, 0.611996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462358,-99) , 
2, 0.314042, 1, 0, 0.510897,-99) , 
9, 0.745099, 0, 0, 0.558481,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42774,-99) , 
5, 1.63729, 1, 0, 0.458987,-99) , 
NN(
0, 
0, 
-1, 0.475655, 0, -1, 0.348112,-99) , 
2, 0.235837, 1, 0, 0.408711,-99) , 
14, 0.331808, 0, 0, 0.496107,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.143294);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474598,-99) , 
0, 132.076, 1, 0, 0.55474,-99) , 
NN(
0, 
0, 
-1, 0.0700642, 1, -1, 0.444627,-99) , 
10, 0.47619, 0, 0, 0.533033,-99) , 
NN(
0, 
0, 
-1, 0.238629, 1, -1, 0.41646,-99) , 
9, 0.475655, 0, 0, 0.491621,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.096863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.744908, 0, 1, 0.585106,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488268,-99) , 
1, 0.0637736, 0, 0, 0.517611,-99) , 
NN(
0, 
0, 
-1, 0.475655, 0, -1, 0.44807,-99) , 
2, 0.154723, 1, 0, 0.481652,-99) , 
11, 0.330364, 0, 0, 0.498948,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0610149);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.330364, 0, 1, 0.527565,-99) , 
NN(
0, 
0, 
-1, 0.465226, 1, -1, 0.464241,-99) , 
9, 0.475655, 0, 0, 0.505116,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0544107);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564669,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493875,-99) , 
2, -0.220896, 1, 0, 0.502316,-99) , 
NN(
0, 
0, 
-1, 0.331803, 0, -1, 0.433969,-99) , 
2, 0.461039, 1, 0, 0.491063,-99) , 
15, 0.330364, 0, 0, 0.50068,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0570262);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.331808, 0, 1, 0.527113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467247,-99) , 
1, 0.202517, 0, 0, 0.484118,-99) , 
6, 3.52018, 1, 0, 0.517884,-99) , 
NN(
0, 
0, 
-1, 0.331803, 0, -1, 0.456696,-99) , 
2, 0.461039, 1, 0, 0.50785,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0481269);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497878,-99) , 
5, 1.13135, 1, 0, 0.507333,-99) , 
9, 0.904058, 0, 0, 0.518258,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479437,-99) , 
12, 0.94286, 0, 0, 0.497205,-99) , 
NN(
0, 
0, 
-1, 0.420242, 1, -1, 0.438691,-99) , 
2, 0.311768, 1, 0, 0.476754,-99) , 
14, 0.331808, 0, 0, 0.501072,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0526641);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.75, 0, 1, 0.533264,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474634,-99) , 
8, 0.982042, 0, 0, 0.490953,-99) , 
7, 3.48335, 1, 0, 0.52224,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476481,-99) , 
2, 0.0984267, 1, 0, 0.490126,-99) , 
NN(
0, 
0, 
-1, 0.496187, 1, -1, 0.443039,-99) , 
2, 0.387699, 1, 0, 0.478155,-99) , 
14, 0.331808, 0, 0, 0.503988,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0561992);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554731,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491854,-99) , 
15, 0.259636, 0, 0, 0.505405,-99) , 
14, 0.7746, 0, 0, 0.512676,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457657,-99) , 
10, 0.475805, 0, 0, 0.497655,-99) , 
NN(
0, 
0, 
-1, 0.0637736, 1, -1, 0.468315,-99) , 
9, 0.475655, 0, 0, 0.48016,-99) , 
14, 0.331808, 0, 0, 0.499211,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0436662);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475863,-99) , 
10, 0.61818, 0, 0, 0.522413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480279,-99) , 
8, 0.915782, 0, 0, 0.514929,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4762,-99) , 
10, 0.47619, 0, 0, 0.495589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454993,-99) , 
2, 0.463631, 1, 0, 0.488994,-99) , 
14, 0.331808, 0, 0, 0.504195,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0354741);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545578,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468992,-99) , 
1, -0.134481, 0, 0, 0.506528,-99) , 
NN(
0, 
0, 
-1, 0.475655, 0, -1, 0.483328,-99) , 
14, 0.331808, 0, 0, 0.496826,-99) , 
2, -0.304752, 1, 0, 0.500423,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0315402);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00156441, 1, 1, 0.516617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485663,-99) , 
0, 109.2, 1, 0, 0.494907,-99) , 
8, 0.981285, 0, 0, 0.505923,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509183,-99) , 
NN(
0, 
0, 
-1, 0.938299, 0, -1, 0.472202,-99) , 
6, 3.02609, 1, 0, 0.481977,-99) , 
7, 3.48018, 1, 0, 0.49968,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0147185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534657,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47032,-99) , 
3, 260.154, 1, 0, 0.497199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465296,-99) , 
2, 0.563146, 1, 0, 0.494869,-99) , 
2, -0.304752, 1, 0, 0.497801,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0209988);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530993,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479663,-99) , 
6, 3.52018, 1, 0, 0.49669,-99) , 
NN(
0, 
0, 
-1, -0.0248052, 1, -1, 0.478273,-99) , 
0, 131.806, 1, 0, 0.492377,-99) , 
2, -0.304752, 1, 0, 0.495221,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0251754);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53859,-99) , 
NN(
0, 
0, 
-1, 0.47619, 0, -1, 0.492588,-99) , 
4, 259.622, 0, 0, 0.496786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466335,-99) , 
1, -0.213714, 0, 0, 0.493758,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0238381);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492694,-99) , 
7, 2.97276, 1, 0, 0.497491,-99) , 
2, -0.228173, 1, 0, 0.501183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462808,-99) , 
1, -0.283085, 0, 0, 0.499017,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0201407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495913,-99) , 
8, 0.981781, 0, 0, 0.523996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4743,-99) , 
10, 0.47619, 0, 0, 0.499501,-99) , 
2, -0.14382, 1, 0, 0.503549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476162,-99) , 
1, -0.213714, 0, 0, 0.500828,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0203201);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487846,-99) , 
5, 1.84012, 1, 0, 0.51458,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476545,-99) , 
10, 0.47619, 0, 0, 0.498782,-99) , 
NN(
0, 
0, 
-1, 252.886, 1, -1, 0.484219,-99) , 
3, 194.741, 1, 0, 0.494562,-99) , 
2, -0.151594, 1, 0, 0.498252,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0218166);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496785,-99) , 
1, 0.133145, 0, 0, 0.513779,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493146,-99) , 
5, 0.887794, 1, 0, 0.495088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474925,-99) , 
2, 0.548559, 1, 0, 0.493106,-99) , 
2, -0.151594, 1, 0, 0.496915,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0260402);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 259.622, 0, 1, 0.508411,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460093,-99) , 
9, 0.475639, 1, 0, 0.483964,-99) , 
0, 85.7823, 0, 0, 0.504151,-99) , 
NN(
0, 
0, 
-1, 0.0626779, 1, -1, 0.485297,-99) , 
8, 0.915782, 0, 0, 0.50093,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0191668);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493876,-99) , 
5, 1.59955, 1, 0, 0.511852,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494819,-99) , 
0, 177.831, 0, 0, 0.496472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477669,-99) , 
2, 0.548559, 1, 0, 0.494624,-99) , 
2, -0.151594, 1, 0, 0.497796,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0151402);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494885,-99) , 
4, 188.63, 0, 0, 0.519217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48349,-99) , 
2, 0.548559, 1, 0, 0.500048,-99) , 
2, -0.151594, 1, 0, 0.503037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481581,-99) , 
3, 281.958, 1, 0, 0.501192,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0191779);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489588,-99) , 
13, 0.942861, 0, 0, 0.512489,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48199,-99) , 
0, 120.848, 1, 0, 0.498799,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475205,-99) , 
0, 166.873, 0, 0, 0.486721,-99) , 
0, 131.806, 1, 0, 0.496087,-99) , 
2, -0.151594, 1, 0, 0.499106,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0193658);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48987,-99) , 
5, 2.08069, 1, 0, 0.511205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510764,-99) , 
NN(
0, 
0, 
-1, 3.3966, 1, -1, 0.492411,-99) , 
13, 0.866671, 1, 0, 0.493771,-99) , 
2, -0.151594, 1, 0, 0.49698,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0176179);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.470096, 0, 1, 0.518125,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473539,-99) , 
10, 0.725624, 0, 0, 0.500442,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454329,-99) , 
0, 109.822, 0, 0, 0.481817,-99) , 
10, 0.47619, 0, 0, 0.497957,-99) , 
1, 0.410632, 0, 0, 0.500044,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0168927);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.470096, 0, 1, 0.513725,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513401,-99) , 
NN(
0, 
0, 
-1, -0.243446, 0, -1, 0.492771,-99) , 
6, 2.01364, 1, 0, 0.4948,-99) , 
1, 0.410632, 0, 0, 0.496758,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0156091);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524765,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495935,-99) , 
11, 0.329786, 0, 0, 0.498195,-99) , 
4, 259.622, 0, 0, 0.500723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47657,-99) , 
1, -0.283085, 0, 0, 0.499362,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0125475);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494775,-99) , 
4, 188.63, 0, 0, 0.516503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498615,-99) , 
5, 0.887794, 1, 0, 0.499984,-99) , 
2, -0.151594, 1, 0, 0.502723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480466,-99) , 
1, -0.283085, 0, 0, 0.50147,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0339804);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497335,-99) , 
9, 0.475655, 0, 0, 0.512547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485541,-99) , 
5, 1.63416, 1, 0, 0.495213,-99) , 
0, 125.232, 1, 0, 0.50604,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474282,-99) , 
9, 0.475639, 1, 0, 0.492232,-99) , 
0, 85.7823, 0, 0, 0.503549,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0155319);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.38537, 1, 1, 0.513584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483144,-99) , 
2, 0.585027, 1, 0, 0.50184,-99) , 
2, 0.00156441, 1, 0, 0.505433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48767,-99) , 
3, 281.958, 1, 0, 0.503908,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0171398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499239,-99) , 
5, 1.84242, 1, 0, 0.518287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491497,-99) , 
7, 3.46433, 1, 0, 0.499789,-99) , 
2, -0.151594, 1, 0, 0.503242,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492246,-99) , 
9, 0.475639, 1, 0, 0.500498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469701,-99) , 
1, -0.0978274, 0, 0, 0.491326,-99) , 
0, 85.7823, 0, 0, 0.501093,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0196853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.25178, 1, 1, 0.51395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491582,-99) , 
13, 0.933338, 0, 0, 0.506821,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49467,-99) , 
10, 0.850341, 1, 0, 0.498187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480516,-99) , 
10, 0.47619, 0, 0, 0.496514,-99) , 
2, 0.00156441, 1, 0, 0.500032,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0126965);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517943,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49907,-99) , 
4, 199.416, 0, 0, 0.503068,-99) , 
NN(
0, 
0, 
-1, 0.0655092, 1, -1, 0.487743,-99) , 
12, 0.911114, 0, 0, 0.500817,-99) , 
12, 0.866671, 1, 0, 0.501919,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0157138);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.850341, 1, 1, 0.506371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471799,-99) , 
9, 0.934708, 0, 0, 0.489901,-99) , 
10, 0.47619, 0, 0, 0.504438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490408,-99) , 
3, 281.958, 1, 0, 0.503234,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0296016);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487051,-99) , 
0, 127.423, 1, 0, 0.496203,-99) , 
5, 1.38537, 1, 0, 0.503686,-99) , 
NN(
NN(
0, 
0, 
-1, 0.229451, 1, 1, 0.51237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478651,-99) , 
9, 0.475639, 1, 0, 0.488178,-99) , 
5, 1.87989, 0, 0, 0.496552,-99) , 
0, 108.794, 0, 0, 0.500395,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0332575);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.38053, 1, 1, 0.511636,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479824,-99) , 
9, 0.799902, 0, 0, 0.502373,-99) , 
NN(
0, 
0, 
-1, 121.944, 1, -1, 0.488969,-99) , 
9, 0.475655, 0, 0, 0.497699,-99) , 
0, 154.819, 0, 0, 0.499414,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0183115);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.857468, 1, 1, 0.505698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468602,-99) , 
10, 0.700681, 0, 0, 0.502679,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462223,-99) , 
0, 109.822, 0, 0, 0.485478,-99) , 
10, 0.47619, 0, 0, 0.500496,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0222107);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496053,-99) , 
10, 0.857468, 1, 0, 0.50112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473164,-99) , 
10, 0.700681, 0, 0, 0.498846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467016,-99) , 
1, 0.146675, 0, 0, 0.484902,-99) , 
10, 0.47619, 0, 0, 0.497077,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0154894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.857468, 1, 1, 0.505462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478704,-99) , 
10, 0.700681, 0, 0, 0.503286,-99) , 
NN(
0, 
0, 
-1, 0.927516, 0, -1, 0.485411,-99) , 
10, 0.47619, 0, 0, 0.501018,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0151938);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510616,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481759,-99) , 
9, 0.475536, 0, 0, 0.505354,-99) , 
NN(
0, 
0, 
-1, 0.47619, 0, -1, 0.495464,-99) , 
1, 0.341261, 0, 0, 0.497345,-99) , 
5, 0.887794, 1, 0, 0.498678,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0131223);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485767,-99) , 
10, 0.47619, 0, 0, 0.501081,-99) , 
4, 259.622, 0, 0, 0.50265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485682,-99) , 
2, 0.312502, 0, 0, 0.491871,-99) , 
13, 0.895241, 0, 0, 0.500895,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0128629);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493393,-99) , 
1, 0.217288, 1, 0, 0.499064,-99) , 
4, 263.827, 0, 0, 0.500582,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505395,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479757,-99) , 
1, 0.0655092, 1, 0, 0.487811,-99) , 
12, 0.86531, 1, 0, 0.492767,-99) , 
12, 0.914289, 0, 0, 0.498916,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.012889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498371,-99) , 
4, 237.769, 0, 0, 0.502325,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490941,-99) , 
9, 0.458261, 1, 0, 0.495423,-99) , 
8, 0.981285, 0, 0, 0.498902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484571,-99) , 
1, -0.283085, 0, 0, 0.498095,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0153217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52121,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490602,-99) , 
1, -0.123404, 0, 0, 0.500483,-99) , 
1, 0.410946, 0, 0, 0.502553,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493156,-99) , 
9, 0.44935, 1, 0, 0.504158,-99) , 
NN(
0, 
0, 
-1, 0.159905, 0, -1, 0.491034,-99) , 
1, 0.0637736, 1, 0, 0.495929,-99) , 
8, 0.971927, 0, 0, 0.499752,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0102934);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496982,-99) , 
3, 182.284, 1, 0, 0.50746,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491611,-99) , 
6, 3.31233, 1, 0, 0.499047,-99) , 
5, 2.8781, 0, 0, 0.500198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487785,-99) , 
3, 129.329, 0, 0, 0.499442,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0130633);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496185,-99) , 
9, 0.475641, 1, 0, 0.505815,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489736,-99) , 
0, 109.679, 0, 0, 0.504406,-99) , 
NN(
0, 
0, 
-1, 0.475655, 0, -1, 0.495923,-99) , 
2, -0.151594, 1, 0, 0.497524,-99) , 
5, 2.8781, 0, 0, 0.498657,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0124207);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516612,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486843,-99) , 
5, 1.63015, 0, 0, 0.500044,-99) , 
4, 199.416, 0, 0, 0.504666,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49041,-99) , 
10, 0.47619, 0, 0, 0.500545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485731,-99) , 
3, 281.958, 1, 0, 0.499233,-99) , 
12, 0.990476, 0, 0, 0.501002,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0115637);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487249,-99) , 
7, 2.91448, 0, 0, 0.498407,-99) , 
2, 0.00232179, 1, 0, 0.503114,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506126,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494971,-99) , 
5, 2.8781, 0, 0, 0.4963,-99) , 
1, 0.410632, 0, 0, 0.497331,-99) , 
12, 0.990476, 0, 0, 0.499214,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0148533);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0570563, 1, 1, 0.514609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488481,-99) , 
6, 3.1907, 1, 0, 0.505506,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498566,-99) , 
1, 0.306165, 0, 0, 0.502426,-99) , 
NN(
0, 
0, 
-1, -0.00660962, 1, -1, 0.491154,-99) , 
0, 124.206, 1, 0, 0.498331,-99) , 
5, 1.13658, 1, 0, 0.499626,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0260613);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.88589, 0, 1, 0.517917,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480601,-99) , 
1, -0.192593, 0, 0, 0.497449,-99) , 
9, 0.475641, 1, 0, 0.504747,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494567,-99) , 
9, 0.924612, 0, 0, 0.505695,-99) , 
NN(
0, 
0, 
-1, 123.605, 1, -1, 0.488146,-99) , 
9, 0.475655, 0, 0, 0.499461,-99) , 
1, 0.0637736, 1, 0, 0.501397,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.022753);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483085,-99) , 
0, 105.507, 0, 0, 0.5133,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493585,-99) , 
0, 125.232, 1, 0, 0.502143,-99) , 
5, 1.38537, 1, 0, 0.50426,-99) , 
NN(
NN(
0, 
0, 
-1, 3.18761, 0, 1, 0.508015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47981,-99) , 
1, -0.0408794, 0, 0, 0.496855,-99) , 
0, 85.7823, 0, 0, 0.502923,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0161937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532405,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490344,-99) , 
13, 0.895241, 0, 0, 0.49973,-99) , 
5, 1.38537, 1, 0, 0.50471,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485446,-99) , 
10, 0.875286, 0, 0, 0.501107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477753,-99) , 
10, 0.47619, 0, 0, 0.498405,-99) , 
0, 108.794, 0, 0, 0.501799,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0168996);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499001,-99) , 
9, 0.475594, 1, 0, 0.508229,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487589,-99) , 
9, 0.475655, 0, 0, 0.498347,-99) , 
1, -0.00559821, 1, 0, 0.500719,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492381,-99) , 
1, 0.0452344, 0, 0, 0.500863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479993,-99) , 
3, 195.935, 1, 0, 0.493792,-99) , 
0, 85.7823, 0, 0, 0.499469,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0149622);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491439,-99) , 
4, 242.357, 1, 0, 0.509364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486283,-99) , 
2, 0.231302, 1, 0, 0.503906,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506727,-99) , 
NN(
0, 
0, 
-1, 0.475655, 0, -1, 0.495484,-99) , 
11, 0.329595, 0, 0, 0.497326,-99) , 
1, -0.00559821, 1, 0, 0.49918,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0125504);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498694,-99) , 
5, 1.38537, 1, 0, 0.503521,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492381,-99) , 
5, 1.54909, 0, 0, 0.499025,-99) , 
0, 108.794, 0, 0, 0.501442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492377,-99) , 
3, 129.329, 0, 0, 0.500889,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.014269);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497628,-99) , 
9, 0.475655, 1, 0, 0.500936,-99) , 
5, 1.38537, 1, 0, 0.504892,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490169,-99) , 
10, 0.875286, 0, 0, 0.501154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48294,-99) , 
10, 0.47619, 0, 0, 0.499048,-99) , 
0, 108.794, 0, 0, 0.502193,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0135688);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499311,-99) , 
2, 0.307881, 0, 0, 0.502001,-99) , 
5, 1.38537, 1, 0, 0.505251,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495192,-99) , 
5, 1.71493, 0, 0, 0.506309,-99) , 
NN(
0, 
0, 
-1, 178.856, 1, -1, 0.494081,-99) , 
12, 0.933337, 1, 0, 0.497652,-99) , 
0, 108.794, 0, 0, 0.501742,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0160106);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496952,-99) , 
0, 85.7823, 0, 0, 0.511329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490162,-99) , 
9, 0.475655, 0, 0, 0.500973,-99) , 
1, 0.0637736, 1, 0, 0.505862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486786,-99) , 
1, 0.0834687, 0, 0, 0.4968,-99) , 
7, 3.89212, 0, 0, 0.499793,-99) , 
2, 0.231302, 1, 0, 0.503188,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0256612);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.85351, 1, 1, 0.510363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494949,-99) , 
2, 0.231302, 1, 0, 0.506718,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482645,-99) , 
9, 0.799902, 0, 0, 0.501804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474088,-99) , 
0, 123.595, 1, 0, 0.494265,-99) , 
9, 0.475655, 0, 0, 0.49913,-99) , 
1, -0.00559821, 1, 0, 0.501268,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.00849227);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.981285, 1, 1, 0.507103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494058,-99) , 
12, 0.914298, 0, 0, 0.504365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504381,-99) , 
NN(
0, 
0, 
-1, 98.9319, 0, -1, 0.496721,-99) , 
15, 0.329786, 0, 0, 0.497752,-99) , 
0, 131.806, 0, 0, 0.499329,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.00591254);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507185,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499718,-99) , 
5, 1.33802, 1, 0, 0.501022,-99) , 
NN(
0, 
0, 
-1, 0.388757, 1, -1, 0.494487,-99) , 
0, 96.599, 0, 0, 0.49944,-99) , 
5, 0.887794, 1, 0, 0.500217,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.00872159);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49565,-99) , 
14, 0.331808, 0, 0, 0.507753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488945,-99) , 
2, -0.250055, 0, 0, 0.500637,-99) , 
5, 1.13658, 1, 0, 0.501855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494026,-99) , 
2, 0.537618, 1, 0, 0.501156,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0195647);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.164164, 1, 1, 0.511129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489988,-99) , 
6, 2.85351, 1, 0, 0.499028,-99) , 
9, 0.475629, 1, 0, 0.503369,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494843,-99) , 
9, 0.924612, 0, 0, 0.502008,-99) , 
NN(
0, 
0, 
-1, 0.380906, 1, -1, 0.492425,-99) , 
9, 0.475655, 0, 0, 0.498608,-99) , 
1, -0.00559821, 1, 0, 0.49995,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00886959);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510631,-99) , 
NN(
NN(
0, 
0, 
-1, 2.13174, 0, 1, 0.507556,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498265,-99) , 
4, 263.827, 0, 0, 0.49984,-99) , 
8, 0.934497, 1, 0, 0.501604,-99) , 
12, 0.866671, 1, 0, 0.502183,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0232692);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.808667, 0, 1, 0.50839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477485,-99) , 
10, 0.61818, 0, 0, 0.504531,-99) , 
NN(
NN(
0, 
0, 
-1, 0.475805, 0, 1, 0.517663,-99) , 
NN(
0, 
0, 
-1, 1.63729, 0, -1, 0.488919,-99) , 
9, 0.475655, 0, 0, 0.500458,-99) , 
14, 0.331808, 0, 0, 0.502844,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0112508);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.857468, 1, 1, 0.503402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48074,-99) , 
10, 0.700681, 0, 0, 0.501566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482492,-99) , 
4, 181.172, 0, 0, 0.495224,-99) , 
10, 0.47619, 0, 0, 0.500763,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0242641);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490724,-99) , 
4, 180.824, 1, 0, 0.504384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49488,-99) , 
5, 1.05365, 1, 0, 0.497559,-99) , 
5, 2.38053, 0, 0, 0.499633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45181,-99) , 
9, 0.744908, 0, 0, 0.49393,-99) , 
11, 0.330364, 1, 0, 0.498691,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0190317);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499802,-99) , 
2, 0.216461, 0, 0, 0.508551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493382,-99) , 
7, 3.20684, 1, 0, 0.500524,-99) , 
7, 3.9559, 0, 0, 0.501573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457826,-99) , 
9, 0.744908, 0, 0, 0.493198,-99) , 
11, 0.330364, 1, 0, 0.500191,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0149363);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 177.662, 1, 1, 0.508726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497707,-99) , 
0, 154.819, 0, 0, 0.498914,-99) , 
7, 3.9559, 0, 0, 0.500196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465313,-99) , 
11, 0.453345, 0, 0, 0.492622,-99) , 
11, 0.330364, 1, 0, 0.498947,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0136739);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.934497, 1, 1, 0.502976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493659,-99) , 
12, 0.876195, 0, 0, 0.502159,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463225,-99) , 
9, 0.744908, 0, 0, 0.492539,-99) , 
11, 0.330364, 1, 0, 0.500573,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0124719);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490458,-99) , 
10, 0.47619, 0, 0, 0.500144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49233,-99) , 
4, 259.622, 1, 0, 0.49934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466626,-99) , 
9, 0.744908, 0, 0, 0.492126,-99) , 
11, 0.330364, 1, 0, 0.498151,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0105561);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495278,-99) , 
12, 0.895244, 1, 0, 0.496331,-99) , 
4, 281.474, 0, 0, 0.497305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487457,-99) , 
0, 200.843, 1, 0, 0.49665,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0160747);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495267,-99) , 
9, 0.475655, 0, 0, 0.501269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491561,-99) , 
4, 172.211, 1, 0, 0.496891,-99) , 
0, 108.794, 0, 0, 0.499246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470938,-99) , 
11, 0.453345, 0, 0, 0.493209,-99) , 
11, 0.330364, 1, 0, 0.498251,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0280937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.238629, 1, 1, 0.509297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481211,-99) , 
0, 85.7823, 1, 0, 0.489115,-99) , 
5, 1.63729, 0, 0, 0.501517,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48681,-99) , 
0, 109.822, 0, 0, 0.51541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485612,-99) , 
14, 0.331808, 1, 0, 0.490278,-99) , 
9, 0.924612, 0, 0, 0.49596,-99) , 
9, 0.475655, 1, 0, 0.497939,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0114555);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489742,-99) , 
0, 95.9269, 0, 0, 0.503807,-99) , 
NN(
0, 
0, 
-1, 0.47619, 0, -1, 0.497042,-99) , 
4, 194.064, 0, 0, 0.499238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48818,-99) , 
0, 200.843, 1, 0, 0.498502,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0245082);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491015,-99) , 
14, 0.373979, 0, 0, 0.514944,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477966,-99) , 
14, 0.567261, 0, 0, 0.496595,-99) , 
14, 0.479406, 1, 0, 0.502253,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491739,-99) , 
2, 0.238489, 1, 0, 0.503655,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473124,-99) , 
2, 0.235837, 0, 0, 0.486392,-99) , 
5, 1.63729, 0, 0, 0.497219,-99) , 
14, 0.331808, 0, 0, 0.500167,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00587093);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498949,-99) , 
7, 3.83297, 0, 0, 0.499853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488513,-99) , 
7, 4.4679, 1, 0, 0.499177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488476,-99) , 
0, 200.843, 1, 0, 0.498464,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0062717);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491329,-99) , 
8, 0.878352, 0, 0, 0.501023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48998,-99) , 
7, 4.4679, 1, 0, 0.500364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489943,-99) , 
0, 200.843, 1, 0, 0.49967,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00787189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498962,-99) , 
8, 0.934497, 1, 0, 0.500357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490311,-99) , 
2, 0.38446, 0, 0, 0.494864,-99) , 
12, 0.914289, 0, 0, 0.499188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489951,-99) , 
1, -0.283085, 0, 0, 0.498668,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.00550427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.150685, 1, 1, 0.50155,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487854,-99) , 
2, 0.0781436, 0, 0, 0.495826,-99) , 
12, 0.914289, 0, 0, 0.500332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491918,-99) , 
1, -0.283085, 0, 0, 0.499859,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00382293);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492661,-99) , 
7, 4.36037, 1, 0, 0.499915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491823,-99) , 
8, 0.879023, 0, 0, 0.499348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491379,-99) , 
3, 129.329, 0, 0, 0.498862,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0071645);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49733,-99) , 
13, 0.866671, 1, 0, 0.498095,-99) , 
4, 281.474, 0, 0, 0.498705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492149,-99) , 
0, 200.843, 1, 0, 0.498269,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00566218);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499753,-99) , 
7, 2.79997, 1, 0, 0.500984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492617,-99) , 
7, 2.43282, 0, 0, 0.500273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491424,-99) , 
2, 0.312502, 0, 0, 0.496012,-99) , 
13, 0.895241, 0, 0, 0.499579,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00614086);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.79997, 1, 1, 0.502064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494033,-99) , 
7, 2.43282, 0, 0, 0.501381,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492004,-99) , 
6, 2.89114, 1, 0, 0.49649,-99) , 
13, 0.895241, 0, 0, 0.500584,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00795912);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4894,-99) , 
10, 0.47619, 0, 0, 0.500987,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484212,-99) , 
7, 3.35248, 1, 0, 0.494997,-99) , 
3, 235.235, 1, 0, 0.49996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493752,-99) , 
3, 129.329, 0, 0, 0.499582,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00544227);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504099,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495878,-99) , 
5, 2.11952, 1, 0, 0.498661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488426,-99) , 
8, 0.879023, 0, 0, 0.497951,-99) , 
4, 128.506, 1, 0, 0.498407,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0097433);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497303,-99) , 
1, 0.133145, 0, 0, 0.500145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487031,-99) , 
14, 0.331789, 0, 0, 0.495247,-99) , 
2, 0.384839, 1, 0, 0.498898,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490108,-99) , 
2, 0.0781436, 0, 0, 0.498567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486527,-99) , 
12, 0.897962, 1, 0, 0.495411,-99) , 
12, 0.914289, 0, 0, 0.498155,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0134366);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49701,-99) , 
0, 108.794, 0, 0, 0.502612,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483429,-99) , 
6, 3.21914, 0, 0, 0.492125,-99) , 
5, 2.31723, 1, 0, 0.499527,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497395,-99) , 
9, 0.47565, 1, 0, 0.501276,-99) , 
NN(
0, 
0, 
-1, 0.331803, 0, -1, 0.491498,-99) , 
5, 1.88589, 0, 0, 0.496806,-99) , 
4, 172.211, 0, 0, 0.498247,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00510679);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504949,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498133,-99) , 
1, 0.0646108, 1, 0, 0.499481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49076,-99) , 
8, 0.879023, 0, 0, 0.498876,-99) , 
4, 128.506, 1, 0, 0.499327,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0122176);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49632,-99) , 
9, 0.924612, 0, 0, 0.501856,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481646,-99) , 
0, 130.709, 1, 0, 0.496537,-99) , 
9, 0.475655, 0, 0, 0.49999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494253,-99) , 
0, 200.843, 1, 0, 0.499609,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0149927);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516519,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495612,-99) , 
14, 0.331808, 1, 0, 0.498796,-99) , 
9, 0.949554, 0, 0, 0.50172,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496979,-99) , 
13, 0.897902, 0, 0, 0.50729,-99) , 
NN(
0, 
0, 
-1, 0.978343, 0, -1, 0.493461,-99) , 
13, 0.935029, 1, 0, 0.497417,-99) , 
9, 0.475655, 0, 0, 0.500188,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0290221);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479974,-99) , 
15, 0.138672, 0, 0, 0.513377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489692,-99) , 
11, 0.330364, 0, 0, 0.497984,-99) , 
9, 0.649725, 1, 0, 0.504269,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49578,-99) , 
2, 0.314042, 1, 0, 0.504612,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479138,-99) , 
9, 0.475588, 0, 0, 0.488128,-99) , 
5, 1.63729, 0, 0, 0.498468,-99) , 
14, 0.331808, 0, 0, 0.501865,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0176967);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00232179, 1, 1, 0.513371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480839,-99) , 
10, 0.745453, 0, 0, 0.499133,-99) , 
5, 1.62543, 1, 0, 0.504735,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497726,-99) , 
12, 0.952384, 1, 0, 0.502493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480163,-99) , 
2, 0.235837, 0, 0, 0.489669,-99) , 
5, 1.63729, 0, 0, 0.497713,-99) , 
14, 0.331808, 0, 0, 0.501825,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0235158);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48575,-99) , 
14, 0.651602, 1, 0, 0.505202,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490529,-99) , 
5, 1.63729, 0, 0, 0.4987,-99) , 
14, 0.331808, 0, 0, 0.502013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47316,-99) , 
11, 0.453345, 0, 0, 0.491555,-99) , 
11, 0.330364, 1, 0, 0.50029,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0142115);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497974,-99) , 
9, 0.65025, 1, 0, 0.503506,-99) , 
NN(
0, 
0, 
-1, 0.341261, 1, -1, 0.495915,-99) , 
9, 0.475655, 0, 0, 0.500381,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473372,-99) , 
9, 0.744908, 0, 0, 0.491427,-99) , 
11, 0.330364, 1, 0, 0.498906,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0116081);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499885,-99) , 
9, 0.475629, 0, 0, 0.508621,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487547,-99) , 
2, -0.228173, 0, 0, 0.500816,-99) , 
5, 1.38537, 1, 0, 0.502963,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476916,-99) , 
9, 0.744908, 0, 0, 0.491,-99) , 
11, 0.330364, 1, 0, 0.500993,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0123839);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494488,-99) , 
9, 0.475629, 1, 0, 0.501529,-99) , 
0, 108.794, 0, 0, 0.505691,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49501,-99) , 
0, 114.227, 1, 0, 0.498681,-99) , 
NN(
0, 
0, 
-1, 0.982115, 1, -1, 0.488573,-99) , 
0, 150.62, 1, 0, 0.496997,-99) , 
5, 1.38537, 1, 0, 0.499408,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00869563);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499691,-99) , 
9, 0.475629, 0, 0, 0.507499,-99) , 
NN(
0, 
0, 
-1, 242.357, 1, -1, 0.498726,-99) , 
5, 1.38537, 1, 0, 0.501139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479753,-99) , 
11, 0.453345, 0, 0, 0.491071,-99) , 
11, 0.330364, 1, 0, 0.499481,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00975805);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499097,-99) , 
6, 3.18501, 1, 0, 0.507152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491906,-99) , 
4, 242.357, 1, 0, 0.5009,-99) , 
5, 1.38537, 1, 0, 0.502619,-99) , 
NN(
0, 
0, 
-1, 0.744908, 0, -1, 0.491024,-99) , 
11, 0.330364, 1, 0, 0.50071,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
